/*
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.amesh.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.amesh.client.model.Weight;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.amesh.client.ApiClient;
/**
 * AgentRubricCriterionInput
 */
@JsonPropertyOrder({
  AgentRubricCriterionInput.JSON_PROPERTY_ASSERTION,
  AgentRubricCriterionInput.JSON_PROPERTY_DESCRIPTION,
  AgentRubricCriterionInput.JSON_PROPERTY_KEY,
  AgentRubricCriterionInput.JSON_PROPERTY_WEIGHT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class AgentRubricCriterionInput {
  public static final String JSON_PROPERTY_ASSERTION = "assertion";
  @javax.annotation.Nonnull
  private Map<String, Object> assertion = new HashMap<>();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nonnull
  private String description;

  public static final String JSON_PROPERTY_KEY = "key";
  @javax.annotation.Nonnull
  private String key;

  public static final String JSON_PROPERTY_WEIGHT = "weight";
  @javax.annotation.Nullable
  private Weight weight;

  public AgentRubricCriterionInput() {
  }

  public AgentRubricCriterionInput assertion(@javax.annotation.Nonnull Map<String, Object> assertion) {
    this.assertion = assertion;
    return this;
  }

  public AgentRubricCriterionInput putAssertionItem(String key, Object assertionItem) {
    if (this.assertion == null) {
      this.assertion = new HashMap<>();
    }
    this.assertion.put(key, assertionItem);
    return this;
  }

  /**
   * Get assertion
   * @return assertion
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ASSERTION, required = true)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public Map<String, Object> getAssertion() {
    return assertion;
  }


  @JsonProperty(value = JSON_PROPERTY_ASSERTION, required = true)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public void setAssertion(@javax.annotation.Nonnull Map<String, Object> assertion) {
    this.assertion = assertion;
  }


  public AgentRubricCriterionInput description(@javax.annotation.Nonnull String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(@javax.annotation.Nonnull String description) {
    this.description = description;
  }


  public AgentRubricCriterionInput key(@javax.annotation.Nonnull String key) {
    this.key = key;
    return this;
  }

  /**
   * Get key
   * @return key
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getKey() {
    return key;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKey(@javax.annotation.Nonnull String key) {
    this.key = key;
  }


  public AgentRubricCriterionInput weight(@javax.annotation.Nullable Weight weight) {
    this.weight = weight;
    return this;
  }

  /**
   * Get weight
   * @return weight
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Weight getWeight() {
    return weight;
  }


  @JsonProperty(value = JSON_PROPERTY_WEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeight(@javax.annotation.Nullable Weight weight) {
    this.weight = weight;
  }


  /**
   * Return true if this AgentRubricCriterion-Input object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgentRubricCriterionInput agentRubricCriterionInput = (AgentRubricCriterionInput) o;
    return Objects.equals(this.assertion, agentRubricCriterionInput.assertion) &&
        Objects.equals(this.description, agentRubricCriterionInput.description) &&
        Objects.equals(this.key, agentRubricCriterionInput.key) &&
        Objects.equals(this.weight, agentRubricCriterionInput.weight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assertion, description, key, weight);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgentRubricCriterionInput {\n");
    sb.append("    assertion: ").append(toIndentedString(assertion)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `assertion` to the URL query string
    if (getAssertion() != null) {
      for (String _key : getAssertion().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sassertion%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getAssertion().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getAssertion().get(_key)))));
      }
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `key` to the URL query string
    if (getKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%skey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKey()))));
    }

    // add `weight` to the URL query string
    if (getWeight() != null) {
      joiner.add(getWeight().toUrlQueryString(prefix + "weight" + suffix));
    }

    return joiner.toString();
  }
}
