/*
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.amesh.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.amesh.client.ApiClient;
/**
 * AgentSessionFleetAggregates
 */
@JsonPropertyOrder({
  AgentSessionFleetAggregates.JSON_PROPERTY_ACTIVE,
  AgentSessionFleetAggregates.JSON_PROPERTY_BY_STATE,
  AgentSessionFleetAggregates.JSON_PROPERTY_DEGRADED_DEPENDENCIES,
  AgentSessionFleetAggregates.JSON_PROPERTY_FAILED_INVOCATIONS,
  AgentSessionFleetAggregates.JSON_PROPERTY_MATCHED_EXECUTIONS,
  AgentSessionFleetAggregates.JSON_PROPERTY_MODEL_INVOCATIONS,
  AgentSessionFleetAggregates.JSON_PROPERTY_TERMINAL,
  AgentSessionFleetAggregates.JSON_PROPERTY_TOOL_INVOCATIONS,
  AgentSessionFleetAggregates.JSON_PROPERTY_TOTAL_COST_USD,
  AgentSessionFleetAggregates.JSON_PROPERTY_TOTAL_TOKENS,
  AgentSessionFleetAggregates.JSON_PROPERTY_TOTAL_TOOL_CALLS,
  AgentSessionFleetAggregates.JSON_PROPERTY_TOTAL_TURNS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class AgentSessionFleetAggregates {
  public static final String JSON_PROPERTY_ACTIVE = "active";
  @javax.annotation.Nonnull
  private Integer active;

  public static final String JSON_PROPERTY_BY_STATE = "byState";
  @javax.annotation.Nullable
  private Map<String, Integer> byState = new HashMap<>();

  public static final String JSON_PROPERTY_DEGRADED_DEPENDENCIES = "degradedDependencies";
  @javax.annotation.Nullable
  private Integer degradedDependencies = 0;

  public static final String JSON_PROPERTY_FAILED_INVOCATIONS = "failedInvocations";
  @javax.annotation.Nullable
  private Integer failedInvocations = 0;

  public static final String JSON_PROPERTY_MATCHED_EXECUTIONS = "matchedExecutions";
  @javax.annotation.Nonnull
  private Integer matchedExecutions;

  public static final String JSON_PROPERTY_MODEL_INVOCATIONS = "modelInvocations";
  @javax.annotation.Nullable
  private Integer modelInvocations = 0;

  public static final String JSON_PROPERTY_TERMINAL = "terminal";
  @javax.annotation.Nonnull
  private Integer terminal;

  public static final String JSON_PROPERTY_TOOL_INVOCATIONS = "toolInvocations";
  @javax.annotation.Nullable
  private Integer toolInvocations = 0;

  public static final String JSON_PROPERTY_TOTAL_COST_USD = "totalCostUsd";
  @javax.annotation.Nullable
  private String totalCostUsd = "0";

  public static final String JSON_PROPERTY_TOTAL_TOKENS = "totalTokens";
  @javax.annotation.Nullable
  private Integer totalTokens = 0;

  public static final String JSON_PROPERTY_TOTAL_TOOL_CALLS = "totalToolCalls";
  @javax.annotation.Nullable
  private Integer totalToolCalls = 0;

  public static final String JSON_PROPERTY_TOTAL_TURNS = "totalTurns";
  @javax.annotation.Nullable
  private Integer totalTurns = 0;

  public AgentSessionFleetAggregates() {
  }

  public AgentSessionFleetAggregates active(@javax.annotation.Nonnull Integer active) {
    this.active = active;
    return this;
  }

  /**
   * Get active
   * minimum: 0
   * @return active
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ACTIVE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getActive() {
    return active;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTIVE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setActive(@javax.annotation.Nonnull Integer active) {
    this.active = active;
  }


  public AgentSessionFleetAggregates byState(@javax.annotation.Nullable Map<String, Integer> byState) {
    this.byState = byState;
    return this;
  }

  public AgentSessionFleetAggregates putByStateItem(String key, Integer byStateItem) {
    if (this.byState == null) {
      this.byState = new HashMap<>();
    }
    this.byState.put(key, byStateItem);
    return this;
  }

  /**
   * Get byState
   * @return byState
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BY_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Integer> getByState() {
    return byState;
  }


  @JsonProperty(value = JSON_PROPERTY_BY_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setByState(@javax.annotation.Nullable Map<String, Integer> byState) {
    this.byState = byState;
  }


  public AgentSessionFleetAggregates degradedDependencies(@javax.annotation.Nullable Integer degradedDependencies) {
    this.degradedDependencies = degradedDependencies;
    return this;
  }

  /**
   * Get degradedDependencies
   * minimum: 0
   * @return degradedDependencies
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEGRADED_DEPENDENCIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getDegradedDependencies() {
    return degradedDependencies;
  }


  @JsonProperty(value = JSON_PROPERTY_DEGRADED_DEPENDENCIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDegradedDependencies(@javax.annotation.Nullable Integer degradedDependencies) {
    this.degradedDependencies = degradedDependencies;
  }


  public AgentSessionFleetAggregates failedInvocations(@javax.annotation.Nullable Integer failedInvocations) {
    this.failedInvocations = failedInvocations;
    return this;
  }

  /**
   * Get failedInvocations
   * minimum: 0
   * @return failedInvocations
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FAILED_INVOCATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getFailedInvocations() {
    return failedInvocations;
  }


  @JsonProperty(value = JSON_PROPERTY_FAILED_INVOCATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFailedInvocations(@javax.annotation.Nullable Integer failedInvocations) {
    this.failedInvocations = failedInvocations;
  }


  public AgentSessionFleetAggregates matchedExecutions(@javax.annotation.Nonnull Integer matchedExecutions) {
    this.matchedExecutions = matchedExecutions;
    return this;
  }

  /**
   * Get matchedExecutions
   * minimum: 0
   * @return matchedExecutions
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MATCHED_EXECUTIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getMatchedExecutions() {
    return matchedExecutions;
  }


  @JsonProperty(value = JSON_PROPERTY_MATCHED_EXECUTIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMatchedExecutions(@javax.annotation.Nonnull Integer matchedExecutions) {
    this.matchedExecutions = matchedExecutions;
  }


  public AgentSessionFleetAggregates modelInvocations(@javax.annotation.Nullable Integer modelInvocations) {
    this.modelInvocations = modelInvocations;
    return this;
  }

  /**
   * Get modelInvocations
   * minimum: 0
   * @return modelInvocations
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MODEL_INVOCATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getModelInvocations() {
    return modelInvocations;
  }


  @JsonProperty(value = JSON_PROPERTY_MODEL_INVOCATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModelInvocations(@javax.annotation.Nullable Integer modelInvocations) {
    this.modelInvocations = modelInvocations;
  }


  public AgentSessionFleetAggregates terminal(@javax.annotation.Nonnull Integer terminal) {
    this.terminal = terminal;
    return this;
  }

  /**
   * Get terminal
   * minimum: 0
   * @return terminal
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TERMINAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getTerminal() {
    return terminal;
  }


  @JsonProperty(value = JSON_PROPERTY_TERMINAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTerminal(@javax.annotation.Nonnull Integer terminal) {
    this.terminal = terminal;
  }


  public AgentSessionFleetAggregates toolInvocations(@javax.annotation.Nullable Integer toolInvocations) {
    this.toolInvocations = toolInvocations;
    return this;
  }

  /**
   * Get toolInvocations
   * minimum: 0
   * @return toolInvocations
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOOL_INVOCATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getToolInvocations() {
    return toolInvocations;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOL_INVOCATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToolInvocations(@javax.annotation.Nullable Integer toolInvocations) {
    this.toolInvocations = toolInvocations;
  }


  public AgentSessionFleetAggregates totalCostUsd(@javax.annotation.Nullable String totalCostUsd) {
    this.totalCostUsd = totalCostUsd;
    return this;
  }

  /**
   * Get totalCostUsd
   * @return totalCostUsd
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_COST_USD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTotalCostUsd() {
    return totalCostUsd;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_COST_USD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalCostUsd(@javax.annotation.Nullable String totalCostUsd) {
    this.totalCostUsd = totalCostUsd;
  }


  public AgentSessionFleetAggregates totalTokens(@javax.annotation.Nullable Integer totalTokens) {
    this.totalTokens = totalTokens;
    return this;
  }

  /**
   * Get totalTokens
   * minimum: 0
   * @return totalTokens
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTotalTokens() {
    return totalTokens;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalTokens(@javax.annotation.Nullable Integer totalTokens) {
    this.totalTokens = totalTokens;
  }


  public AgentSessionFleetAggregates totalToolCalls(@javax.annotation.Nullable Integer totalToolCalls) {
    this.totalToolCalls = totalToolCalls;
    return this;
  }

  /**
   * Get totalToolCalls
   * minimum: 0
   * @return totalToolCalls
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_TOOL_CALLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTotalToolCalls() {
    return totalToolCalls;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_TOOL_CALLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalToolCalls(@javax.annotation.Nullable Integer totalToolCalls) {
    this.totalToolCalls = totalToolCalls;
  }


  public AgentSessionFleetAggregates totalTurns(@javax.annotation.Nullable Integer totalTurns) {
    this.totalTurns = totalTurns;
    return this;
  }

  /**
   * Get totalTurns
   * minimum: 0
   * @return totalTurns
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_TURNS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTotalTurns() {
    return totalTurns;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_TURNS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalTurns(@javax.annotation.Nullable Integer totalTurns) {
    this.totalTurns = totalTurns;
  }


  /**
   * Return true if this AgentSessionFleetAggregates object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgentSessionFleetAggregates agentSessionFleetAggregates = (AgentSessionFleetAggregates) o;
    return Objects.equals(this.active, agentSessionFleetAggregates.active) &&
        Objects.equals(this.byState, agentSessionFleetAggregates.byState) &&
        Objects.equals(this.degradedDependencies, agentSessionFleetAggregates.degradedDependencies) &&
        Objects.equals(this.failedInvocations, agentSessionFleetAggregates.failedInvocations) &&
        Objects.equals(this.matchedExecutions, agentSessionFleetAggregates.matchedExecutions) &&
        Objects.equals(this.modelInvocations, agentSessionFleetAggregates.modelInvocations) &&
        Objects.equals(this.terminal, agentSessionFleetAggregates.terminal) &&
        Objects.equals(this.toolInvocations, agentSessionFleetAggregates.toolInvocations) &&
        Objects.equals(this.totalCostUsd, agentSessionFleetAggregates.totalCostUsd) &&
        Objects.equals(this.totalTokens, agentSessionFleetAggregates.totalTokens) &&
        Objects.equals(this.totalToolCalls, agentSessionFleetAggregates.totalToolCalls) &&
        Objects.equals(this.totalTurns, agentSessionFleetAggregates.totalTurns);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, byState, degradedDependencies, failedInvocations, matchedExecutions, modelInvocations, terminal, toolInvocations, totalCostUsd, totalTokens, totalToolCalls, totalTurns);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgentSessionFleetAggregates {\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    byState: ").append(toIndentedString(byState)).append("\n");
    sb.append("    degradedDependencies: ").append(toIndentedString(degradedDependencies)).append("\n");
    sb.append("    failedInvocations: ").append(toIndentedString(failedInvocations)).append("\n");
    sb.append("    matchedExecutions: ").append(toIndentedString(matchedExecutions)).append("\n");
    sb.append("    modelInvocations: ").append(toIndentedString(modelInvocations)).append("\n");
    sb.append("    terminal: ").append(toIndentedString(terminal)).append("\n");
    sb.append("    toolInvocations: ").append(toIndentedString(toolInvocations)).append("\n");
    sb.append("    totalCostUsd: ").append(toIndentedString(totalCostUsd)).append("\n");
    sb.append("    totalTokens: ").append(toIndentedString(totalTokens)).append("\n");
    sb.append("    totalToolCalls: ").append(toIndentedString(totalToolCalls)).append("\n");
    sb.append("    totalTurns: ").append(toIndentedString(totalTurns)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `active` to the URL query string
    if (getActive() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sactive%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getActive()))));
    }

    // add `byState` to the URL query string
    if (getByState() != null) {
      for (String _key : getByState().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sbyState%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getByState().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getByState().get(_key)))));
      }
    }

    // add `degradedDependencies` to the URL query string
    if (getDegradedDependencies() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdegradedDependencies%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDegradedDependencies()))));
    }

    // add `failedInvocations` to the URL query string
    if (getFailedInvocations() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfailedInvocations%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFailedInvocations()))));
    }

    // add `matchedExecutions` to the URL query string
    if (getMatchedExecutions() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smatchedExecutions%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMatchedExecutions()))));
    }

    // add `modelInvocations` to the URL query string
    if (getModelInvocations() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smodelInvocations%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getModelInvocations()))));
    }

    // add `terminal` to the URL query string
    if (getTerminal() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sterminal%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTerminal()))));
    }

    // add `toolInvocations` to the URL query string
    if (getToolInvocations() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stoolInvocations%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getToolInvocations()))));
    }

    // add `totalCostUsd` to the URL query string
    if (getTotalCostUsd() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalCostUsd%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalCostUsd()))));
    }

    // add `totalTokens` to the URL query string
    if (getTotalTokens() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalTokens%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalTokens()))));
    }

    // add `totalToolCalls` to the URL query string
    if (getTotalToolCalls() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalToolCalls%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalToolCalls()))));
    }

    // add `totalTurns` to the URL query string
    if (getTotalTurns() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalTurns%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalTurns()))));
    }

    return joiner.toString();
  }
}
