/*
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.amesh.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.amesh.client.model.FormField;
import io.amesh.client.model.FormSection;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.amesh.client.ApiClient;
/**
 * AppForm
 */
@JsonPropertyOrder({
  AppForm.JSON_PROPERTY_FIELDS,
  AppForm.JSON_PROPERTY_LAYOUT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class AppForm {
  public static final String JSON_PROPERTY_FIELDS = "fields";
  @javax.annotation.Nullable
  private List<FormField> fields = new ArrayList<>();

  public static final String JSON_PROPERTY_LAYOUT = "layout";
  @javax.annotation.Nullable
  private List<FormSection> layout = new ArrayList<>();

  public AppForm() {
  }

  public AppForm fields(@javax.annotation.Nullable List<FormField> fields) {
    this.fields = fields;
    return this;
  }

  public AppForm addFieldsItem(FormField fieldsItem) {
    if (this.fields == null) {
      this.fields = new ArrayList<>();
    }
    this.fields.add(fieldsItem);
    return this;
  }

  /**
   * Get fields
   * @return fields
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FIELDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<FormField> getFields() {
    return fields;
  }


  @JsonProperty(value = JSON_PROPERTY_FIELDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFields(@javax.annotation.Nullable List<FormField> fields) {
    this.fields = fields;
  }


  public AppForm layout(@javax.annotation.Nullable List<FormSection> layout) {
    this.layout = layout;
    return this;
  }

  public AppForm addLayoutItem(FormSection layoutItem) {
    if (this.layout == null) {
      this.layout = new ArrayList<>();
    }
    this.layout.add(layoutItem);
    return this;
  }

  /**
   * Get layout
   * @return layout
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAYOUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<FormSection> getLayout() {
    return layout;
  }


  @JsonProperty(value = JSON_PROPERTY_LAYOUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLayout(@javax.annotation.Nullable List<FormSection> layout) {
    this.layout = layout;
  }


  /**
   * Return true if this AppForm object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppForm appForm = (AppForm) o;
    return Objects.equals(this.fields, appForm.fields) &&
        Objects.equals(this.layout, appForm.layout);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fields, layout);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppForm {\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    layout: ").append(toIndentedString(layout)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `fields` to the URL query string
    if (getFields() != null) {
      for (int i = 0; i < getFields().size(); i++) {
        if (getFields().get(i) != null) {
          joiner.add(getFields().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sfields%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `layout` to the URL query string
    if (getLayout() != null) {
      for (int i = 0; i < getLayout().size(); i++) {
        if (getLayout().get(i) != null) {
          joiner.add(getLayout().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%slayout%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}
