/*
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.amesh.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.amesh.client.model.BackfillResourcePin;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.amesh.client.ApiClient;
/**
 * Caller attestation that a replay uses immutable source inputs and pins.
 */
@JsonPropertyOrder({
  BackfillReplaySource.JSON_PROPERTY_FROZEN_INPUT_DIGEST,
  BackfillReplaySource.JSON_PROPERTY_RESOURCE_PINS,
  BackfillReplaySource.JSON_PROPERTY_SOURCE_EXECUTION_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class BackfillReplaySource {
  public static final String JSON_PROPERTY_FROZEN_INPUT_DIGEST = "frozenInputDigest";
  @javax.annotation.Nonnull
  private String frozenInputDigest;

  public static final String JSON_PROPERTY_RESOURCE_PINS = "resourcePins";
  @javax.annotation.Nonnull
  private List<BackfillResourcePin> resourcePins = new ArrayList<>();

  public static final String JSON_PROPERTY_SOURCE_EXECUTION_ID = "sourceExecutionId";
  @javax.annotation.Nonnull
  private UUID sourceExecutionId;

  public BackfillReplaySource() {
  }

  public BackfillReplaySource frozenInputDigest(@javax.annotation.Nonnull String frozenInputDigest) {
    this.frozenInputDigest = frozenInputDigest;
    return this;
  }

  /**
   * Get frozenInputDigest
   * @return frozenInputDigest
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FROZEN_INPUT_DIGEST, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFrozenInputDigest() {
    return frozenInputDigest;
  }


  @JsonProperty(value = JSON_PROPERTY_FROZEN_INPUT_DIGEST, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFrozenInputDigest(@javax.annotation.Nonnull String frozenInputDigest) {
    this.frozenInputDigest = frozenInputDigest;
  }


  public BackfillReplaySource resourcePins(@javax.annotation.Nonnull List<BackfillResourcePin> resourcePins) {
    this.resourcePins = resourcePins;
    return this;
  }

  public BackfillReplaySource addResourcePinsItem(BackfillResourcePin resourcePinsItem) {
    if (this.resourcePins == null) {
      this.resourcePins = new ArrayList<>();
    }
    this.resourcePins.add(resourcePinsItem);
    return this;
  }

  /**
   * Get resourcePins
   * @return resourcePins
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RESOURCE_PINS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<BackfillResourcePin> getResourcePins() {
    return resourcePins;
  }


  @JsonProperty(value = JSON_PROPERTY_RESOURCE_PINS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResourcePins(@javax.annotation.Nonnull List<BackfillResourcePin> resourcePins) {
    this.resourcePins = resourcePins;
  }


  public BackfillReplaySource sourceExecutionId(@javax.annotation.Nonnull UUID sourceExecutionId) {
    this.sourceExecutionId = sourceExecutionId;
    return this;
  }

  /**
   * Get sourceExecutionId
   * @return sourceExecutionId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SOURCE_EXECUTION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getSourceExecutionId() {
    return sourceExecutionId;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE_EXECUTION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSourceExecutionId(@javax.annotation.Nonnull UUID sourceExecutionId) {
    this.sourceExecutionId = sourceExecutionId;
  }


  /**
   * Return true if this BackfillReplaySource object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BackfillReplaySource backfillReplaySource = (BackfillReplaySource) o;
    return Objects.equals(this.frozenInputDigest, backfillReplaySource.frozenInputDigest) &&
        Objects.equals(this.resourcePins, backfillReplaySource.resourcePins) &&
        Objects.equals(this.sourceExecutionId, backfillReplaySource.sourceExecutionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(frozenInputDigest, resourcePins, sourceExecutionId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BackfillReplaySource {\n");
    sb.append("    frozenInputDigest: ").append(toIndentedString(frozenInputDigest)).append("\n");
    sb.append("    resourcePins: ").append(toIndentedString(resourcePins)).append("\n");
    sb.append("    sourceExecutionId: ").append(toIndentedString(sourceExecutionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `frozenInputDigest` to the URL query string
    if (getFrozenInputDigest() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfrozenInputDigest%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFrozenInputDigest()))));
    }

    // add `resourcePins` to the URL query string
    if (getResourcePins() != null) {
      for (int i = 0; i < getResourcePins().size(); i++) {
        if (getResourcePins().get(i) != null) {
          joiner.add(getResourcePins().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sresourcePins%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `sourceExecutionId` to the URL query string
    if (getSourceExecutionId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssourceExecutionId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSourceExecutionId()))));
    }

    return joiner.toString();
  }
}
