/*
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.amesh.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.amesh.client.ApiClient;
/**
 * BlueprintProvenance
 */
@JsonPropertyOrder({
  BlueprintProvenance.JSON_PROPERTY_DIGEST,
  BlueprintProvenance.JSON_PROPERTY_LOCATION,
  BlueprintProvenance.JSON_PROPERTY_PUBLISHER,
  BlueprintProvenance.JSON_PROPERTY_REVISION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class BlueprintProvenance {
  public static final String JSON_PROPERTY_DIGEST = "digest";
  @javax.annotation.Nonnull
  private String digest;

  public static final String JSON_PROPERTY_LOCATION = "location";
  @javax.annotation.Nonnull
  private String location;

  public static final String JSON_PROPERTY_PUBLISHER = "publisher";
  @javax.annotation.Nonnull
  private String publisher;

  public static final String JSON_PROPERTY_REVISION = "revision";
  @javax.annotation.Nonnull
  private String revision;

  public BlueprintProvenance() {
  }

  public BlueprintProvenance digest(@javax.annotation.Nonnull String digest) {
    this.digest = digest;
    return this;
  }

  /**
   * Get digest
   * @return digest
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DIGEST, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDigest() {
    return digest;
  }


  @JsonProperty(value = JSON_PROPERTY_DIGEST, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDigest(@javax.annotation.Nonnull String digest) {
    this.digest = digest;
  }


  public BlueprintProvenance location(@javax.annotation.Nonnull String location) {
    this.location = location;
    return this;
  }

  /**
   * Get location
   * @return location
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLocation() {
    return location;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocation(@javax.annotation.Nonnull String location) {
    this.location = location;
  }


  public BlueprintProvenance publisher(@javax.annotation.Nonnull String publisher) {
    this.publisher = publisher;
    return this;
  }

  /**
   * Get publisher
   * @return publisher
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PUBLISHER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPublisher() {
    return publisher;
  }


  @JsonProperty(value = JSON_PROPERTY_PUBLISHER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPublisher(@javax.annotation.Nonnull String publisher) {
    this.publisher = publisher;
  }


  public BlueprintProvenance revision(@javax.annotation.Nonnull String revision) {
    this.revision = revision;
    return this;
  }

  /**
   * Get revision
   * @return revision
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REVISION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRevision() {
    return revision;
  }


  @JsonProperty(value = JSON_PROPERTY_REVISION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRevision(@javax.annotation.Nonnull String revision) {
    this.revision = revision;
  }


  /**
   * Return true if this BlueprintProvenance object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlueprintProvenance blueprintProvenance = (BlueprintProvenance) o;
    return Objects.equals(this.digest, blueprintProvenance.digest) &&
        Objects.equals(this.location, blueprintProvenance.location) &&
        Objects.equals(this.publisher, blueprintProvenance.publisher) &&
        Objects.equals(this.revision, blueprintProvenance.revision);
  }

  @Override
  public int hashCode() {
    return Objects.hash(digest, location, publisher, revision);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlueprintProvenance {\n");
    sb.append("    digest: ").append(toIndentedString(digest)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    publisher: ").append(toIndentedString(publisher)).append("\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `digest` to the URL query string
    if (getDigest() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdigest%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDigest()))));
    }

    // add `location` to the URL query string
    if (getLocation() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slocation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLocation()))));
    }

    // add `publisher` to the URL query string
    if (getPublisher() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spublisher%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPublisher()))));
    }

    // add `revision` to the URL query string
    if (getRevision() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srevision%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRevision()))));
    }

    return joiner.toString();
  }
}
