/*
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.amesh.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.amesh.client.model.OpenAIResponseInputImage;
import io.amesh.client.model.OpenAIResponseInputText;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.amesh.client.ApiClient;
import io.amesh.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
@JsonDeserialize(using=ContentAnyOfInner.ContentAnyOfInnerDeserializer.class)
@JsonSerialize(using = ContentAnyOfInner.ContentAnyOfInnerSerializer.class)
public class ContentAnyOfInner extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(ContentAnyOfInner.class.getName());

    public static class ContentAnyOfInnerSerializer extends StdSerializer<ContentAnyOfInner> {
        public ContentAnyOfInnerSerializer(Class<ContentAnyOfInner> t) {
            super(t);
        }

        public ContentAnyOfInnerSerializer() {
            this(null);
        }

        @Override
        public void serialize(ContentAnyOfInner value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class ContentAnyOfInnerDeserializer extends StdDeserializer<ContentAnyOfInner> {
        public ContentAnyOfInnerDeserializer() {
            this(ContentAnyOfInner.class);
        }

        public ContentAnyOfInnerDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public ContentAnyOfInner deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = ctxt.readTree(jp);

            Object deserialized = null;
            // deserialize OpenAIResponseInputImage
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(OpenAIResponseInputImage.class);
                ContentAnyOfInner ret = new ContentAnyOfInner();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'ContentAnyOfInner'", e);
            }

            // deserialize OpenAIResponseInputText
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(OpenAIResponseInputText.class);
                ContentAnyOfInner ret = new ContentAnyOfInner();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'ContentAnyOfInner'", e);
            }

            throw new IOException("Failed deserialization for ContentAnyOfInner: no match found");
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public ContentAnyOfInner getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "ContentAnyOfInner cannot be null");
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public ContentAnyOfInner() {
        super("anyOf", Boolean.FALSE);
    }

    public ContentAnyOfInner(OpenAIResponseInputImage o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ContentAnyOfInner(OpenAIResponseInputText o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("OpenAIResponseInputImage", OpenAIResponseInputImage.class);
        schemas.put("OpenAIResponseInputText", OpenAIResponseInputText.class);
        JSON.registerDescendants(ContentAnyOfInner.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return ContentAnyOfInner.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * OpenAIResponseInputImage, OpenAIResponseInputText
     *
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(OpenAIResponseInputImage.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(OpenAIResponseInputText.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be OpenAIResponseInputImage, OpenAIResponseInputText");
    }

    /**
     * Get the actual instance, which can be the following:
     * OpenAIResponseInputImage, OpenAIResponseInputText
     *
     * @return The actual instance (OpenAIResponseInputImage, OpenAIResponseInputText)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `OpenAIResponseInputImage`. If the actual instance is not `OpenAIResponseInputImage`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `OpenAIResponseInputImage`
     * @throws ClassCastException if the instance is not `OpenAIResponseInputImage`
     */
    public OpenAIResponseInputImage getOpenAIResponseInputImage() throws ClassCastException {
        return (OpenAIResponseInputImage)super.getActualInstance();
    }

    /**
     * Get the actual instance of `OpenAIResponseInputText`. If the actual instance is not `OpenAIResponseInputText`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `OpenAIResponseInputText`
     * @throws ClassCastException if the instance is not `OpenAIResponseInputText`
     */
    public OpenAIResponseInputText getOpenAIResponseInputText() throws ClassCastException {
        return (OpenAIResponseInputText)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    return null;
  }

}
