/*
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.amesh.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.amesh.client.model.CredentialKind;
import io.amesh.client.model.CredentialStatus;
import io.amesh.client.model.PrincipalType;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.amesh.client.ApiClient;
/**
 * CredentialMetadata
 */
@JsonPropertyOrder({
  CredentialMetadata.JSON_PROPERTY_AUDIENCE,
  CredentialMetadata.JSON_PROPERTY_CREATED_AT,
  CredentialMetadata.JSON_PROPERTY_EXPIRES_AT,
  CredentialMetadata.JSON_PROPERTY_ID,
  CredentialMetadata.JSON_PROPERTY_ISSUED_CREDENTIAL_VERSION,
  CredentialMetadata.JSON_PROPERTY_KIND,
  CredentialMetadata.JSON_PROPERTY_LAST_USED_AT,
  CredentialMetadata.JSON_PROPERTY_NAME,
  CredentialMetadata.JSON_PROPERTY_OVERLAP_EXPIRES_AT,
  CredentialMetadata.JSON_PROPERTY_PARENT_TOKEN_ID,
  CredentialMetadata.JSON_PROPERTY_PRINCIPAL_ID,
  CredentialMetadata.JSON_PROPERTY_PRINCIPAL_TYPE,
  CredentialMetadata.JSON_PROPERTY_RATE_LIMIT_PER_MINUTE,
  CredentialMetadata.JSON_PROPERTY_REVOKED_AT,
  CredentialMetadata.JSON_PROPERTY_SCOPES,
  CredentialMetadata.JSON_PROPERTY_STATUS,
  CredentialMetadata.JSON_PROPERTY_SUPERSEDED_BY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class CredentialMetadata {
  public static final String JSON_PROPERTY_AUDIENCE = "audience";
  @javax.annotation.Nullable
  private String audience = "amesh-api";

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_EXPIRES_AT = "expires_at";
  @javax.annotation.Nonnull
  private OffsetDateTime expiresAt;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private UUID id;

  public static final String JSON_PROPERTY_ISSUED_CREDENTIAL_VERSION = "issued_credential_version";
  @javax.annotation.Nullable
  private Integer issuedCredentialVersion = 1;

  public static final String JSON_PROPERTY_KIND = "kind";
  @javax.annotation.Nullable
  private CredentialKind kind;

  public static final String JSON_PROPERTY_LAST_USED_AT = "last_used_at";
  private JsonNullable<OffsetDateTime> lastUsedAt = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_OVERLAP_EXPIRES_AT = "overlap_expires_at";
  private JsonNullable<OffsetDateTime> overlapExpiresAt = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_PARENT_TOKEN_ID = "parent_token_id";
  private JsonNullable<UUID> parentTokenId = JsonNullable.<UUID>undefined();

  public static final String JSON_PROPERTY_PRINCIPAL_ID = "principal_id";
  @javax.annotation.Nonnull
  private UUID principalId;

  public static final String JSON_PROPERTY_PRINCIPAL_TYPE = "principal_type";
  @javax.annotation.Nonnull
  private PrincipalType principalType;

  public static final String JSON_PROPERTY_RATE_LIMIT_PER_MINUTE = "rate_limit_per_minute";
  @javax.annotation.Nullable
  private Integer rateLimitPerMinute = 600;

  public static final String JSON_PROPERTY_REVOKED_AT = "revoked_at";
  private JsonNullable<OffsetDateTime> revokedAt = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_SCOPES = "scopes";
  @javax.annotation.Nullable
  private List<String> scopes = new ArrayList<>(Arrays.asList("*:*"));

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private CredentialStatus status;

  public static final String JSON_PROPERTY_SUPERSEDED_BY = "superseded_by";
  private JsonNullable<UUID> supersededBy = JsonNullable.<UUID>undefined();

  public CredentialMetadata() {
  }

  public CredentialMetadata audience(@javax.annotation.Nullable String audience) {
    this.audience = audience;
    return this;
  }

  /**
   * Get audience
   * @return audience
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUDIENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAudience() {
    return audience;
  }


  @JsonProperty(value = JSON_PROPERTY_AUDIENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAudience(@javax.annotation.Nullable String audience) {
    this.audience = audience;
  }


  public CredentialMetadata createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public CredentialMetadata expiresAt(@javax.annotation.Nonnull OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EXPIRES_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRES_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpiresAt(@javax.annotation.Nonnull OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }


  public CredentialMetadata id(@javax.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable UUID id) {
    this.id = id;
  }


  public CredentialMetadata issuedCredentialVersion(@javax.annotation.Nullable Integer issuedCredentialVersion) {
    this.issuedCredentialVersion = issuedCredentialVersion;
    return this;
  }

  /**
   * Get issuedCredentialVersion
   * minimum: 1
   * @return issuedCredentialVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ISSUED_CREDENTIAL_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getIssuedCredentialVersion() {
    return issuedCredentialVersion;
  }


  @JsonProperty(value = JSON_PROPERTY_ISSUED_CREDENTIAL_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuedCredentialVersion(@javax.annotation.Nullable Integer issuedCredentialVersion) {
    this.issuedCredentialVersion = issuedCredentialVersion;
  }


  public CredentialMetadata kind(@javax.annotation.Nullable CredentialKind kind) {
    this.kind = kind;
    return this;
  }

  /**
   * Get kind
   * @return kind
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KIND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CredentialKind getKind() {
    return kind;
  }


  @JsonProperty(value = JSON_PROPERTY_KIND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKind(@javax.annotation.Nullable CredentialKind kind) {
    this.kind = kind;
  }


  public CredentialMetadata lastUsedAt(@javax.annotation.Nullable OffsetDateTime lastUsedAt) {
    this.lastUsedAt = JsonNullable.<OffsetDateTime>of(lastUsedAt);
    return this;
  }

  /**
   * Get lastUsedAt
   * @return lastUsedAt
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public OffsetDateTime getLastUsedAt() {
        return lastUsedAt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LAST_USED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getLastUsedAt_JsonNullable() {
    return lastUsedAt;
  }

  @JsonProperty(JSON_PROPERTY_LAST_USED_AT)
  public void setLastUsedAt_JsonNullable(JsonNullable<OffsetDateTime> lastUsedAt) {
    this.lastUsedAt = lastUsedAt;
  }

  public void setLastUsedAt(@javax.annotation.Nullable OffsetDateTime lastUsedAt) {
    this.lastUsedAt = JsonNullable.<OffsetDateTime>of(lastUsedAt);
  }


  public CredentialMetadata name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public CredentialMetadata overlapExpiresAt(@javax.annotation.Nullable OffsetDateTime overlapExpiresAt) {
    this.overlapExpiresAt = JsonNullable.<OffsetDateTime>of(overlapExpiresAt);
    return this;
  }

  /**
   * Get overlapExpiresAt
   * @return overlapExpiresAt
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public OffsetDateTime getOverlapExpiresAt() {
        return overlapExpiresAt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_OVERLAP_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getOverlapExpiresAt_JsonNullable() {
    return overlapExpiresAt;
  }

  @JsonProperty(JSON_PROPERTY_OVERLAP_EXPIRES_AT)
  public void setOverlapExpiresAt_JsonNullable(JsonNullable<OffsetDateTime> overlapExpiresAt) {
    this.overlapExpiresAt = overlapExpiresAt;
  }

  public void setOverlapExpiresAt(@javax.annotation.Nullable OffsetDateTime overlapExpiresAt) {
    this.overlapExpiresAt = JsonNullable.<OffsetDateTime>of(overlapExpiresAt);
  }


  public CredentialMetadata parentTokenId(@javax.annotation.Nullable UUID parentTokenId) {
    this.parentTokenId = JsonNullable.<UUID>of(parentTokenId);
    return this;
  }

  /**
   * Get parentTokenId
   * @return parentTokenId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public UUID getParentTokenId() {
        return parentTokenId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PARENT_TOKEN_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<UUID> getParentTokenId_JsonNullable() {
    return parentTokenId;
  }

  @JsonProperty(JSON_PROPERTY_PARENT_TOKEN_ID)
  public void setParentTokenId_JsonNullable(JsonNullable<UUID> parentTokenId) {
    this.parentTokenId = parentTokenId;
  }

  public void setParentTokenId(@javax.annotation.Nullable UUID parentTokenId) {
    this.parentTokenId = JsonNullable.<UUID>of(parentTokenId);
  }


  public CredentialMetadata principalId(@javax.annotation.Nonnull UUID principalId) {
    this.principalId = principalId;
    return this;
  }

  /**
   * Get principalId
   * @return principalId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PRINCIPAL_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getPrincipalId() {
    return principalId;
  }


  @JsonProperty(value = JSON_PROPERTY_PRINCIPAL_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrincipalId(@javax.annotation.Nonnull UUID principalId) {
    this.principalId = principalId;
  }


  public CredentialMetadata principalType(@javax.annotation.Nonnull PrincipalType principalType) {
    this.principalType = principalType;
    return this;
  }

  /**
   * Get principalType
   * @return principalType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PRINCIPAL_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PrincipalType getPrincipalType() {
    return principalType;
  }


  @JsonProperty(value = JSON_PROPERTY_PRINCIPAL_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrincipalType(@javax.annotation.Nonnull PrincipalType principalType) {
    this.principalType = principalType;
  }


  public CredentialMetadata rateLimitPerMinute(@javax.annotation.Nullable Integer rateLimitPerMinute) {
    this.rateLimitPerMinute = rateLimitPerMinute;
    return this;
  }

  /**
   * Get rateLimitPerMinute
   * minimum: 1
   * maximum: 1000000
   * @return rateLimitPerMinute
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RATE_LIMIT_PER_MINUTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getRateLimitPerMinute() {
    return rateLimitPerMinute;
  }


  @JsonProperty(value = JSON_PROPERTY_RATE_LIMIT_PER_MINUTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRateLimitPerMinute(@javax.annotation.Nullable Integer rateLimitPerMinute) {
    this.rateLimitPerMinute = rateLimitPerMinute;
  }


  public CredentialMetadata revokedAt(@javax.annotation.Nullable OffsetDateTime revokedAt) {
    this.revokedAt = JsonNullable.<OffsetDateTime>of(revokedAt);
    return this;
  }

  /**
   * Get revokedAt
   * @return revokedAt
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public OffsetDateTime getRevokedAt() {
        return revokedAt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_REVOKED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getRevokedAt_JsonNullable() {
    return revokedAt;
  }

  @JsonProperty(JSON_PROPERTY_REVOKED_AT)
  public void setRevokedAt_JsonNullable(JsonNullable<OffsetDateTime> revokedAt) {
    this.revokedAt = revokedAt;
  }

  public void setRevokedAt(@javax.annotation.Nullable OffsetDateTime revokedAt) {
    this.revokedAt = JsonNullable.<OffsetDateTime>of(revokedAt);
  }


  public CredentialMetadata scopes(@javax.annotation.Nullable List<String> scopes) {
    this.scopes = scopes;
    return this;
  }

  public CredentialMetadata addScopesItem(String scopesItem) {
    if (this.scopes == null) {
      this.scopes = new ArrayList<>(Arrays.asList("*:*"));
    }
    this.scopes.add(scopesItem);
    return this;
  }

  /**
   * Get scopes
   * @return scopes
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCOPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getScopes() {
    return scopes;
  }


  @JsonProperty(value = JSON_PROPERTY_SCOPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScopes(@javax.annotation.Nullable List<String> scopes) {
    this.scopes = scopes;
  }


  public CredentialMetadata status(@javax.annotation.Nullable CredentialStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CredentialStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable CredentialStatus status) {
    this.status = status;
  }


  public CredentialMetadata supersededBy(@javax.annotation.Nullable UUID supersededBy) {
    this.supersededBy = JsonNullable.<UUID>of(supersededBy);
    return this;
  }

  /**
   * Get supersededBy
   * @return supersededBy
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public UUID getSupersededBy() {
        return supersededBy.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SUPERSEDED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<UUID> getSupersededBy_JsonNullable() {
    return supersededBy;
  }

  @JsonProperty(JSON_PROPERTY_SUPERSEDED_BY)
  public void setSupersededBy_JsonNullable(JsonNullable<UUID> supersededBy) {
    this.supersededBy = supersededBy;
  }

  public void setSupersededBy(@javax.annotation.Nullable UUID supersededBy) {
    this.supersededBy = JsonNullable.<UUID>of(supersededBy);
  }


  /**
   * Return true if this CredentialMetadata object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CredentialMetadata credentialMetadata = (CredentialMetadata) o;
    return Objects.equals(this.audience, credentialMetadata.audience) &&
        Objects.equals(this.createdAt, credentialMetadata.createdAt) &&
        Objects.equals(this.expiresAt, credentialMetadata.expiresAt) &&
        Objects.equals(this.id, credentialMetadata.id) &&
        Objects.equals(this.issuedCredentialVersion, credentialMetadata.issuedCredentialVersion) &&
        Objects.equals(this.kind, credentialMetadata.kind) &&
        equalsNullable(this.lastUsedAt, credentialMetadata.lastUsedAt) &&
        Objects.equals(this.name, credentialMetadata.name) &&
        equalsNullable(this.overlapExpiresAt, credentialMetadata.overlapExpiresAt) &&
        equalsNullable(this.parentTokenId, credentialMetadata.parentTokenId) &&
        Objects.equals(this.principalId, credentialMetadata.principalId) &&
        Objects.equals(this.principalType, credentialMetadata.principalType) &&
        Objects.equals(this.rateLimitPerMinute, credentialMetadata.rateLimitPerMinute) &&
        equalsNullable(this.revokedAt, credentialMetadata.revokedAt) &&
        Objects.equals(this.scopes, credentialMetadata.scopes) &&
        Objects.equals(this.status, credentialMetadata.status) &&
        equalsNullable(this.supersededBy, credentialMetadata.supersededBy);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(audience, createdAt, expiresAt, id, issuedCredentialVersion, kind, hashCodeNullable(lastUsedAt), name, hashCodeNullable(overlapExpiresAt), hashCodeNullable(parentTokenId), principalId, principalType, rateLimitPerMinute, hashCodeNullable(revokedAt), scopes, status, hashCodeNullable(supersededBy));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CredentialMetadata {\n");
    sb.append("    audience: ").append(toIndentedString(audience)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    issuedCredentialVersion: ").append(toIndentedString(issuedCredentialVersion)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    lastUsedAt: ").append(toIndentedString(lastUsedAt)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    overlapExpiresAt: ").append(toIndentedString(overlapExpiresAt)).append("\n");
    sb.append("    parentTokenId: ").append(toIndentedString(parentTokenId)).append("\n");
    sb.append("    principalId: ").append(toIndentedString(principalId)).append("\n");
    sb.append("    principalType: ").append(toIndentedString(principalType)).append("\n");
    sb.append("    rateLimitPerMinute: ").append(toIndentedString(rateLimitPerMinute)).append("\n");
    sb.append("    revokedAt: ").append(toIndentedString(revokedAt)).append("\n");
    sb.append("    scopes: ").append(toIndentedString(scopes)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    supersededBy: ").append(toIndentedString(supersededBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `audience` to the URL query string
    if (getAudience() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saudience%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAudience()))));
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `expires_at` to the URL query string
    if (getExpiresAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexpires_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpiresAt()))));
    }

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `issued_credential_version` to the URL query string
    if (getIssuedCredentialVersion() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sissued_credential_version%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIssuedCredentialVersion()))));
    }

    // add `kind` to the URL query string
    if (getKind() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%skind%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKind()))));
    }

    // add `last_used_at` to the URL query string
    if (getLastUsedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slast_used_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastUsedAt()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `overlap_expires_at` to the URL query string
    if (getOverlapExpiresAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soverlap_expires_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOverlapExpiresAt()))));
    }

    // add `parent_token_id` to the URL query string
    if (getParentTokenId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sparent_token_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getParentTokenId()))));
    }

    // add `principal_id` to the URL query string
    if (getPrincipalId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprincipal_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrincipalId()))));
    }

    // add `principal_type` to the URL query string
    if (getPrincipalType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprincipal_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrincipalType()))));
    }

    // add `rate_limit_per_minute` to the URL query string
    if (getRateLimitPerMinute() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srate_limit_per_minute%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRateLimitPerMinute()))));
    }

    // add `revoked_at` to the URL query string
    if (getRevokedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srevoked_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRevokedAt()))));
    }

    // add `scopes` to the URL query string
    if (getScopes() != null) {
      for (int i = 0; i < getScopes().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sscopes%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getScopes().get(i)))));
      }
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `superseded_by` to the URL query string
    if (getSupersededBy() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssuperseded_by%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSupersededBy()))));
    }

    return joiner.toString();
  }
}
