/*
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.amesh.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.amesh.client.ApiClient;
/**
 * Lineage
 */
@JsonPropertyOrder({
  Lineage.JSON_PROPERTY_CONFIGURATION_DIGEST,
  Lineage.JSON_PROPERTY_INPUT_DIGEST,
  Lineage.JSON_PROPERTY_PARENT_RUN_ID,
  Lineage.JSON_PROPERTY_RUN_ID,
  Lineage.JSON_PROPERTY_SIDE,
  Lineage.JSON_PROPERTY_SPEC_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class Lineage {
  public static final String JSON_PROPERTY_CONFIGURATION_DIGEST = "configurationDigest";
  @javax.annotation.Nonnull
  private String configurationDigest;

  public static final String JSON_PROPERTY_INPUT_DIGEST = "inputDigest";
  @javax.annotation.Nonnull
  private String inputDigest;

  public static final String JSON_PROPERTY_PARENT_RUN_ID = "parentRunId";
  private JsonNullable<UUID> parentRunId = JsonNullable.<UUID>undefined();

  public static final String JSON_PROPERTY_RUN_ID = "runId";
  @javax.annotation.Nullable
  private UUID runId;

  public static final String JSON_PROPERTY_SIDE = "side";
  @javax.annotation.Nonnull
  private String side;

  public static final String JSON_PROPERTY_SPEC_ID = "specId";
  @javax.annotation.Nonnull
  private UUID specId;

  public Lineage() {
  }

  public Lineage configurationDigest(@javax.annotation.Nonnull String configurationDigest) {
    this.configurationDigest = configurationDigest;
    return this;
  }

  /**
   * Get configurationDigest
   * @return configurationDigest
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONFIGURATION_DIGEST, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getConfigurationDigest() {
    return configurationDigest;
  }


  @JsonProperty(value = JSON_PROPERTY_CONFIGURATION_DIGEST, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConfigurationDigest(@javax.annotation.Nonnull String configurationDigest) {
    this.configurationDigest = configurationDigest;
  }


  public Lineage inputDigest(@javax.annotation.Nonnull String inputDigest) {
    this.inputDigest = inputDigest;
    return this;
  }

  /**
   * Get inputDigest
   * @return inputDigest
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INPUT_DIGEST, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getInputDigest() {
    return inputDigest;
  }


  @JsonProperty(value = JSON_PROPERTY_INPUT_DIGEST, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInputDigest(@javax.annotation.Nonnull String inputDigest) {
    this.inputDigest = inputDigest;
  }


  public Lineage parentRunId(@javax.annotation.Nullable UUID parentRunId) {
    this.parentRunId = JsonNullable.<UUID>of(parentRunId);
    return this;
  }

  /**
   * Get parentRunId
   * @return parentRunId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public UUID getParentRunId() {
        return parentRunId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PARENT_RUN_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<UUID> getParentRunId_JsonNullable() {
    return parentRunId;
  }

  @JsonProperty(JSON_PROPERTY_PARENT_RUN_ID)
  public void setParentRunId_JsonNullable(JsonNullable<UUID> parentRunId) {
    this.parentRunId = parentRunId;
  }

  public void setParentRunId(@javax.annotation.Nullable UUID parentRunId) {
    this.parentRunId = JsonNullable.<UUID>of(parentRunId);
  }


  public Lineage runId(@javax.annotation.Nullable UUID runId) {
    this.runId = runId;
    return this;
  }

  /**
   * Get runId
   * @return runId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RUN_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getRunId() {
    return runId;
  }


  @JsonProperty(value = JSON_PROPERTY_RUN_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRunId(@javax.annotation.Nullable UUID runId) {
    this.runId = runId;
  }


  public Lineage side(@javax.annotation.Nonnull String side) {
    this.side = side;
    return this;
  }

  /**
   * Get side
   * @return side
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SIDE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSide() {
    return side;
  }


  @JsonProperty(value = JSON_PROPERTY_SIDE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSide(@javax.annotation.Nonnull String side) {
    this.side = side;
  }


  public Lineage specId(@javax.annotation.Nonnull UUID specId) {
    this.specId = specId;
    return this;
  }

  /**
   * Get specId
   * @return specId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SPEC_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getSpecId() {
    return specId;
  }


  @JsonProperty(value = JSON_PROPERTY_SPEC_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSpecId(@javax.annotation.Nonnull UUID specId) {
    this.specId = specId;
  }


  /**
   * Return true if this Lineage object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Lineage lineage = (Lineage) o;
    return Objects.equals(this.configurationDigest, lineage.configurationDigest) &&
        Objects.equals(this.inputDigest, lineage.inputDigest) &&
        equalsNullable(this.parentRunId, lineage.parentRunId) &&
        Objects.equals(this.runId, lineage.runId) &&
        Objects.equals(this.side, lineage.side) &&
        Objects.equals(this.specId, lineage.specId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(configurationDigest, inputDigest, hashCodeNullable(parentRunId), runId, side, specId);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Lineage {\n");
    sb.append("    configurationDigest: ").append(toIndentedString(configurationDigest)).append("\n");
    sb.append("    inputDigest: ").append(toIndentedString(inputDigest)).append("\n");
    sb.append("    parentRunId: ").append(toIndentedString(parentRunId)).append("\n");
    sb.append("    runId: ").append(toIndentedString(runId)).append("\n");
    sb.append("    side: ").append(toIndentedString(side)).append("\n");
    sb.append("    specId: ").append(toIndentedString(specId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `configurationDigest` to the URL query string
    if (getConfigurationDigest() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sconfigurationDigest%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getConfigurationDigest()))));
    }

    // add `inputDigest` to the URL query string
    if (getInputDigest() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sinputDigest%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInputDigest()))));
    }

    // add `parentRunId` to the URL query string
    if (getParentRunId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sparentRunId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getParentRunId()))));
    }

    // add `runId` to the URL query string
    if (getRunId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srunId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRunId()))));
    }

    // add `side` to the URL query string
    if (getSide() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sside%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSide()))));
    }

    // add `specId` to the URL query string
    if (getSpecId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sspecId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSpecId()))));
    }

    return joiner.toString();
  }
}
