/*
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.amesh.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.amesh.client.ApiClient;
/**
 * LoginResponse
 */
@JsonPropertyOrder({
  LoginResponse.JSON_PROPERTY_ABSOLUTE_EXPIRES_AT,
  LoginResponse.JSON_PROPERTY_DISPLAY,
  LoginResponse.JSON_PROPERTY_IDLE_EXPIRES_AT,
  LoginResponse.JSON_PROPERTY_PRINCIPAL_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class LoginResponse {
  public static final String JSON_PROPERTY_ABSOLUTE_EXPIRES_AT = "absoluteExpiresAt";
  @javax.annotation.Nonnull
  private OffsetDateTime absoluteExpiresAt;

  public static final String JSON_PROPERTY_DISPLAY = "display";
  @javax.annotation.Nonnull
  private String display;

  public static final String JSON_PROPERTY_IDLE_EXPIRES_AT = "idleExpiresAt";
  @javax.annotation.Nonnull
  private OffsetDateTime idleExpiresAt;

  public static final String JSON_PROPERTY_PRINCIPAL_ID = "principalId";
  @javax.annotation.Nonnull
  private UUID principalId;

  public LoginResponse() {
  }

  public LoginResponse absoluteExpiresAt(@javax.annotation.Nonnull OffsetDateTime absoluteExpiresAt) {
    this.absoluteExpiresAt = absoluteExpiresAt;
    return this;
  }

  /**
   * Get absoluteExpiresAt
   * @return absoluteExpiresAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ABSOLUTE_EXPIRES_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getAbsoluteExpiresAt() {
    return absoluteExpiresAt;
  }


  @JsonProperty(value = JSON_PROPERTY_ABSOLUTE_EXPIRES_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAbsoluteExpiresAt(@javax.annotation.Nonnull OffsetDateTime absoluteExpiresAt) {
    this.absoluteExpiresAt = absoluteExpiresAt;
  }


  public LoginResponse display(@javax.annotation.Nonnull String display) {
    this.display = display;
    return this;
  }

  /**
   * Get display
   * @return display
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DISPLAY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDisplay() {
    return display;
  }


  @JsonProperty(value = JSON_PROPERTY_DISPLAY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDisplay(@javax.annotation.Nonnull String display) {
    this.display = display;
  }


  public LoginResponse idleExpiresAt(@javax.annotation.Nonnull OffsetDateTime idleExpiresAt) {
    this.idleExpiresAt = idleExpiresAt;
    return this;
  }

  /**
   * Get idleExpiresAt
   * @return idleExpiresAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IDLE_EXPIRES_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getIdleExpiresAt() {
    return idleExpiresAt;
  }


  @JsonProperty(value = JSON_PROPERTY_IDLE_EXPIRES_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdleExpiresAt(@javax.annotation.Nonnull OffsetDateTime idleExpiresAt) {
    this.idleExpiresAt = idleExpiresAt;
  }


  public LoginResponse principalId(@javax.annotation.Nonnull UUID principalId) {
    this.principalId = principalId;
    return this;
  }

  /**
   * Get principalId
   * @return principalId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PRINCIPAL_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getPrincipalId() {
    return principalId;
  }


  @JsonProperty(value = JSON_PROPERTY_PRINCIPAL_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrincipalId(@javax.annotation.Nonnull UUID principalId) {
    this.principalId = principalId;
  }


  /**
   * Return true if this LoginResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginResponse loginResponse = (LoginResponse) o;
    return Objects.equals(this.absoluteExpiresAt, loginResponse.absoluteExpiresAt) &&
        Objects.equals(this.display, loginResponse.display) &&
        Objects.equals(this.idleExpiresAt, loginResponse.idleExpiresAt) &&
        Objects.equals(this.principalId, loginResponse.principalId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(absoluteExpiresAt, display, idleExpiresAt, principalId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginResponse {\n");
    sb.append("    absoluteExpiresAt: ").append(toIndentedString(absoluteExpiresAt)).append("\n");
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("    idleExpiresAt: ").append(toIndentedString(idleExpiresAt)).append("\n");
    sb.append("    principalId: ").append(toIndentedString(principalId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `absoluteExpiresAt` to the URL query string
    if (getAbsoluteExpiresAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sabsoluteExpiresAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAbsoluteExpiresAt()))));
    }

    // add `display` to the URL query string
    if (getDisplay() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdisplay%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDisplay()))));
    }

    // add `idleExpiresAt` to the URL query string
    if (getIdleExpiresAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sidleExpiresAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIdleExpiresAt()))));
    }

    // add `principalId` to the URL query string
    if (getPrincipalId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprincipalId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrincipalId()))));
    }

    return joiner.toString();
  }
}
