/*
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.amesh.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.amesh.client.model.ExecutionEvent;
import io.amesh.client.model.ExecutionSnapshot;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.amesh.client.ApiClient;
/**
 * ReduceExecutionRequest
 */
@JsonPropertyOrder({
  ReduceExecutionRequest.JSON_PROPERTY_EVENTS,
  ReduceExecutionRequest.JSON_PROPERTY_SNAPSHOT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ReduceExecutionRequest {
  public static final String JSON_PROPERTY_EVENTS = "events";
  @javax.annotation.Nonnull
  private List<ExecutionEvent> events = new ArrayList<>();

  public static final String JSON_PROPERTY_SNAPSHOT = "snapshot";
  @javax.annotation.Nonnull
  private ExecutionSnapshot snapshot;

  public ReduceExecutionRequest() {
  }

  public ReduceExecutionRequest events(@javax.annotation.Nonnull List<ExecutionEvent> events) {
    this.events = events;
    return this;
  }

  public ReduceExecutionRequest addEventsItem(ExecutionEvent eventsItem) {
    if (this.events == null) {
      this.events = new ArrayList<>();
    }
    this.events.add(eventsItem);
    return this;
  }

  /**
   * Get events
   * @return events
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EVENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<ExecutionEvent> getEvents() {
    return events;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEvents(@javax.annotation.Nonnull List<ExecutionEvent> events) {
    this.events = events;
  }


  public ReduceExecutionRequest snapshot(@javax.annotation.Nonnull ExecutionSnapshot snapshot) {
    this.snapshot = snapshot;
    return this;
  }

  /**
   * Get snapshot
   * @return snapshot
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SNAPSHOT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ExecutionSnapshot getSnapshot() {
    return snapshot;
  }


  @JsonProperty(value = JSON_PROPERTY_SNAPSHOT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSnapshot(@javax.annotation.Nonnull ExecutionSnapshot snapshot) {
    this.snapshot = snapshot;
  }


  /**
   * Return true if this ReduceExecutionRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReduceExecutionRequest reduceExecutionRequest = (ReduceExecutionRequest) o;
    return Objects.equals(this.events, reduceExecutionRequest.events) &&
        Objects.equals(this.snapshot, reduceExecutionRequest.snapshot);
  }

  @Override
  public int hashCode() {
    return Objects.hash(events, snapshot);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReduceExecutionRequest {\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("    snapshot: ").append(toIndentedString(snapshot)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `events` to the URL query string
    if (getEvents() != null) {
      for (int i = 0; i < getEvents().size(); i++) {
        if (getEvents().get(i) != null) {
          joiner.add(getEvents().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sevents%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `snapshot` to the URL query string
    if (getSnapshot() != null) {
      joiner.add(getSnapshot().toUrlQueryString(prefix + "snapshot" + suffix));
    }

    return joiner.toString();
  }
}
