/*
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.amesh.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.amesh.client.ApiClient;
/**
 * TaskExitMetadata
 */
@JsonPropertyOrder({
  TaskExitMetadata.JSON_PROPERTY_CODE,
  TaskExitMetadata.JSON_PROPERTY_DURATION_MS,
  TaskExitMetadata.JSON_PROPERTY_REASON,
  TaskExitMetadata.JSON_PROPERTY_STATUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class TaskExitMetadata {
  public static final String JSON_PROPERTY_CODE = "code";
  private JsonNullable<Integer> code = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_DURATION_MS = "durationMs";
  private JsonNullable<BigDecimal> durationMs = JsonNullable.<BigDecimal>undefined();

  public static final String JSON_PROPERTY_REASON = "reason";
  private JsonNullable<String> reason = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private String status = "SUCCESS";

  public TaskExitMetadata() {
  }

  public TaskExitMetadata code(@javax.annotation.Nullable Integer code) {
    this.code = JsonNullable.<Integer>of(code);
    return this;
  }

  /**
   * Get code
   * @return code
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Integer getCode() {
        return code.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getCode_JsonNullable() {
    return code;
  }

  @JsonProperty(JSON_PROPERTY_CODE)
  public void setCode_JsonNullable(JsonNullable<Integer> code) {
    this.code = code;
  }

  public void setCode(@javax.annotation.Nullable Integer code) {
    this.code = JsonNullable.<Integer>of(code);
  }


  public TaskExitMetadata durationMs(@javax.annotation.Nullable BigDecimal durationMs) {
    this.durationMs = JsonNullable.<BigDecimal>of(durationMs);
    return this;
  }

  /**
   * Get durationMs
   * minimum: 0.0
   * @return durationMs
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public BigDecimal getDurationMs() {
        return durationMs.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DURATION_MS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getDurationMs_JsonNullable() {
    return durationMs;
  }

  @JsonProperty(JSON_PROPERTY_DURATION_MS)
  public void setDurationMs_JsonNullable(JsonNullable<BigDecimal> durationMs) {
    this.durationMs = durationMs;
  }

  public void setDurationMs(@javax.annotation.Nullable BigDecimal durationMs) {
    this.durationMs = JsonNullable.<BigDecimal>of(durationMs);
  }


  public TaskExitMetadata reason(@javax.annotation.Nullable String reason) {
    this.reason = JsonNullable.<String>of(reason);
    return this;
  }

  /**
   * Get reason
   * @return reason
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getReason() {
        return reason.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getReason_JsonNullable() {
    return reason;
  }

  @JsonProperty(JSON_PROPERTY_REASON)
  public void setReason_JsonNullable(JsonNullable<String> reason) {
    this.reason = reason;
  }

  public void setReason(@javax.annotation.Nullable String reason) {
    this.reason = JsonNullable.<String>of(reason);
  }


  public TaskExitMetadata status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  /**
   * Return true if this TaskExitMetadata object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskExitMetadata taskExitMetadata = (TaskExitMetadata) o;
    return equalsNullable(this.code, taskExitMetadata.code) &&
        equalsNullable(this.durationMs, taskExitMetadata.durationMs) &&
        equalsNullable(this.reason, taskExitMetadata.reason) &&
        Objects.equals(this.status, taskExitMetadata.status);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(code), hashCodeNullable(durationMs), hashCodeNullable(reason), status);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskExitMetadata {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    durationMs: ").append(toIndentedString(durationMs)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `code` to the URL query string
    if (getCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCode()))));
    }

    // add `durationMs` to the URL query string
    if (getDurationMs() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdurationMs%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDurationMs()))));
    }

    // add `reason` to the URL query string
    if (getReason() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreason%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReason()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    return joiner.toString();
  }
}
