/*
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.amesh.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.amesh.client.model.Absolute;
import io.amesh.client.model.Relative;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.amesh.client.ApiClient;
/**
 * Tolerance
 */
@JsonPropertyOrder({
  Tolerance.JSON_PROPERTY_ABSOLUTE,
  Tolerance.JSON_PROPERTY_RELATIVE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class Tolerance {
  public static final String JSON_PROPERTY_ABSOLUTE = "absolute";
  @javax.annotation.Nullable
  private Absolute absolute;

  public static final String JSON_PROPERTY_RELATIVE = "relative";
  @javax.annotation.Nullable
  private Relative relative;

  public Tolerance() {
  }

  public Tolerance absolute(@javax.annotation.Nullable Absolute absolute) {
    this.absolute = absolute;
    return this;
  }

  /**
   * Get absolute
   * @return absolute
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ABSOLUTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Absolute getAbsolute() {
    return absolute;
  }


  @JsonProperty(value = JSON_PROPERTY_ABSOLUTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAbsolute(@javax.annotation.Nullable Absolute absolute) {
    this.absolute = absolute;
  }


  public Tolerance relative(@javax.annotation.Nullable Relative relative) {
    this.relative = relative;
    return this;
  }

  /**
   * Get relative
   * @return relative
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RELATIVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Relative getRelative() {
    return relative;
  }


  @JsonProperty(value = JSON_PROPERTY_RELATIVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelative(@javax.annotation.Nullable Relative relative) {
    this.relative = relative;
  }


  /**
   * Return true if this Tolerance object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tolerance tolerance = (Tolerance) o;
    return Objects.equals(this.absolute, tolerance.absolute) &&
        Objects.equals(this.relative, tolerance.relative);
  }

  @Override
  public int hashCode() {
    return Objects.hash(absolute, relative);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tolerance {\n");
    sb.append("    absolute: ").append(toIndentedString(absolute)).append("\n");
    sb.append("    relative: ").append(toIndentedString(relative)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `absolute` to the URL query string
    if (getAbsolute() != null) {
      joiner.add(getAbsolute().toUrlQueryString(prefix + "absolute" + suffix));
    }

    // add `relative` to the URL query string
    if (getRelative() != null) {
      joiner.add(getRelative().toUrlQueryString(prefix + "relative" + suffix));
    }

    return joiner.toString();
  }
}
