from __future__ import annotations

from amesh.dsl.descriptors import ResourceKind

from .common import (
    TaskRuntimeOwnership,
    TaskSpecification,
    _object_schema,
    _task,
    mesh_session_budget,
    timeout,
)


def agent_task_specifications() -> tuple[TaskSpecification, ...]:
    return (
        _task(
            "agent.llm",
            ResourceKind.TASK,
            title="LLM completion",
            description="Call an OpenAI-compatible language model endpoint.",
            category="Agents",
            property_order=(
                "provider",
                "model",
                "prompt",
                "messages",
                "parameters",
                "ceilingMode",
                "budget",
                "maxCompletionTokens",
                "dataHandling",
                "timeoutSeconds",
            ),
        ),
        _task(
            "agent.chat",
            ResourceKind.TASK,
            title="Bounded chat",
            description="Call a provider-neutral chat model with explicit budgets and data policy.",
            category="Agents",
            property_order=(
                "provider",
                "model",
                "prompt",
                "messages",
                "parameters",
                "ceilingMode",
                "budget",
                "dataHandling",
                "timeoutSeconds",
            ),
        ),
        _task(
            "agent.embedding",
            ResourceKind.TASK,
            title="Bounded embedding",
            description="Create embeddings through a provider-neutral bounded model contract.",
            category="Agents",
            property_order=(
                "provider",
                "model",
                "input",
                "ceilingMode",
                "budget",
                "dataHandling",
                "timeoutSeconds",
            ),
        ),
        _task(
            "agent.structured",
            ResourceKind.TASK,
            title="Structured model output",
            description="Require Draft 2020-12 validated structured model output.",
            category="Agents",
            property_order=(
                "provider",
                "model",
                "prompt",
                "messages",
                "outputSchema",
                "schemaName",
                "parameters",
                "ceilingMode",
                "budget",
                "dataHandling",
                "timeoutSeconds",
            ),
        ),
        _task(
            "agent.toolCall",
            ResourceKind.TASK,
            title="Bounded tool proposal",
            description="Ask a model to propose schema-validated tool calls without executing them.",
            category="Agents",
            property_order=(
                "provider",
                "model",
                "prompt",
                "messages",
                "tools",
                "toolChoice",
                "parameters",
                "ceilingMode",
                "budget",
                "dataHandling",
                "timeoutSeconds",
            ),
        ),
        _task(
            "agent.mcp",
            ResourceKind.TASK,
            title="MCP tool",
            description="Invoke a legacy endpoint or a governed, pinned MCP connection.",
            category="Agents",
            property_order=(
                "connection",
                "revision",
                "endpoint",
                "tool",
                "arguments",
                "dataHandling",
                "allowWrite",
                "approvalTask",
                "timeoutMode",
                "timeoutSeconds",
            ),
        ),
        _task(
            "agent.mesh",
            ResourceKind.TASK,
            _object_schema(
                {
                    "topology": {
                        "type": "string",
                        "enum": [
                            "SUPERVISOR",
                            "ROUTER",
                            "PEER_TO_PEER",
                            "HIERARCHICAL",
                            "SWARM",
                        ],
                    },
                    "members": {
                        "type": "array",
                        "minItems": 1,
                        "maxItems": 1_000,
                        "items": {
                            "type": "object",
                            "properties": {
                                "memberId": {"type": "string", "minLength": 1},
                                "task": {"type": "string", "minLength": 1},
                                "agent": {"type": "string", "minLength": 1},
                                "agentRevision": {"type": "integer", "minimum": 1},
                                "role": {
                                    "type": "string",
                                    "enum": ["SUPERVISOR", "ROUTER", "WORKER", "PEER"],
                                },
                                "capabilities": {
                                    "type": "array",
                                    "uniqueItems": True,
                                    "items": {"type": "string", "minLength": 1},
                                },
                                "parentMemberId": {"type": "string", "minLength": 1},
                            },
                            "required": [
                                "memberId",
                                "task",
                                "agent",
                                "agentRevision",
                                "role",
                            ],
                            "additionalProperties": False,
                        },
                    },
                    "budget": {
                        **mesh_session_budget,
                        "properties": {
                            **mesh_session_budget["properties"],
                            "maxSessions": {
                                "type": "integer",
                                "minimum": 1,
                                "maximum": 1_000,
                            },
                            "maxConcurrency": {
                                "type": "integer",
                                "minimum": 1,
                                "maximum": 1_000,
                            },
                        },
                        "required": [
                            *mesh_session_budget["required"],
                            "maxSessions",
                            "maxConcurrency",
                        ],
                    },
                    "failurePolicy": {
                        "type": "string",
                        "enum": ["FAIL_FAST", "CONTINUE_ON_ERROR", "COLLECT_ALL"],
                    },
                    "maxConcurrency": {"type": "integer", "minimum": 1, "maximum": 1_000},
                    "timeoutSeconds": timeout,
                },
                required=("topology", "members", "budget", "maxConcurrency"),
            ),
            title="Agent mesh",
            description="Run a statically bounded multi-agent topology on the durable reducer.",
            category="Agents",
            property_order=(
                "topology",
                "members",
                "budget",
                "failurePolicy",
                "maxConcurrency",
                "timeoutSeconds",
            ),
            runtime_ownership=TaskRuntimeOwnership.FLOWABLE,
        ),
        _task(
            "agent.route",
            ResourceKind.TASK,
            title="Agent route",
            description="Choose an eligible mesh member using durable, explainable signals.",
            category="Agents",
            property_order=("requiredCapabilities", "candidates", "timeoutSeconds"),
        ),
        _task(
            "agent.handoff",
            ResourceKind.TASK,
            title="Typed agent hand-off",
            description="Validate, authorize and redact context before another agent sees it.",
            category="Agents",
            property_order=(
                "source",
                "destination",
                "payload",
                "schema",
                "rationale",
                "contextKeys",
                "redactKeys",
                "requiredCapabilities",
                "policy",
                "timeoutSeconds",
            ),
        ),
        _task(
            "agent.session",
            ResourceKind.TASK,
            title="Bounded agent session",
            description=(
                "Run one durable, checkpointed agent against an exact capability envelope."
            ),
            category="Agents",
            property_order=(
                "agent",
                "agentRevision",
                "input",
                "interactionProtocol",
                "invalidOutputPolicy",
                "maxRepairAttempts",
                "requiredToolPlan",
                "businessAssertions",
                "memoryReadKeys",
                "memoryWriteKey",
                "meshId",
                "memberId",
                "meshBudget",
                "contextPolicy",
                "approvalTask",
                "dataHandling",
                "timeoutMode",
                "timeoutSeconds",
            ),
        ),
    )
