"""Provider-neutral quality contracts and differential shadow execution."""

from .agent_harness_conformance import (
    CONFORMANCE_MANIFEST_VERSION,
    CONFORMANCE_REPORT_VERSION,
    HARNESS_PORT_VERSION,
    REQUIRED_CASE_IDS,
    HarnessCaseStatus,
    HarnessConformanceCase,
    HarnessConformanceCaseResult,
    HarnessConformanceManifest,
    HarnessConformanceReport,
    HarnessConformanceSurface,
    HarnessDependencyProvenance,
    HarnessPackageProvenance,
    HarnessRuntimeVersions,
    canonical_report_json,
    dependency_license,
    manifest_digest,
    sha256_file,
)
from .api import build_differential_application_router, build_differential_router
from .cli import (
    add_differential_commands,
    differential_request,
    differential_result,
    load_differential_spec,
)
from .client import DifferentialClient
from .differential import (
    Comparator,
    ComparisonCategory,
    ComparisonDifference,
    ComparisonPolicy,
    ComparisonReport,
    ConfigurationPin,
    DifferentialService,
    DifferentialSpec,
    FixtureSource,
    Lineage,
    RunObservation,
    ShadowEffect,
    ShadowExecutionError,
    ShadowFixture,
    ShadowRun,
    ShadowRunContext,
    StructuralComparator,
    Tolerance,
    compare_runs,
)
from .durable import DurableDifferentialService
from .repository import (
    DifferentialConflictError,
    DifferentialEventRecord,
    DifferentialRecord,
    DifferentialRunBusyError,
    DifferentialRunRecord,
    DifferentialState,
    PostgresDifferentialShadowRepository,
)

__all__ = [
    "CONFORMANCE_MANIFEST_VERSION",
    "CONFORMANCE_REPORT_VERSION",
    "HARNESS_PORT_VERSION",
    "REQUIRED_CASE_IDS",
    "Comparator",
    "ComparisonCategory",
    "ComparisonDifference",
    "ComparisonPolicy",
    "ComparisonReport",
    "ConfigurationPin",
    "DifferentialClient",
    "DifferentialConflictError",
    "DifferentialEventRecord",
    "DifferentialRecord",
    "DifferentialRunBusyError",
    "DifferentialRunRecord",
    "DifferentialService",
    "DifferentialSpec",
    "DifferentialState",
    "DurableDifferentialService",
    "FixtureSource",
    "HarnessCaseStatus",
    "HarnessConformanceCase",
    "HarnessConformanceCaseResult",
    "HarnessConformanceManifest",
    "HarnessConformanceReport",
    "HarnessConformanceSurface",
    "HarnessDependencyProvenance",
    "HarnessPackageProvenance",
    "HarnessRuntimeVersions",
    "Lineage",
    "PostgresDifferentialShadowRepository",
    "RunObservation",
    "ShadowEffect",
    "ShadowExecutionError",
    "ShadowFixture",
    "ShadowRun",
    "ShadowRunContext",
    "StructuralComparator",
    "Tolerance",
    "add_differential_commands",
    "build_differential_application_router",
    "build_differential_router",
    "canonical_report_json",
    "compare_runs",
    "dependency_license",
    "differential_request",
    "differential_result",
    "load_differential_spec",
    "manifest_digest",
    "sha256_file",
]
