/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgentSessionPhase } from './AgentSessionPhase';
import {
    AgentSessionPhaseFromJSON,
    AgentSessionPhaseFromJSONTyped,
    AgentSessionPhaseToJSON,
    AgentSessionPhaseToJSONTyped,
} from './AgentSessionPhase';
import type { AgentSessionCounters } from './AgentSessionCounters';
import {
    AgentSessionCountersFromJSON,
    AgentSessionCountersFromJSONTyped,
    AgentSessionCountersToJSON,
    AgentSessionCountersToJSONTyped,
} from './AgentSessionCounters';
import type { AgentSessionState } from './AgentSessionState';
import {
    AgentSessionStateFromJSON,
    AgentSessionStateFromJSONTyped,
    AgentSessionStateToJSON,
    AgentSessionStateToJSONTyped,
} from './AgentSessionState';
import type { AgentContextReceipt } from './AgentContextReceipt';
import {
    AgentContextReceiptFromJSON,
    AgentContextReceiptFromJSONTyped,
    AgentContextReceiptToJSON,
    AgentContextReceiptToJSONTyped,
} from './AgentContextReceipt';

/**
 * Redacted session state safe for execution-scoped inspection.
 * @export
 * @interface AgentSessionSummary
 */
export interface AgentSessionSummary {
    /**
     *
     * @type {number}
     * @memberof AgentSessionSummary
     */
    attempt: number;
    /**
     *
     * @type {string}
     * @memberof AgentSessionSummary
     */
    capabilityPinId: string;
    /**
     *
     * @type {Date}
     * @memberof AgentSessionSummary
     */
    completedAt?: Date | null;
    /**
     *
     * @type {AgentContextReceipt}
     * @memberof AgentSessionSummary
     */
    contextReceipt?: AgentContextReceipt | null;
    /**
     *
     * @type {AgentSessionCounters}
     * @memberof AgentSessionSummary
     */
    counters: AgentSessionCounters;
    /**
     *
     * @type {Date}
     * @memberof AgentSessionSummary
     */
    createdAt: Date;
    /**
     *
     * @type {string}
     * @memberof AgentSessionSummary
     */
    envelopeDigest: string;
    /**
     *
     * @type {string}
     * @memberof AgentSessionSummary
     */
    error?: string | null;
    /**
     *
     * @type {string}
     * @memberof AgentSessionSummary
     */
    executionId: string;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof AgentSessionSummary
     */
    finalResult?: { [key: string]: any; } | null;
    /**
     *
     * @type {string}
     * @memberof AgentSessionSummary
     */
    namespace: string;
    /**
     *
     * @type {AgentSessionPhase}
     * @memberof AgentSessionSummary
     */
    phase: AgentSessionPhase;
    /**
     *
     * @type {string}
     * @memberof AgentSessionSummary
     */
    sessionId: string;
    /**
     *
     * @type {AgentSessionState}
     * @memberof AgentSessionSummary
     */
    state: AgentSessionState;
    /**
     *
     * @type {string}
     * @memberof AgentSessionSummary
     */
    taskRunId: string;
    /**
     *
     * @type {string}
     * @memberof AgentSessionSummary
     */
    tenantId: string;
    /**
     *
     * @type {Date}
     * @memberof AgentSessionSummary
     */
    updatedAt: Date;
    /**
     *
     * @type {number}
     * @memberof AgentSessionSummary
     */
    version: number;
}



/**
 * Check if a given object implements the AgentSessionSummary interface.
 */
export function instanceOfAgentSessionSummary(value: object): value is AgentSessionSummary {
    if (!('attempt' in value) || value['attempt'] === undefined) return false;
    if (!('capabilityPinId' in value) || value['capabilityPinId'] === undefined) return false;
    if (!('counters' in value) || value['counters'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('envelopeDigest' in value) || value['envelopeDigest'] === undefined) return false;
    if (!('executionId' in value) || value['executionId'] === undefined) return false;
    if (!('namespace' in value) || value['namespace'] === undefined) return false;
    if (!('phase' in value) || value['phase'] === undefined) return false;
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('taskRunId' in value) || value['taskRunId'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function AgentSessionSummaryFromJSON(json: any): AgentSessionSummary {
    return AgentSessionSummaryFromJSONTyped(json, false);
}

export function AgentSessionSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentSessionSummary {
    if (json == null) {
        return json;
    }
    return {

        'attempt': json['attempt'],
        'capabilityPinId': json['capabilityPinId'],
        'completedAt': json['completedAt'] === undefined ? undefined : json['completedAt'] === null ? null : (new Date(json['completedAt'])),
        'contextReceipt': json['contextReceipt'] === undefined ? undefined : json['contextReceipt'] === null ? null : AgentContextReceiptFromJSON(json['contextReceipt']),
        'counters': AgentSessionCountersFromJSON(json['counters']),
        'createdAt': (new Date(json['createdAt'])),
        'envelopeDigest': json['envelopeDigest'],
        'error': json['error'] === undefined ? undefined : json['error'] === null ? null : json['error'],
        'executionId': json['executionId'],
        'finalResult': json['finalResult'] === undefined ? undefined : json['finalResult'] === null ? null : json['finalResult'],
        'namespace': json['namespace'],
        'phase': AgentSessionPhaseFromJSON(json['phase']),
        'sessionId': json['sessionId'],
        'state': AgentSessionStateFromJSON(json['state']),
        'taskRunId': json['taskRunId'],
        'tenantId': json['tenantId'],
        'updatedAt': (new Date(json['updatedAt'])),
        'version': json['version'],
    };
}

export function AgentSessionSummaryToJSON(json: any): AgentSessionSummary {
    return AgentSessionSummaryToJSONTyped(json, false);
}

export function AgentSessionSummaryToJSONTyped(value?: AgentSessionSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'attempt': value['attempt'],
        'capabilityPinId': value['capabilityPinId'],
        'completedAt': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'contextReceipt': AgentContextReceiptToJSON(value['contextReceipt']),
        'counters': AgentSessionCountersToJSON(value['counters']),
        'createdAt': value['createdAt'].toISOString(),
        'envelopeDigest': value['envelopeDigest'],
        'error': value['error'],
        'executionId': value['executionId'],
        'finalResult': value['finalResult'],
        'namespace': value['namespace'],
        'phase': AgentSessionPhaseToJSON(value['phase']),
        'sessionId': value['sessionId'],
        'state': AgentSessionStateToJSON(value['state']),
        'taskRunId': value['taskRunId'],
        'tenantId': value['tenantId'],
        'updatedAt': value['updatedAt'].toISOString(),
        'version': value['version'],
    };
}
