/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ToolProviderKind } from './ToolProviderKind';
import {
    ToolProviderKindFromJSON,
    ToolProviderKindFromJSONTyped,
    ToolProviderKindToJSON,
    ToolProviderKindToJSONTyped,
} from './ToolProviderKind';

/**
 *
 * @export
 * @interface AgentToolRef
 */
export interface AgentToolRef {
    /**
     *
     * @type {string}
     * @memberof AgentToolRef
     */
    connectionKey?: string | null;
    /**
     *
     * @type {number}
     * @memberof AgentToolRef
     */
    connectionRevision?: number | null;
    /**
     *
     * @type {string}
     * @memberof AgentToolRef
     */
    providerKey?: string | null;
    /**
     *
     * @type {ToolProviderKind}
     * @memberof AgentToolRef
     */
    providerKind?: ToolProviderKind;
    /**
     *
     * @type {number}
     * @memberof AgentToolRef
     */
    providerRevision?: number | null;
    /**
     *
     * @type {string}
     * @memberof AgentToolRef
     */
    schemaDigest: string;
    /**
     *
     * @type {string}
     * @memberof AgentToolRef
     */
    toolName: string;
}



/**
 * Check if a given object implements the AgentToolRef interface.
 */
export function instanceOfAgentToolRef(value: object): value is AgentToolRef {
    if (!('schemaDigest' in value) || value['schemaDigest'] === undefined) return false;
    if (!('toolName' in value) || value['toolName'] === undefined) return false;
    return true;
}

export function AgentToolRefFromJSON(json: any): AgentToolRef {
    return AgentToolRefFromJSONTyped(json, false);
}

export function AgentToolRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentToolRef {
    if (json == null) {
        return json;
    }
    return {

        'connectionKey': json['connectionKey'] === undefined ? undefined : json['connectionKey'] === null ? null : json['connectionKey'],
        'connectionRevision': json['connectionRevision'] === undefined ? undefined : json['connectionRevision'] === null ? null : json['connectionRevision'],
        'providerKey': json['providerKey'] === undefined ? undefined : json['providerKey'] === null ? null : json['providerKey'],
        'providerKind': json['providerKind'] == null ? undefined : ToolProviderKindFromJSON(json['providerKind']),
        'providerRevision': json['providerRevision'] === undefined ? undefined : json['providerRevision'] === null ? null : json['providerRevision'],
        'schemaDigest': json['schemaDigest'],
        'toolName': json['toolName'],
    };
}

export function AgentToolRefToJSON(json: any): AgentToolRef {
    return AgentToolRefToJSONTyped(json, false);
}

export function AgentToolRefToJSONTyped(value?: AgentToolRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'connectionKey': value['connectionKey'],
        'connectionRevision': value['connectionRevision'],
        'providerKey': value['providerKey'],
        'providerKind': ToolProviderKindToJSON(value['providerKind']),
        'providerRevision': value['providerRevision'],
        'schemaDigest': value['schemaDigest'],
        'toolName': value['toolName'],
    };
}
