/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const AssetAccessMode = {
    Read: 'READ',
    Write: 'WRITE'
} as const;
export type AssetAccessMode = typeof AssetAccessMode[keyof typeof AssetAccessMode];


export function instanceOfAssetAccessMode(value: any): boolean {
    for (const key in AssetAccessMode) {
        if (Object.prototype.hasOwnProperty.call(AssetAccessMode, key)) {
            if (AssetAccessMode[key as keyof typeof AssetAccessMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AssetAccessModeFromJSON(json: any): AssetAccessMode {
    return AssetAccessModeFromJSONTyped(json, false);
}

export function AssetAccessModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetAccessMode {
    return json as AssetAccessMode;
}

export function AssetAccessModeToJSON(value?: AssetAccessMode | null): any {
    return value as any;
}

export function AssetAccessModeToJSONTyped(value: any, ignoreDiscriminator: boolean): AssetAccessMode {
    return value as AssetAccessMode;
}
