/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const AuditArtifactKind = {
    Audit: 'AUDIT',
    Compliance: 'COMPLIANCE'
} as const;
export type AuditArtifactKind = typeof AuditArtifactKind[keyof typeof AuditArtifactKind];


export function instanceOfAuditArtifactKind(value: any): boolean {
    for (const key in AuditArtifactKind) {
        if (Object.prototype.hasOwnProperty.call(AuditArtifactKind, key)) {
            if (AuditArtifactKind[key as keyof typeof AuditArtifactKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AuditArtifactKindFromJSON(json: any): AuditArtifactKind {
    return AuditArtifactKindFromJSONTyped(json, false);
}

export function AuditArtifactKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditArtifactKind {
    return json as AuditArtifactKind;
}

export function AuditArtifactKindToJSON(value?: AuditArtifactKind | null): any {
    return value as any;
}

export function AuditArtifactKindToJSONTyped(value: any, ignoreDiscriminator: boolean): AuditArtifactKind {
    return value as AuditArtifactKind;
}
