/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AuditLegalHold
 */
export interface AuditLegalHold {
    /**
     *
     * @type {boolean}
     * @memberof AuditLegalHold
     */
    active?: boolean;
    /**
     *
     * @type {Date}
     * @memberof AuditLegalHold
     */
    createdAt?: Date;
    /**
     *
     * @type {string}
     * @memberof AuditLegalHold
     */
    createdBy: string;
    /**
     *
     * @type {Date}
     * @memberof AuditLegalHold
     */
    endsAt?: Date | null;
    /**
     *
     * @type {string}
     * @memberof AuditLegalHold
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof AuditLegalHold
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof AuditLegalHold
     */
    reason: string;
    /**
     *
     * @type {Date}
     * @memberof AuditLegalHold
     */
    releasedAt?: Date | null;
    /**
     *
     * @type {string}
     * @memberof AuditLegalHold
     */
    releasedBy?: string | null;
    /**
     *
     * @type {Date}
     * @memberof AuditLegalHold
     */
    startsAt: Date;
    /**
     *
     * @type {string}
     * @memberof AuditLegalHold
     */
    tenantId: string;
}

/**
 * Check if a given object implements the AuditLegalHold interface.
 */
export function instanceOfAuditLegalHold(value: object): value is AuditLegalHold {
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('startsAt' in value) || value['startsAt'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function AuditLegalHoldFromJSON(json: any): AuditLegalHold {
    return AuditLegalHoldFromJSONTyped(json, false);
}

export function AuditLegalHoldFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditLegalHold {
    if (json == null) {
        return json;
    }
    return {

        'active': json['active'] == null ? undefined : json['active'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'createdBy': json['createdBy'],
        'endsAt': json['endsAt'] === undefined ? undefined : json['endsAt'] === null ? null : (new Date(json['endsAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'reason': json['reason'],
        'releasedAt': json['releasedAt'] === undefined ? undefined : json['releasedAt'] === null ? null : (new Date(json['releasedAt'])),
        'releasedBy': json['releasedBy'] === undefined ? undefined : json['releasedBy'] === null ? null : json['releasedBy'],
        'startsAt': (new Date(json['startsAt'])),
        'tenantId': json['tenantId'],
    };
}

export function AuditLegalHoldToJSON(json: any): AuditLegalHold {
    return AuditLegalHoldToJSONTyped(json, false);
}

export function AuditLegalHoldToJSONTyped(value?: AuditLegalHold | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'active': value['active'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'createdBy': value['createdBy'],
        'endsAt': value['endsAt'] == null ? value['endsAt'] : value['endsAt'].toISOString(),
        'id': value['id'],
        'name': value['name'],
        'reason': value['reason'],
        'releasedAt': value['releasedAt'] == null ? value['releasedAt'] : value['releasedAt'].toISOString(),
        'releasedBy': value['releasedBy'],
        'startsAt': value['startsAt'].toISOString(),
        'tenantId': value['tenantId'],
    };
}
