/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlueprintProvenance } from './BlueprintProvenance';
import {
    BlueprintProvenanceFromJSON,
    BlueprintProvenanceFromJSONTyped,
    BlueprintProvenanceToJSON,
    BlueprintProvenanceToJSONTyped,
} from './BlueprintProvenance';
import type { BlueprintCatalogSource } from './BlueprintCatalogSource';
import {
    BlueprintCatalogSourceFromJSON,
    BlueprintCatalogSourceFromJSONTyped,
    BlueprintCatalogSourceToJSON,
    BlueprintCatalogSourceToJSONTyped,
} from './BlueprintCatalogSource';
import type { BlueprintParameter } from './BlueprintParameter';
import {
    BlueprintParameterFromJSON,
    BlueprintParameterFromJSONTyped,
    BlueprintParameterToJSON,
    BlueprintParameterToJSONTyped,
} from './BlueprintParameter';

/**
 *
 * @export
 * @interface BlueprintSummary
 */
export interface BlueprintSummary {
    /**
     *
     * @type {string}
     * @memberof BlueprintSummary
     */
    blueprintId: string;
    /**
     *
     * @type {string}
     * @memberof BlueprintSummary
     */
    documentation: string;
    /**
     *
     * @type {string}
     * @memberof BlueprintSummary
     */
    license: string;
    /**
     *
     * @type {boolean}
     * @memberof BlueprintSummary
     */
    localOnly: boolean;
    /**
     *
     * @type {Array<BlueprintParameter>}
     * @memberof BlueprintSummary
     */
    parameters: Array<BlueprintParameter>;
    /**
     *
     * @type {BlueprintProvenance}
     * @memberof BlueprintSummary
     */
    provenance: BlueprintProvenance;
    /**
     *
     * @type {BlueprintCatalogSource}
     * @memberof BlueprintSummary
     */
    source: BlueprintCatalogSource;
    /**
     *
     * @type {string}
     * @memberof BlueprintSummary
     */
    summary: string;
    /**
     *
     * @type {Array<string>}
     * @memberof BlueprintSummary
     */
    tags: Array<string>;
    /**
     *
     * @type {string}
     * @memberof BlueprintSummary
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof BlueprintSummary
     */
    version: string;
}



/**
 * Check if a given object implements the BlueprintSummary interface.
 */
export function instanceOfBlueprintSummary(value: object): value is BlueprintSummary {
    if (!('blueprintId' in value) || value['blueprintId'] === undefined) return false;
    if (!('documentation' in value) || value['documentation'] === undefined) return false;
    if (!('license' in value) || value['license'] === undefined) return false;
    if (!('localOnly' in value) || value['localOnly'] === undefined) return false;
    if (!('parameters' in value) || value['parameters'] === undefined) return false;
    if (!('provenance' in value) || value['provenance'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function BlueprintSummaryFromJSON(json: any): BlueprintSummary {
    return BlueprintSummaryFromJSONTyped(json, false);
}

export function BlueprintSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlueprintSummary {
    if (json == null) {
        return json;
    }
    return {

        'blueprintId': json['blueprintId'],
        'documentation': json['documentation'],
        'license': json['license'],
        'localOnly': json['localOnly'],
        'parameters': ((json['parameters'] as Array<any>).map(BlueprintParameterFromJSON)),
        'provenance': BlueprintProvenanceFromJSON(json['provenance']),
        'source': BlueprintCatalogSourceFromJSON(json['source']),
        'summary': json['summary'],
        'tags': json['tags'],
        'title': json['title'],
        'version': json['version'],
    };
}

export function BlueprintSummaryToJSON(json: any): BlueprintSummary {
    return BlueprintSummaryToJSONTyped(json, false);
}

export function BlueprintSummaryToJSONTyped(value?: BlueprintSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'blueprintId': value['blueprintId'],
        'documentation': value['documentation'],
        'license': value['license'],
        'localOnly': value['localOnly'],
        'parameters': ((value['parameters'] as Array<any>).map(BlueprintParameterToJSON)),
        'provenance': BlueprintProvenanceToJSON(value['provenance']),
        'source': BlueprintCatalogSourceToJSON(value['source']),
        'summary': value['summary'],
        'tags': value['tags'],
        'title': value['title'],
        'version': value['version'],
    };
}
