/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const CapabilitySourceAccessStatus = {
    Allowed: 'allowed',
    Denied: 'denied',
    Unavailable: 'unavailable'
} as const;
export type CapabilitySourceAccessStatus = typeof CapabilitySourceAccessStatus[keyof typeof CapabilitySourceAccessStatus];


export function instanceOfCapabilitySourceAccessStatus(value: any): boolean {
    for (const key in CapabilitySourceAccessStatus) {
        if (Object.prototype.hasOwnProperty.call(CapabilitySourceAccessStatus, key)) {
            if (CapabilitySourceAccessStatus[key as keyof typeof CapabilitySourceAccessStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CapabilitySourceAccessStatusFromJSON(json: any): CapabilitySourceAccessStatus {
    return CapabilitySourceAccessStatusFromJSONTyped(json, false);
}

export function CapabilitySourceAccessStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CapabilitySourceAccessStatus {
    return json as CapabilitySourceAccessStatus;
}

export function CapabilitySourceAccessStatusToJSON(value?: CapabilitySourceAccessStatus | null): any {
    return value as any;
}

export function CapabilitySourceAccessStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): CapabilitySourceAccessStatus {
    return value as CapabilitySourceAccessStatus;
}
