/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ComplianceEvidenceCategory } from './ComplianceEvidenceCategory';
import {
    ComplianceEvidenceCategoryFromJSON,
    ComplianceEvidenceCategoryFromJSONTyped,
    ComplianceEvidenceCategoryToJSON,
    ComplianceEvidenceCategoryToJSONTyped,
} from './ComplianceEvidenceCategory';

/**
 *
 * @export
 * @interface ComplianceEvidenceRecord
 */
export interface ComplianceEvidenceRecord {
    /**
     *
     * @type {ComplianceEvidenceCategory}
     * @memberof ComplianceEvidenceRecord
     */
    category: ComplianceEvidenceCategory;
    /**
     *
     * @type {string}
     * @memberof ComplianceEvidenceRecord
     */
    checksumSha256: string;
    /**
     *
     * @type {Date}
     * @memberof ComplianceEvidenceRecord
     */
    createdAt?: Date;
    /**
     *
     * @type {string}
     * @memberof ComplianceEvidenceRecord
     */
    createdBy: string;
    /**
     *
     * @type {string}
     * @memberof ComplianceEvidenceRecord
     */
    id?: string;
    /**
     *
     * @type {Date}
     * @memberof ComplianceEvidenceRecord
     */
    occurredAt: Date;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof ComplianceEvidenceRecord
     */
    payload?: { [key: string]: any; };
    /**
     *
     * @type {string}
     * @memberof ComplianceEvidenceRecord
     */
    source: string;
    /**
     *
     * @type {string}
     * @memberof ComplianceEvidenceRecord
     */
    tenantId: string;
    /**
     *
     * @type {string}
     * @memberof ComplianceEvidenceRecord
     */
    title: string;
}



/**
 * Check if a given object implements the ComplianceEvidenceRecord interface.
 */
export function instanceOfComplianceEvidenceRecord(value: object): value is ComplianceEvidenceRecord {
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('checksumSha256' in value) || value['checksumSha256'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('occurredAt' in value) || value['occurredAt'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ComplianceEvidenceRecordFromJSON(json: any): ComplianceEvidenceRecord {
    return ComplianceEvidenceRecordFromJSONTyped(json, false);
}

export function ComplianceEvidenceRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplianceEvidenceRecord {
    if (json == null) {
        return json;
    }
    return {

        'category': ComplianceEvidenceCategoryFromJSON(json['category']),
        'checksumSha256': json['checksumSha256'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'createdBy': json['createdBy'],
        'id': json['id'] == null ? undefined : json['id'],
        'occurredAt': (new Date(json['occurredAt'])),
        'payload': json['payload'] == null ? undefined : json['payload'],
        'source': json['source'],
        'tenantId': json['tenantId'],
        'title': json['title'],
    };
}

export function ComplianceEvidenceRecordToJSON(json: any): ComplianceEvidenceRecord {
    return ComplianceEvidenceRecordToJSONTyped(json, false);
}

export function ComplianceEvidenceRecordToJSONTyped(value?: ComplianceEvidenceRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'category': ComplianceEvidenceCategoryToJSON(value['category']),
        'checksumSha256': value['checksumSha256'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'createdBy': value['createdBy'],
        'id': value['id'],
        'occurredAt': value['occurredAt'].toISOString(),
        'payload': value['payload'],
        'source': value['source'],
        'tenantId': value['tenantId'],
        'title': value['title'],
    };
}
