/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const FeatureFlagScope = {
    Instance: 'INSTANCE',
    Tenant: 'TENANT',
    Namespace: 'NAMESPACE'
} as const;
export type FeatureFlagScope = typeof FeatureFlagScope[keyof typeof FeatureFlagScope];


export function instanceOfFeatureFlagScope(value: any): boolean {
    for (const key in FeatureFlagScope) {
        if (Object.prototype.hasOwnProperty.call(FeatureFlagScope, key)) {
            if (FeatureFlagScope[key as keyof typeof FeatureFlagScope] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FeatureFlagScopeFromJSON(json: any): FeatureFlagScope {
    return FeatureFlagScopeFromJSONTyped(json, false);
}

export function FeatureFlagScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureFlagScope {
    return json as FeatureFlagScope;
}

export function FeatureFlagScopeToJSON(value?: FeatureFlagScope | null): any {
    return value as any;
}

export function FeatureFlagScopeToJSONTyped(value: any, ignoreDiscriminator: boolean): FeatureFlagScope {
    return value as FeatureFlagScope;
}
