/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FormSection
 */
export interface FormSection {
    /**
     *
     * @type {number}
     * @memberof FormSection
     */
    columns?: number;
    /**
     *
     * @type {Array<string>}
     * @memberof FormSection
     */
    fields: Array<string>;
    /**
     *
     * @type {string}
     * @memberof FormSection
     */
    helpText?: string;
    /**
     *
     * @type {string}
     * @memberof FormSection
     */
    title: string;
}

/**
 * Check if a given object implements the FormSection interface.
 */
export function instanceOfFormSection(value: object): value is FormSection {
    if (!('fields' in value) || value['fields'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function FormSectionFromJSON(json: any): FormSection {
    return FormSectionFromJSONTyped(json, false);
}

export function FormSectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormSection {
    if (json == null) {
        return json;
    }
    return {

        'columns': json['columns'] == null ? undefined : json['columns'],
        'fields': json['fields'],
        'helpText': json['helpText'] == null ? undefined : json['helpText'],
        'title': json['title'],
    };
}

export function FormSectionToJSON(json: any): FormSection {
    return FormSectionToJSONTyped(json, false);
}

export function FormSectionToJSONTyped(value?: FormSection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'columns': value['columns'],
        'fields': value['fields'],
        'helpText': value['helpText'],
        'title': value['title'],
    };
}
