/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface McpConnectionTestRequest
 */
export interface McpConnectionTestRequest {
    /**
     *
     * @type {number}
     * @memberof McpConnectionTestRequest
     */
    revision: number;
    /**
     *
     * @type {number}
     * @memberof McpConnectionTestRequest
     */
    timeoutSeconds?: number;
}

/**
 * Check if a given object implements the McpConnectionTestRequest interface.
 */
export function instanceOfMcpConnectionTestRequest(value: object): value is McpConnectionTestRequest {
    if (!('revision' in value) || value['revision'] === undefined) return false;
    return true;
}

export function McpConnectionTestRequestFromJSON(json: any): McpConnectionTestRequest {
    return McpConnectionTestRequestFromJSONTyped(json, false);
}

export function McpConnectionTestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): McpConnectionTestRequest {
    if (json == null) {
        return json;
    }
    return {

        'revision': json['revision'],
        'timeoutSeconds': json['timeoutSeconds'] == null ? undefined : json['timeoutSeconds'],
    };
}

export function McpConnectionTestRequestToJSON(json: any): McpConnectionTestRequest {
    return McpConnectionTestRequestToJSONTyped(json, false);
}

export function McpConnectionTestRequestToJSONTyped(value?: McpConnectionTestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'revision': value['revision'],
        'timeoutSeconds': value['timeoutSeconds'],
    };
}
