/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckPolicySource } from './CheckPolicySource';
import {
    CheckPolicySourceFromJSON,
    CheckPolicySourceFromJSONTyped,
    CheckPolicySourceToJSON,
    CheckPolicySourceToJSONTyped,
} from './CheckPolicySource';
import type { CheckDefinition } from './CheckDefinition';
import {
    CheckDefinitionFromJSON,
    CheckDefinitionFromJSONTyped,
    CheckDefinitionToJSON,
    CheckDefinitionToJSONTyped,
} from './CheckDefinition';

/**
 *
 * @export
 * @interface NamespaceCheckPolicy
 */
export interface NamespaceCheckPolicy {
    /**
     *
     * @type {Date}
     * @memberof NamespaceCheckPolicy
     */
    createdAt: Date;
    /**
     *
     * @type {CheckDefinition}
     * @memberof NamespaceCheckPolicy
     */
    definition: CheckDefinition;
    /**
     *
     * @type {boolean}
     * @memberof NamespaceCheckPolicy
     */
    enabled: boolean;
    /**
     *
     * @type {string}
     * @memberof NamespaceCheckPolicy
     */
    namespace: string;
    /**
     *
     * @type {string}
     * @memberof NamespaceCheckPolicy
     */
    policyId: string;
    /**
     *
     * @type {string}
     * @memberof NamespaceCheckPolicy
     */
    policyKey: string;
    /**
     *
     * @type {CheckPolicySource}
     * @memberof NamespaceCheckPolicy
     */
    source: CheckPolicySource;
    /**
     *
     * @type {string}
     * @memberof NamespaceCheckPolicy
     */
    taskType?: string | null;
    /**
     *
     * @type {string}
     * @memberof NamespaceCheckPolicy
     */
    tenantId: string;
    /**
     *
     * @type {Date}
     * @memberof NamespaceCheckPolicy
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the NamespaceCheckPolicy interface.
 */
export function instanceOfNamespaceCheckPolicy(value: object): value is NamespaceCheckPolicy {
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('definition' in value) || value['definition'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('namespace' in value) || value['namespace'] === undefined) return false;
    if ((!('policyId' in (value as Record<string, any>)) && !('policy_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['policyId'] === undefined && (value as Record<string, any>)['policy_id'] === undefined)) return false;
    if ((!('policyKey' in (value as Record<string, any>)) && !('policy_key' in (value as Record<string, any>))) || ((value as Record<string, any>)['policyKey'] === undefined && (value as Record<string, any>)['policy_key'] === undefined)) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if ((!('tenantId' in (value as Record<string, any>)) && !('tenant_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['tenantId'] === undefined && (value as Record<string, any>)['tenant_id'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function NamespaceCheckPolicyFromJSON(json: any): NamespaceCheckPolicy {
    return NamespaceCheckPolicyFromJSONTyped(json, false);
}

export function NamespaceCheckPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): NamespaceCheckPolicy {
    if (json == null) {
        return json;
    }
    return {

        'createdAt': (new Date(json['created_at'])),
        'definition': CheckDefinitionFromJSON(json['definition']),
        'enabled': json['enabled'],
        'namespace': json['namespace'],
        'policyId': json['policy_id'],
        'policyKey': json['policy_key'],
        'source': CheckPolicySourceFromJSON(json['source']),
        'taskType': json['task_type'] === undefined ? undefined : json['task_type'] === null ? null : json['task_type'],
        'tenantId': json['tenant_id'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function NamespaceCheckPolicyToJSON(json: any): NamespaceCheckPolicy {
    return NamespaceCheckPolicyToJSONTyped(json, false);
}

export function NamespaceCheckPolicyToJSONTyped(value?: NamespaceCheckPolicy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'created_at': value['createdAt'].toISOString(),
        'definition': CheckDefinitionToJSON(value['definition']),
        'enabled': value['enabled'],
        'namespace': value['namespace'],
        'policy_id': value['policyId'],
        'policy_key': value['policyKey'],
        'source': CheckPolicySourceToJSON(value['source']),
        'task_type': value['taskType'],
        'tenant_id': value['tenantId'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}
