/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface NondeterministicOperation
 */
export interface NondeterministicOperation {
    /**
     *
     * @type {boolean}
     * @memberof NondeterministicOperation
     */
    deterministicOutput?: boolean;
    /**
     *
     * @type {string}
     * @memberof NondeterministicOperation
     */
    replayRequirement?: string;
    /**
     *
     * @type {string}
     * @memberof NondeterministicOperation
     */
    taskId: string;
    /**
     *
     * @type {string}
     * @memberof NondeterministicOperation
     */
    taskType: string;
}

/**
 * Check if a given object implements the NondeterministicOperation interface.
 */
export function instanceOfNondeterministicOperation(value: object): value is NondeterministicOperation {
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('taskType' in value) || value['taskType'] === undefined) return false;
    return true;
}

export function NondeterministicOperationFromJSON(json: any): NondeterministicOperation {
    return NondeterministicOperationFromJSONTyped(json, false);
}

export function NondeterministicOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): NondeterministicOperation {
    if (json == null) {
        return json;
    }
    return {

        'deterministicOutput': json['deterministicOutput'] == null ? undefined : json['deterministicOutput'],
        'replayRequirement': json['replayRequirement'] == null ? undefined : json['replayRequirement'],
        'taskId': json['taskId'],
        'taskType': json['taskType'],
    };
}

export function NondeterministicOperationToJSON(json: any): NondeterministicOperation {
    return NondeterministicOperationToJSONTyped(json, false);
}

export function NondeterministicOperationToJSONTyped(value?: NondeterministicOperation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'deterministicOutput': value['deterministicOutput'],
        'replayRequirement': value['replayRequirement'],
        'taskId': value['taskId'],
        'taskType': value['taskType'],
    };
}
