/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PluginDocumentation } from './PluginDocumentation';
import {
    PluginDocumentationFromJSON,
    PluginDocumentationFromJSONTyped,
    PluginDocumentationToJSON,
    PluginDocumentationToJSONTyped,
} from './PluginDocumentation';
import type { InputModality } from './InputModality';
import {
    InputModalityFromJSON,
    InputModalityFromJSONTyped,
    InputModalityToJSON,
    InputModalityToJSONTyped,
} from './InputModality';
import type { ExtensionType } from './ExtensionType';
import {
    ExtensionTypeFromJSON,
    ExtensionTypeFromJSONTyped,
    ExtensionTypeToJSON,
    ExtensionTypeToJSONTyped,
} from './ExtensionType';
import type { PluginTransport } from './PluginTransport';
import {
    PluginTransportFromJSON,
    PluginTransportFromJSONTyped,
    PluginTransportToJSON,
    PluginTransportToJSONTyped,
} from './PluginTransport';

/**
 *
 * @export
 * @interface PluginEntryPoint
 */
export interface PluginEntryPoint {
    /**
     *
     * @type {PluginEntryPointApiVersionEnum}
     * @memberof PluginEntryPoint
     */
    apiVersion?: PluginEntryPointApiVersionEnum;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof PluginEntryPoint
     */
    configurationSchema: { [key: string]: any; };
    /**
     *
     * @type {PluginDocumentation}
     * @memberof PluginEntryPoint
     */
    documentation: PluginDocumentation;
    /**
     *
     * @type {Set<InputModality>}
     * @memberof PluginEntryPoint
     */
    inputModalities?: Set<InputModality>;
    /**
     *
     * @type {string}
     * @memberof PluginEntryPoint
     */
    name: string;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof PluginEntryPoint
     */
    outputSchema?: { [key: string]: any; } | null;
    /**
     *
     * @type {string}
     * @memberof PluginEntryPoint
     */
    resourceType?: string | null;
    /**
     *
     * @type {string}
     * @memberof PluginEntryPoint
     */
    target: string;
    /**
     *
     * @type {PluginTransport}
     * @memberof PluginEntryPoint
     */
    transport: PluginTransport;
    /**
     *
     * @type {ExtensionType}
     * @memberof PluginEntryPoint
     */
    type: ExtensionType;
}


/**
 * @export
 */
export const PluginEntryPointApiVersionEnum = {
    AmeshExtensionV1: 'amesh.extension/v1'
} as const;
export type PluginEntryPointApiVersionEnum = typeof PluginEntryPointApiVersionEnum[keyof typeof PluginEntryPointApiVersionEnum];


/**
 * Check if a given object implements the PluginEntryPoint interface.
 */
export function instanceOfPluginEntryPoint(value: object): value is PluginEntryPoint {
    if (!('configurationSchema' in value) || value['configurationSchema'] === undefined) return false;
    if (!('documentation' in value) || value['documentation'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('target' in value) || value['target'] === undefined) return false;
    if (!('transport' in value) || value['transport'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function PluginEntryPointFromJSON(json: any): PluginEntryPoint {
    return PluginEntryPointFromJSONTyped(json, false);
}

export function PluginEntryPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginEntryPoint {
    if (json == null) {
        return json;
    }
    return {

        'apiVersion': json['apiVersion'] == null ? undefined : json['apiVersion'],
        'configurationSchema': json['configurationSchema'],
        'documentation': PluginDocumentationFromJSON(json['documentation']),
        'inputModalities': json['inputModalities'] == null ? undefined : (new Set((json['inputModalities'] as Array<any>).map(InputModalityFromJSON))),
        'name': json['name'],
        'outputSchema': json['outputSchema'] === undefined ? undefined : json['outputSchema'] === null ? null : json['outputSchema'],
        'resourceType': json['resourceType'] === undefined ? undefined : json['resourceType'] === null ? null : json['resourceType'],
        'target': json['target'],
        'transport': PluginTransportFromJSON(json['transport']),
        'type': ExtensionTypeFromJSON(json['type']),
    };
}

export function PluginEntryPointToJSON(json: any): PluginEntryPoint {
    return PluginEntryPointToJSONTyped(json, false);
}

export function PluginEntryPointToJSONTyped(value?: PluginEntryPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'apiVersion': value['apiVersion'],
        'configurationSchema': value['configurationSchema'],
        'documentation': PluginDocumentationToJSON(value['documentation']),
        'inputModalities': value['inputModalities'] == null ? undefined : (Array.from(value['inputModalities'] as Set<any>).map(InputModalityToJSON)),
        'name': value['name'],
        'outputSchema': value['outputSchema'],
        'resourceType': value['resourceType'],
        'target': value['target'],
        'transport': PluginTransportToJSON(value['transport']),
        'type': ExtensionTypeToJSON(value['type']),
    };
}
