/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PluginPackageRecord } from './PluginPackageRecord';
import {
    PluginPackageRecordFromJSON,
    PluginPackageRecordFromJSONTyped,
    PluginPackageRecordToJSON,
    PluginPackageRecordToJSONTyped,
} from './PluginPackageRecord';

/**
 *
 * @export
 * @interface PluginCatalogSnapshot
 */
export interface PluginCatalogSnapshot {
    /**
     *
     * @type {string}
     * @memberof PluginCatalogSnapshot
     */
    catalogDigest: string;
    /**
     *
     * @type {Date}
     * @memberof PluginCatalogSnapshot
     */
    generatedAt: Date;
    /**
     *
     * @type {number}
     * @memberof PluginCatalogSnapshot
     */
    generation: number;
    /**
     *
     * @type {Array<PluginPackageRecord>}
     * @memberof PluginCatalogSnapshot
     */
    packages: Array<PluginPackageRecord>;
    /**
     *
     * @type {PluginCatalogSnapshotSchemaVersionEnum}
     * @memberof PluginCatalogSnapshot
     */
    schemaVersion?: PluginCatalogSnapshotSchemaVersionEnum;
}


/**
 * @export
 */
export const PluginCatalogSnapshotSchemaVersionEnum = {
    AmeshPluginCatalogV1: 'amesh.plugin-catalog/v1'
} as const;
export type PluginCatalogSnapshotSchemaVersionEnum = typeof PluginCatalogSnapshotSchemaVersionEnum[keyof typeof PluginCatalogSnapshotSchemaVersionEnum];


/**
 * Check if a given object implements the PluginCatalogSnapshot interface.
 */
export function instanceOfPluginCatalogSnapshot(value: object): value is PluginCatalogSnapshot {
    if (!('catalogDigest' in value) || value['catalogDigest'] === undefined) return false;
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('generation' in value) || value['generation'] === undefined) return false;
    if (!('packages' in value) || value['packages'] === undefined) return false;
    return true;
}

export function PluginCatalogSnapshotFromJSON(json: any): PluginCatalogSnapshot {
    return PluginCatalogSnapshotFromJSONTyped(json, false);
}

export function PluginCatalogSnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginCatalogSnapshot {
    if (json == null) {
        return json;
    }
    return {

        'catalogDigest': json['catalogDigest'],
        'generatedAt': (new Date(json['generatedAt'])),
        'generation': json['generation'],
        'packages': ((json['packages'] as Array<any>).map(PluginPackageRecordFromJSON)),
        'schemaVersion': json['schemaVersion'] == null ? undefined : json['schemaVersion'],
    };
}

export function PluginCatalogSnapshotToJSON(json: any): PluginCatalogSnapshot {
    return PluginCatalogSnapshotToJSONTyped(json, false);
}

export function PluginCatalogSnapshotToJSONTyped(value?: PluginCatalogSnapshot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'catalogDigest': value['catalogDigest'],
        'generatedAt': value['generatedAt'].toISOString(),
        'generation': value['generation'],
        'packages': ((value['packages'] as Array<any>).map(PluginPackageRecordToJSON)),
        'schemaVersion': value['schemaVersion'],
    };
}
