/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const PluginTransport = {
    Stdio: 'stdio',
    Grpc: 'grpc',
    Http: 'http'
} as const;
export type PluginTransport = typeof PluginTransport[keyof typeof PluginTransport];


export function instanceOfPluginTransport(value: any): boolean {
    for (const key in PluginTransport) {
        if (Object.prototype.hasOwnProperty.call(PluginTransport, key)) {
            if (PluginTransport[key as keyof typeof PluginTransport] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PluginTransportFromJSON(json: any): PluginTransport {
    return PluginTransportFromJSONTyped(json, false);
}

export function PluginTransportFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginTransport {
    return json as PluginTransport;
}

export function PluginTransportToJSON(value?: PluginTransport | null): any {
    return value as any;
}

export function PluginTransportToJSONTyped(value: any, ignoreDiscriminator: boolean): PluginTransport {
    return value as PluginTransport;
}
