/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PluginPolicyScope } from './PluginPolicyScope';
import {
    PluginPolicyScopeFromJSON,
    PluginPolicyScopeFromJSONTyped,
    PluginPolicyScopeToJSON,
    PluginPolicyScopeToJSONTyped,
} from './PluginPolicyScope';

/**
 *
 * @export
 * @interface PluginQuarantineCreate
 */
export interface PluginQuarantineCreate {
    /**
     *
     * @type {string}
     * @memberof PluginQuarantineCreate
     */
    namespace?: string | null;
    /**
     *
     * @type {string}
     * @memberof PluginQuarantineCreate
     */
    _package: string;
    /**
     *
     * @type {string}
     * @memberof PluginQuarantineCreate
     */
    reason: string;
    /**
     *
     * @type {PluginPolicyScope}
     * @memberof PluginQuarantineCreate
     */
    scope?: PluginPolicyScope;
    /**
     *
     * @type {string}
     * @memberof PluginQuarantineCreate
     */
    version: string;
}



/**
 * Check if a given object implements the PluginQuarantineCreate interface.
 */
export function instanceOfPluginQuarantineCreate(value: object): value is PluginQuarantineCreate {
    if ((!('_package' in (value as Record<string, any>)) && !('package' in (value as Record<string, any>))) || ((value as Record<string, any>)['_package'] === undefined && (value as Record<string, any>)['package'] === undefined)) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function PluginQuarantineCreateFromJSON(json: any): PluginQuarantineCreate {
    return PluginQuarantineCreateFromJSONTyped(json, false);
}

export function PluginQuarantineCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginQuarantineCreate {
    if (json == null) {
        return json;
    }
    return {

        'namespace': json['namespace'] === undefined ? undefined : json['namespace'] === null ? null : json['namespace'],
        '_package': json['package'],
        'reason': json['reason'],
        'scope': json['scope'] == null ? undefined : PluginPolicyScopeFromJSON(json['scope']),
        'version': json['version'],
    };
}

export function PluginQuarantineCreateToJSON(json: any): PluginQuarantineCreate {
    return PluginQuarantineCreateToJSONTyped(json, false);
}

export function PluginQuarantineCreateToJSONTyped(value?: PluginQuarantineCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'namespace': value['namespace'],
        'package': value['_package'],
        'reason': value['reason'],
        'scope': PluginPolicyScopeToJSON(value['scope']),
        'version': value['version'],
    };
}
