/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PolicyConditionEvidence } from './PolicyConditionEvidence';
import {
    PolicyConditionEvidenceFromJSON,
    PolicyConditionEvidenceFromJSONTyped,
    PolicyConditionEvidenceToJSON,
    PolicyConditionEvidenceToJSONTyped,
} from './PolicyConditionEvidence';
import type { PolicyOutcome } from './PolicyOutcome';
import {
    PolicyOutcomeFromJSON,
    PolicyOutcomeFromJSONTyped,
    PolicyOutcomeToJSON,
    PolicyOutcomeToJSONTyped,
} from './PolicyOutcome';

/**
 *
 * @export
 * @interface PolicyRuleEvidence
 */
export interface PolicyRuleEvidence {
    /**
     *
     * @type {string}
     * @memberof PolicyRuleEvidence
     */
    approvalKey?: string | null;
    /**
     *
     * @type {Array<PolicyConditionEvidence>}
     * @memberof PolicyRuleEvidence
     */
    conditions?: Array<PolicyConditionEvidence>;
    /**
     *
     * @type {PolicyOutcome}
     * @memberof PolicyRuleEvidence
     */
    outcome: PolicyOutcome;
    /**
     *
     * @type {string}
     * @memberof PolicyRuleEvidence
     */
    policyId: string;
    /**
     *
     * @type {string}
     * @memberof PolicyRuleEvidence
     */
    policyKey: string;
    /**
     *
     * @type {number}
     * @memberof PolicyRuleEvidence
     */
    policyRevision: number;
    /**
     *
     * @type {string}
     * @memberof PolicyRuleEvidence
     */
    reason: string;
    /**
     *
     * @type {string}
     * @memberof PolicyRuleEvidence
     */
    ruleId: string;
}



/**
 * Check if a given object implements the PolicyRuleEvidence interface.
 */
export function instanceOfPolicyRuleEvidence(value: object): value is PolicyRuleEvidence {
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('policyId' in value) || value['policyId'] === undefined) return false;
    if (!('policyKey' in value) || value['policyKey'] === undefined) return false;
    if (!('policyRevision' in value) || value['policyRevision'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('ruleId' in value) || value['ruleId'] === undefined) return false;
    return true;
}

export function PolicyRuleEvidenceFromJSON(json: any): PolicyRuleEvidence {
    return PolicyRuleEvidenceFromJSONTyped(json, false);
}

export function PolicyRuleEvidenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyRuleEvidence {
    if (json == null) {
        return json;
    }
    return {

        'approvalKey': json['approvalKey'] === undefined ? undefined : json['approvalKey'] === null ? null : json['approvalKey'],
        'conditions': json['conditions'] == null ? undefined : ((json['conditions'] as Array<any>).map(PolicyConditionEvidenceFromJSON)),
        'outcome': PolicyOutcomeFromJSON(json['outcome']),
        'policyId': json['policyId'],
        'policyKey': json['policyKey'],
        'policyRevision': json['policyRevision'],
        'reason': json['reason'],
        'ruleId': json['ruleId'],
    };
}

export function PolicyRuleEvidenceToJSON(json: any): PolicyRuleEvidence {
    return PolicyRuleEvidenceToJSONTyped(json, false);
}

export function PolicyRuleEvidenceToJSONTyped(value?: PolicyRuleEvidence | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'approvalKey': value['approvalKey'],
        'conditions': value['conditions'] == null ? undefined : ((value['conditions'] as Array<any>).map(PolicyConditionEvidenceToJSON)),
        'outcome': PolicyOutcomeToJSON(value['outcome']),
        'policyId': value['policyId'],
        'policyKey': value['policyKey'],
        'policyRevision': value['policyRevision'],
        'reason': value['reason'],
        'ruleId': value['ruleId'],
    };
}
