/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const PromotionTargetKind = {
    Workflow: 'WORKFLOW',
    Agent: 'AGENT'
} as const;
export type PromotionTargetKind = typeof PromotionTargetKind[keyof typeof PromotionTargetKind];


export function instanceOfPromotionTargetKind(value: any): boolean {
    for (const key in PromotionTargetKind) {
        if (Object.prototype.hasOwnProperty.call(PromotionTargetKind, key)) {
            if (PromotionTargetKind[key as keyof typeof PromotionTargetKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PromotionTargetKindFromJSON(json: any): PromotionTargetKind {
    return PromotionTargetKindFromJSONTyped(json, false);
}

export function PromotionTargetKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromotionTargetKind {
    return json as PromotionTargetKind;
}

export function PromotionTargetKindToJSON(value?: PromotionTargetKind | null): any {
    return value as any;
}

export function PromotionTargetKindToJSONTyped(value: any, ignoreDiscriminator: boolean): PromotionTargetKind {
    return value as PromotionTargetKind;
}
