/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const RealtimeSeverity = {
    Trace: 'TRACE',
    Debug: 'DEBUG',
    Info: 'INFO',
    Warning: 'WARNING',
    Error: 'ERROR'
} as const;
export type RealtimeSeverity = typeof RealtimeSeverity[keyof typeof RealtimeSeverity];


export function instanceOfRealtimeSeverity(value: any): boolean {
    for (const key in RealtimeSeverity) {
        if (Object.prototype.hasOwnProperty.call(RealtimeSeverity, key)) {
            if (RealtimeSeverity[key as keyof typeof RealtimeSeverity] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RealtimeSeverityFromJSON(json: any): RealtimeSeverity {
    return RealtimeSeverityFromJSONTyped(json, false);
}

export function RealtimeSeverityFromJSONTyped(json: any, ignoreDiscriminator: boolean): RealtimeSeverity {
    return json as RealtimeSeverity;
}

export function RealtimeSeverityToJSON(value?: RealtimeSeverity | null): any {
    return value as any;
}

export function RealtimeSeverityToJSONTyped(value: any, ignoreDiscriminator: boolean): RealtimeSeverity {
    return value as RealtimeSeverity;
}
