/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskCompletion } from './TaskCompletion';
import {
    TaskCompletionFromJSON,
    TaskCompletionFromJSONTyped,
    TaskCompletionToJSON,
    TaskCompletionToJSONTyped,
} from './TaskCompletion';

/**
 *
 * @export
 * @interface ResumeTaskRequest
 */
export interface ResumeTaskRequest {
    /**
     *
     * @type {TaskCompletion}
     * @memberof ResumeTaskRequest
     */
    completion: TaskCompletion;
    /**
     *
     * @type {string}
     * @memberof ResumeTaskRequest
     */
    resumeToken: string;
}

/**
 * Check if a given object implements the ResumeTaskRequest interface.
 */
export function instanceOfResumeTaskRequest(value: object): value is ResumeTaskRequest {
    if (!('completion' in value) || value['completion'] === undefined) return false;
    if (!('resumeToken' in value) || value['resumeToken'] === undefined) return false;
    return true;
}

export function ResumeTaskRequestFromJSON(json: any): ResumeTaskRequest {
    return ResumeTaskRequestFromJSONTyped(json, false);
}

export function ResumeTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResumeTaskRequest {
    if (json == null) {
        return json;
    }
    return {

        'completion': TaskCompletionFromJSON(json['completion']),
        'resumeToken': json['resumeToken'],
    };
}

export function ResumeTaskRequestToJSON(json: any): ResumeTaskRequest {
    return ResumeTaskRequestToJSONTyped(json, false);
}

export function ResumeTaskRequestToJSONTyped(value?: ResumeTaskRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'completion': TaskCompletionToJSON(value['completion']),
        'resumeToken': value['resumeToken'],
    };
}
