/* tslint:disable */
/* eslint-disable */
/**
 * AMESH
 * Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TaskCachePurgeRequest
 */
export interface TaskCachePurgeRequest {
    /**
     *
     * @type {string}
     * @memberof TaskCachePurgeRequest
     */
    flowId?: string | null;
    /**
     *
     * @type {string}
     * @memberof TaskCachePurgeRequest
     */
    keyPrefix?: string | null;
    /**
     *
     * @type {string}
     * @memberof TaskCachePurgeRequest
     */
    namespace?: string | null;
    /**
     *
     * @type {string}
     * @memberof TaskCachePurgeRequest
     */
    reason: string;
    /**
     *
     * @type {string}
     * @memberof TaskCachePurgeRequest
     */
    taskId?: string | null;
}

/**
 * Check if a given object implements the TaskCachePurgeRequest interface.
 */
export function instanceOfTaskCachePurgeRequest(value: object): value is TaskCachePurgeRequest {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function TaskCachePurgeRequestFromJSON(json: any): TaskCachePurgeRequest {
    return TaskCachePurgeRequestFromJSONTyped(json, false);
}

export function TaskCachePurgeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskCachePurgeRequest {
    if (json == null) {
        return json;
    }
    return {

        'flowId': json['flowId'] === undefined ? undefined : json['flowId'] === null ? null : json['flowId'],
        'keyPrefix': json['keyPrefix'] === undefined ? undefined : json['keyPrefix'] === null ? null : json['keyPrefix'],
        'namespace': json['namespace'] === undefined ? undefined : json['namespace'] === null ? null : json['namespace'],
        'reason': json['reason'],
        'taskId': json['taskId'] === undefined ? undefined : json['taskId'] === null ? null : json['taskId'],
    };
}

export function TaskCachePurgeRequestToJSON(json: any): TaskCachePurgeRequest {
    return TaskCachePurgeRequestToJSONTyped(json, false);
}

export function TaskCachePurgeRequestToJSONTyped(value?: TaskCachePurgeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'flowId': value['flowId'],
        'keyPrefix': value['keyPrefix'],
        'namespace': value['namespace'],
        'reason': value['reason'],
        'taskId': value['taskId'],
    };
}
