/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"encoding/json"
	"fmt"
)

// ReconciliationTargetType the model 'ReconciliationTargetType'
type ReconciliationTargetType string

// List of ReconciliationTargetType
const (
	RECONCILIATIONTARGETTYPE_TENANT     ReconciliationTargetType = "TENANT"
	RECONCILIATIONTARGETTYPE_EXECUTION  ReconciliationTargetType = "EXECUTION"
	RECONCILIATIONTARGETTYPE_TRIGGER    ReconciliationTargetType = "TRIGGER"
	RECONCILIATIONTARGETTYPE_WORKER     ReconciliationTargetType = "WORKER"
	RECONCILIATIONTARGETTYPE_TIME_RANGE ReconciliationTargetType = "TIME_RANGE"
)

// All allowed values of ReconciliationTargetType enum
var AllowedReconciliationTargetTypeEnumValues = []ReconciliationTargetType{
	"TENANT",
	"EXECUTION",
	"TRIGGER",
	"WORKER",
	"TIME_RANGE",
}

func (v *ReconciliationTargetType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ReconciliationTargetType(value)
	for _, existing := range AllowedReconciliationTargetTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ReconciliationTargetType", value)
}

// NewReconciliationTargetTypeFromValue returns a pointer to a valid ReconciliationTargetType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewReconciliationTargetTypeFromValue(v string) (*ReconciliationTargetType, error) {
	ev := ReconciliationTargetType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ReconciliationTargetType: valid values are %v", v, AllowedReconciliationTargetTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ReconciliationTargetType) IsValid() bool {
	for _, existing := range AllowedReconciliationTargetTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ReconciliationTargetType value
func (v ReconciliationTargetType) Ptr() *ReconciliationTargetType {
	return &v
}

type NullableReconciliationTargetType struct {
	value *ReconciliationTargetType
	isSet bool
}

func (v NullableReconciliationTargetType) Get() *ReconciliationTargetType {
	return v.value
}

func (v *NullableReconciliationTargetType) Set(val *ReconciliationTargetType) {
	v.value = val
	v.isSet = true
}

func (v NullableReconciliationTargetType) IsSet() bool {
	return v.isSet
}

func (v *NullableReconciliationTargetType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReconciliationTargetType(val *ReconciliationTargetType) *NullableReconciliationTargetType {
	return &NullableReconciliationTargetType{value: val, isSet: true}
}

func (v NullableReconciliationTargetType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReconciliationTargetType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
