/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AssetCatalogExport type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetCatalogExport{}

// AssetCatalogExport struct for AssetCatalogExport
type AssetCatalogExport struct {
	Events []*map[string]interface{} `json:"events"`
	Format *string `json:"format,omitempty"`
	GeneratedAt time.Time `json:"generatedAt"`
	Producer string `json:"producer"`
}

type _AssetCatalogExport AssetCatalogExport

// NewAssetCatalogExport instantiates a new AssetCatalogExport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetCatalogExport(events []*map[string]interface{}, generatedAt time.Time, producer string) *AssetCatalogExport {
	this := AssetCatalogExport{}
	this.Events = events
	var format string = "openlineage"
	this.Format = &format
	this.GeneratedAt = generatedAt
	this.Producer = producer
	return &this
}

// NewAssetCatalogExportWithDefaults instantiates a new AssetCatalogExport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetCatalogExportWithDefaults() *AssetCatalogExport {
	this := AssetCatalogExport{}
	var format string = "openlineage"
	this.Format = &format
	return &this
}

// GetEvents returns the Events field value
func (o *AssetCatalogExport) GetEvents() []*map[string]interface{} {
	if o == nil {
		var ret []*map[string]interface{}
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *AssetCatalogExport) GetEventsOk() ([]*map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *AssetCatalogExport) SetEvents(v []*map[string]interface{}) {
	o.Events = v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *AssetCatalogExport) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetCatalogExport) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *AssetCatalogExport) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *AssetCatalogExport) SetFormat(v string) {
	o.Format = &v
}

// GetGeneratedAt returns the GeneratedAt field value
func (o *AssetCatalogExport) GetGeneratedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.GeneratedAt
}

// GetGeneratedAtOk returns a tuple with the GeneratedAt field value
// and a boolean to check if the value has been set.
func (o *AssetCatalogExport) GetGeneratedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GeneratedAt, true
}

// SetGeneratedAt sets field value
func (o *AssetCatalogExport) SetGeneratedAt(v time.Time) {
	o.GeneratedAt = v
}

// GetProducer returns the Producer field value
func (o *AssetCatalogExport) GetProducer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Producer
}

// GetProducerOk returns a tuple with the Producer field value
// and a boolean to check if the value has been set.
func (o *AssetCatalogExport) GetProducerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Producer, true
}

// SetProducer sets field value
func (o *AssetCatalogExport) SetProducer(v string) {
	o.Producer = v
}

func (o AssetCatalogExport) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetCatalogExport) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	toSerialize["generatedAt"] = o.GeneratedAt
	toSerialize["producer"] = o.Producer
	return toSerialize, nil
}

func (o *AssetCatalogExport) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
		"generatedAt",
		"producer",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssetCatalogExport := _AssetCatalogExport{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssetCatalogExport)

	if err != nil {
		return err
	}

	*o = AssetCatalogExport(varAssetCatalogExport)

	return err
}

type NullableAssetCatalogExport struct {
	value *AssetCatalogExport
	isSet bool
}

func (v NullableAssetCatalogExport) Get() *AssetCatalogExport {
	return v.value
}

func (v *NullableAssetCatalogExport) Set(val *AssetCatalogExport) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetCatalogExport) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetCatalogExport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetCatalogExport(val *AssetCatalogExport) *NullableAssetCatalogExport {
	return &NullableAssetCatalogExport{value: val, isSet: true}
}

func (v NullableAssetCatalogExport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetCatalogExport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
