/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the AgentProgressEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentProgressEvent{}

// AgentProgressEvent Safe progress frame after acceptance into the canonical journal.
type AgentProgressEvent struct {
	AcceptedAt       time.Time          `json:"acceptedAt"`
	Cursor           string             `json:"cursor"`
	EventId          string             `json:"eventId"`
	EventIndex       int32              `json:"eventIndex"`
	Frame            AgentProgressFrame `json:"frame"`
	SchemaVersion    *string            `json:"schemaVersion,omitempty"`
	ServiceSessionId string             `json:"serviceSessionId"`
}

type _AgentProgressEvent AgentProgressEvent

// NewAgentProgressEvent instantiates a new AgentProgressEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentProgressEvent(acceptedAt time.Time, cursor string, eventId string, eventIndex int32, frame AgentProgressFrame, serviceSessionId string) *AgentProgressEvent {
	this := AgentProgressEvent{}
	this.AcceptedAt = acceptedAt
	this.Cursor = cursor
	this.EventId = eventId
	this.EventIndex = eventIndex
	this.Frame = frame
	var schemaVersion string = "amesh.agent-progress-event/v1"
	this.SchemaVersion = &schemaVersion
	this.ServiceSessionId = serviceSessionId
	return &this
}

// NewAgentProgressEventWithDefaults instantiates a new AgentProgressEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentProgressEventWithDefaults() *AgentProgressEvent {
	this := AgentProgressEvent{}
	var schemaVersion string = "amesh.agent-progress-event/v1"
	this.SchemaVersion = &schemaVersion
	return &this
}

// GetAcceptedAt returns the AcceptedAt field value
func (o *AgentProgressEvent) GetAcceptedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.AcceptedAt
}

// GetAcceptedAtOk returns a tuple with the AcceptedAt field value
// and a boolean to check if the value has been set.
func (o *AgentProgressEvent) GetAcceptedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AcceptedAt, true
}

// SetAcceptedAt sets field value
func (o *AgentProgressEvent) SetAcceptedAt(v time.Time) {
	o.AcceptedAt = v
}

// GetCursor returns the Cursor field value
func (o *AgentProgressEvent) GetCursor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value
// and a boolean to check if the value has been set.
func (o *AgentProgressEvent) GetCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cursor, true
}

// SetCursor sets field value
func (o *AgentProgressEvent) SetCursor(v string) {
	o.Cursor = v
}

// GetEventId returns the EventId field value
func (o *AgentProgressEvent) GetEventId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *AgentProgressEvent) GetEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *AgentProgressEvent) SetEventId(v string) {
	o.EventId = v
}

// GetEventIndex returns the EventIndex field value
func (o *AgentProgressEvent) GetEventIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EventIndex
}

// GetEventIndexOk returns a tuple with the EventIndex field value
// and a boolean to check if the value has been set.
func (o *AgentProgressEvent) GetEventIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventIndex, true
}

// SetEventIndex sets field value
func (o *AgentProgressEvent) SetEventIndex(v int32) {
	o.EventIndex = v
}

// GetFrame returns the Frame field value
func (o *AgentProgressEvent) GetFrame() AgentProgressFrame {
	if o == nil {
		var ret AgentProgressFrame
		return ret
	}

	return o.Frame
}

// GetFrameOk returns a tuple with the Frame field value
// and a boolean to check if the value has been set.
func (o *AgentProgressEvent) GetFrameOk() (*AgentProgressFrame, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Frame, true
}

// SetFrame sets field value
func (o *AgentProgressEvent) SetFrame(v AgentProgressFrame) {
	o.Frame = v
}

// GetSchemaVersion returns the SchemaVersion field value if set, zero value otherwise.
func (o *AgentProgressEvent) GetSchemaVersion() string {
	if o == nil || IsNil(o.SchemaVersion) {
		var ret string
		return ret
	}
	return *o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentProgressEvent) GetSchemaVersionOk() (*string, bool) {
	if o == nil || IsNil(o.SchemaVersion) {
		return nil, false
	}
	return o.SchemaVersion, true
}

// HasSchemaVersion returns a boolean if a field has been set.
func (o *AgentProgressEvent) HasSchemaVersion() bool {
	if o != nil && !IsNil(o.SchemaVersion) {
		return true
	}

	return false
}

// SetSchemaVersion gets a reference to the given string and assigns it to the SchemaVersion field.
func (o *AgentProgressEvent) SetSchemaVersion(v string) {
	o.SchemaVersion = &v
}

// GetServiceSessionId returns the ServiceSessionId field value
func (o *AgentProgressEvent) GetServiceSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceSessionId
}

// GetServiceSessionIdOk returns a tuple with the ServiceSessionId field value
// and a boolean to check if the value has been set.
func (o *AgentProgressEvent) GetServiceSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceSessionId, true
}

// SetServiceSessionId sets field value
func (o *AgentProgressEvent) SetServiceSessionId(v string) {
	o.ServiceSessionId = v
}

func (o AgentProgressEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentProgressEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["acceptedAt"] = o.AcceptedAt
	toSerialize["cursor"] = o.Cursor
	toSerialize["eventId"] = o.EventId
	toSerialize["eventIndex"] = o.EventIndex
	toSerialize["frame"] = o.Frame
	if !IsNil(o.SchemaVersion) {
		toSerialize["schemaVersion"] = o.SchemaVersion
	}
	toSerialize["serviceSessionId"] = o.ServiceSessionId
	return toSerialize, nil
}

func (o *AgentProgressEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"acceptedAt",
		"cursor",
		"eventId",
		"eventIndex",
		"frame",
		"serviceSessionId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentProgressEvent := _AgentProgressEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentProgressEvent)

	if err != nil {
		return err
	}

	*o = AgentProgressEvent(varAgentProgressEvent)

	return err
}

type NullableAgentProgressEvent struct {
	value *AgentProgressEvent
	isSet bool
}

func (v NullableAgentProgressEvent) Get() *AgentProgressEvent {
	return v.value
}

func (v *NullableAgentProgressEvent) Set(val *AgentProgressEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentProgressEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentProgressEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentProgressEvent(val *AgentProgressEvent) *NullableAgentProgressEvent {
	return &NullableAgentProgressEvent{value: val, isSet: true}
}

func (v NullableAgentProgressEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentProgressEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
