/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"encoding/json"
)

// checks if the PolicyPluginContext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyPluginContext{}

// PolicyPluginContext struct for PolicyPluginContext
type PolicyPluginContext struct {
	Packages []*map[string]interface{} `json:"packages,omitempty"`
	TaskTypes []*string `json:"taskTypes,omitempty"`
}

// NewPolicyPluginContext instantiates a new PolicyPluginContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyPluginContext() *PolicyPluginContext {
	this := PolicyPluginContext{}
	return &this
}

// NewPolicyPluginContextWithDefaults instantiates a new PolicyPluginContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyPluginContextWithDefaults() *PolicyPluginContext {
	this := PolicyPluginContext{}
	return &this
}

// GetPackages returns the Packages field value if set, zero value otherwise.
func (o *PolicyPluginContext) GetPackages() []*map[string]interface{} {
	if o == nil || IsNil(o.Packages) {
		var ret []*map[string]interface{}
		return ret
	}
	return o.Packages
}

// GetPackagesOk returns a tuple with the Packages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyPluginContext) GetPackagesOk() ([]*map[string]interface{}, bool) {
	if o == nil || IsNil(o.Packages) {
		return nil, false
	}
	return o.Packages, true
}

// HasPackages returns a boolean if a field has been set.
func (o *PolicyPluginContext) HasPackages() bool {
	if o != nil && !IsNil(o.Packages) {
		return true
	}

	return false
}

// SetPackages gets a reference to the given []*map[string]interface{} and assigns it to the Packages field.
func (o *PolicyPluginContext) SetPackages(v []*map[string]interface{}) {
	o.Packages = v
}

// GetTaskTypes returns the TaskTypes field value if set, zero value otherwise.
func (o *PolicyPluginContext) GetTaskTypes() []*string {
	if o == nil || IsNil(o.TaskTypes) {
		var ret []*string
		return ret
	}
	return o.TaskTypes
}

// GetTaskTypesOk returns a tuple with the TaskTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyPluginContext) GetTaskTypesOk() ([]*string, bool) {
	if o == nil || IsNil(o.TaskTypes) {
		return nil, false
	}
	return o.TaskTypes, true
}

// HasTaskTypes returns a boolean if a field has been set.
func (o *PolicyPluginContext) HasTaskTypes() bool {
	if o != nil && !IsNil(o.TaskTypes) {
		return true
	}

	return false
}

// SetTaskTypes gets a reference to the given []*string and assigns it to the TaskTypes field.
func (o *PolicyPluginContext) SetTaskTypes(v []*string) {
	o.TaskTypes = v
}

func (o PolicyPluginContext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyPluginContext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Packages) {
		toSerialize["packages"] = o.Packages
	}
	if !IsNil(o.TaskTypes) {
		toSerialize["taskTypes"] = o.TaskTypes
	}
	return toSerialize, nil
}

type NullablePolicyPluginContext struct {
	value *PolicyPluginContext
	isSet bool
}

func (v NullablePolicyPluginContext) Get() *PolicyPluginContext {
	return v.value
}

func (v *NullablePolicyPluginContext) Set(val *PolicyPluginContext) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyPluginContext) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyPluginContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyPluginContext(val *PolicyPluginContext) *NullablePolicyPluginContext {
	return &NullablePolicyPluginContext{value: val, isSet: true}
}

func (v NullablePolicyPluginContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyPluginContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
