/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"encoding/json"
	"fmt"
)

// SearchSortField the model 'SearchSortField'
type SearchSortField string

// List of SearchSortField
const (
	SEARCHSORTFIELD_RELEVANCE   SearchSortField = "RELEVANCE"
	SEARCHSORTFIELD_TITLE       SearchSortField = "TITLE"
	SEARCHSORTFIELD_OCCURRED_AT SearchSortField = "OCCURRED_AT"
	SEARCHSORTFIELD_UPDATED_AT  SearchSortField = "UPDATED_AT"
	SEARCHSORTFIELD_TYPE        SearchSortField = "TYPE"
	SEARCHSORTFIELD_STATE       SearchSortField = "STATE"
)

// All allowed values of SearchSortField enum
var AllowedSearchSortFieldEnumValues = []SearchSortField{
	"RELEVANCE",
	"TITLE",
	"OCCURRED_AT",
	"UPDATED_AT",
	"TYPE",
	"STATE",
}

func (v *SearchSortField) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SearchSortField(value)
	for _, existing := range AllowedSearchSortFieldEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SearchSortField", value)
}

// NewSearchSortFieldFromValue returns a pointer to a valid SearchSortField
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSearchSortFieldFromValue(v string) (*SearchSortField, error) {
	ev := SearchSortField(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SearchSortField: valid values are %v", v, AllowedSearchSortFieldEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SearchSortField) IsValid() bool {
	for _, existing := range AllowedSearchSortFieldEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SearchSortField value
func (v SearchSortField) Ptr() *SearchSortField {
	return &v
}

type NullableSearchSortField struct {
	value *SearchSortField
	isSet bool
}

func (v NullableSearchSortField) Get() *SearchSortField {
	return v.value
}

func (v *NullableSearchSortField) Set(val *SearchSortField) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchSortField) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchSortField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchSortField(val *SearchSortField) *NullableSearchSortField {
	return &NullableSearchSortField{value: val, isSet: true}
}

func (v NullableSearchSortField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchSortField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
