/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"encoding/json"
	"time"
)

// checks if the CompliancePackageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompliancePackageRequest{}

// CompliancePackageRequest struct for CompliancePackageRequest
type CompliancePackageRequest struct {
	MaxAuditEvents *int32 `json:"maxAuditEvents,omitempty"`
	OccurredFrom NullableTime `json:"occurredFrom,omitempty"`
	OccurredTo NullableTime `json:"occurredTo,omitempty"`
}

// NewCompliancePackageRequest instantiates a new CompliancePackageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompliancePackageRequest() *CompliancePackageRequest {
	this := CompliancePackageRequest{}
	var maxAuditEvents int32 = 10000
	this.MaxAuditEvents = &maxAuditEvents
	return &this
}

// NewCompliancePackageRequestWithDefaults instantiates a new CompliancePackageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompliancePackageRequestWithDefaults() *CompliancePackageRequest {
	this := CompliancePackageRequest{}
	var maxAuditEvents int32 = 10000
	this.MaxAuditEvents = &maxAuditEvents
	return &this
}

// GetMaxAuditEvents returns the MaxAuditEvents field value if set, zero value otherwise.
func (o *CompliancePackageRequest) GetMaxAuditEvents() int32 {
	if o == nil || IsNil(o.MaxAuditEvents) {
		var ret int32
		return ret
	}
	return *o.MaxAuditEvents
}

// GetMaxAuditEventsOk returns a tuple with the MaxAuditEvents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompliancePackageRequest) GetMaxAuditEventsOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxAuditEvents) {
		return nil, false
	}
	return o.MaxAuditEvents, true
}

// HasMaxAuditEvents returns a boolean if a field has been set.
func (o *CompliancePackageRequest) HasMaxAuditEvents() bool {
	if o != nil && !IsNil(o.MaxAuditEvents) {
		return true
	}

	return false
}

// SetMaxAuditEvents gets a reference to the given int32 and assigns it to the MaxAuditEvents field.
func (o *CompliancePackageRequest) SetMaxAuditEvents(v int32) {
	o.MaxAuditEvents = &v
}

// GetOccurredFrom returns the OccurredFrom field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompliancePackageRequest) GetOccurredFrom() time.Time {
	if o == nil || IsNil(o.OccurredFrom.Get()) {
		var ret time.Time
		return ret
	}
	return *o.OccurredFrom.Get()
}

// GetOccurredFromOk returns a tuple with the OccurredFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompliancePackageRequest) GetOccurredFromOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.OccurredFrom.Get(), o.OccurredFrom.IsSet()
}

// HasOccurredFrom returns a boolean if a field has been set.
func (o *CompliancePackageRequest) HasOccurredFrom() bool {
	if o != nil && o.OccurredFrom.IsSet() {
		return true
	}

	return false
}

// SetOccurredFrom gets a reference to the given NullableTime and assigns it to the OccurredFrom field.
func (o *CompliancePackageRequest) SetOccurredFrom(v time.Time) {
	o.OccurredFrom.Set(&v)
}
// SetOccurredFromNil sets the value for OccurredFrom to be an explicit nil
func (o *CompliancePackageRequest) SetOccurredFromNil() {
	o.OccurredFrom.Set(nil)
}

// UnsetOccurredFrom ensures that no value is present for OccurredFrom, not even an explicit nil
func (o *CompliancePackageRequest) UnsetOccurredFrom() {
	o.OccurredFrom.Unset()
}

// GetOccurredTo returns the OccurredTo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompliancePackageRequest) GetOccurredTo() time.Time {
	if o == nil || IsNil(o.OccurredTo.Get()) {
		var ret time.Time
		return ret
	}
	return *o.OccurredTo.Get()
}

// GetOccurredToOk returns a tuple with the OccurredTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompliancePackageRequest) GetOccurredToOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.OccurredTo.Get(), o.OccurredTo.IsSet()
}

// HasOccurredTo returns a boolean if a field has been set.
func (o *CompliancePackageRequest) HasOccurredTo() bool {
	if o != nil && o.OccurredTo.IsSet() {
		return true
	}

	return false
}

// SetOccurredTo gets a reference to the given NullableTime and assigns it to the OccurredTo field.
func (o *CompliancePackageRequest) SetOccurredTo(v time.Time) {
	o.OccurredTo.Set(&v)
}
// SetOccurredToNil sets the value for OccurredTo to be an explicit nil
func (o *CompliancePackageRequest) SetOccurredToNil() {
	o.OccurredTo.Set(nil)
}

// UnsetOccurredTo ensures that no value is present for OccurredTo, not even an explicit nil
func (o *CompliancePackageRequest) UnsetOccurredTo() {
	o.OccurredTo.Unset()
}

func (o CompliancePackageRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompliancePackageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaxAuditEvents) {
		toSerialize["maxAuditEvents"] = o.MaxAuditEvents
	}
	if o.OccurredFrom.IsSet() {
		toSerialize["occurredFrom"] = o.OccurredFrom.Get()
	}
	if o.OccurredTo.IsSet() {
		toSerialize["occurredTo"] = o.OccurredTo.Get()
	}
	return toSerialize, nil
}

type NullableCompliancePackageRequest struct {
	value *CompliancePackageRequest
	isSet bool
}

func (v NullableCompliancePackageRequest) Get() *CompliancePackageRequest {
	return v.value
}

func (v *NullableCompliancePackageRequest) Set(val *CompliancePackageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCompliancePackageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCompliancePackageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompliancePackageRequest(val *CompliancePackageRequest) *NullableCompliancePackageRequest {
	return &NullableCompliancePackageRequest{value: val, isSet: true}
}

func (v NullableCompliancePackageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompliancePackageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
