/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the FlowTestQualityGate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlowTestQualityGate{}

// FlowTestQualityGate struct for FlowTestQualityGate
type FlowTestQualityGate struct {
	Enabled bool `json:"enabled"`
	MinimumCoverage float32 `json:"minimumCoverage"`
	Namespace string `json:"namespace"`
	RequiredTestIds []string `json:"requiredTestIds"`
	TenantId string `json:"tenantId"`
	UpdatedAt time.Time `json:"updatedAt"`
	UpdatedBy string `json:"updatedBy"`
	Version int32 `json:"version"`
}

type _FlowTestQualityGate FlowTestQualityGate

// NewFlowTestQualityGate instantiates a new FlowTestQualityGate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlowTestQualityGate(enabled bool, minimumCoverage float32, namespace string, requiredTestIds []string, tenantId string, updatedAt time.Time, updatedBy string, version int32) *FlowTestQualityGate {
	this := FlowTestQualityGate{}
	this.Enabled = enabled
	this.MinimumCoverage = minimumCoverage
	this.Namespace = namespace
	this.RequiredTestIds = requiredTestIds
	this.TenantId = tenantId
	this.UpdatedAt = updatedAt
	this.UpdatedBy = updatedBy
	this.Version = version
	return &this
}

// NewFlowTestQualityGateWithDefaults instantiates a new FlowTestQualityGate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlowTestQualityGateWithDefaults() *FlowTestQualityGate {
	this := FlowTestQualityGate{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *FlowTestQualityGate) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *FlowTestQualityGate) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *FlowTestQualityGate) SetEnabled(v bool) {
	o.Enabled = v
}

// GetMinimumCoverage returns the MinimumCoverage field value
func (o *FlowTestQualityGate) GetMinimumCoverage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.MinimumCoverage
}

// GetMinimumCoverageOk returns a tuple with the MinimumCoverage field value
// and a boolean to check if the value has been set.
func (o *FlowTestQualityGate) GetMinimumCoverageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinimumCoverage, true
}

// SetMinimumCoverage sets field value
func (o *FlowTestQualityGate) SetMinimumCoverage(v float32) {
	o.MinimumCoverage = v
}

// GetNamespace returns the Namespace field value
func (o *FlowTestQualityGate) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *FlowTestQualityGate) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *FlowTestQualityGate) SetNamespace(v string) {
	o.Namespace = v
}

// GetRequiredTestIds returns the RequiredTestIds field value
func (o *FlowTestQualityGate) GetRequiredTestIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RequiredTestIds
}

// GetRequiredTestIdsOk returns a tuple with the RequiredTestIds field value
// and a boolean to check if the value has been set.
func (o *FlowTestQualityGate) GetRequiredTestIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequiredTestIds, true
}

// SetRequiredTestIds sets field value
func (o *FlowTestQualityGate) SetRequiredTestIds(v []string) {
	o.RequiredTestIds = v
}

// GetTenantId returns the TenantId field value
func (o *FlowTestQualityGate) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *FlowTestQualityGate) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *FlowTestQualityGate) SetTenantId(v string) {
	o.TenantId = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *FlowTestQualityGate) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *FlowTestQualityGate) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *FlowTestQualityGate) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetUpdatedBy returns the UpdatedBy field value
func (o *FlowTestQualityGate) GetUpdatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedBy
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value
// and a boolean to check if the value has been set.
func (o *FlowTestQualityGate) GetUpdatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedBy, true
}

// SetUpdatedBy sets field value
func (o *FlowTestQualityGate) SetUpdatedBy(v string) {
	o.UpdatedBy = v
}

// GetVersion returns the Version field value
func (o *FlowTestQualityGate) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *FlowTestQualityGate) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *FlowTestQualityGate) SetVersion(v int32) {
	o.Version = v
}

func (o FlowTestQualityGate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlowTestQualityGate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	toSerialize["minimumCoverage"] = o.MinimumCoverage
	toSerialize["namespace"] = o.Namespace
	toSerialize["requiredTestIds"] = o.RequiredTestIds
	toSerialize["tenantId"] = o.TenantId
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["updatedBy"] = o.UpdatedBy
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *FlowTestQualityGate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"minimumCoverage",
		"namespace",
		"requiredTestIds",
		"tenantId",
		"updatedAt",
		"updatedBy",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFlowTestQualityGate := _FlowTestQualityGate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFlowTestQualityGate)

	if err != nil {
		return err
	}

	*o = FlowTestQualityGate(varFlowTestQualityGate)

	return err
}

type NullableFlowTestQualityGate struct {
	value *FlowTestQualityGate
	isSet bool
}

func (v NullableFlowTestQualityGate) Get() *FlowTestQualityGate {
	return v.value
}

func (v *NullableFlowTestQualityGate) Set(val *FlowTestQualityGate) {
	v.value = val
	v.isSet = true
}

func (v NullableFlowTestQualityGate) IsSet() bool {
	return v.isSet
}

func (v *NullableFlowTestQualityGate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlowTestQualityGate(val *FlowTestQualityGate) *NullableFlowTestQualityGate {
	return &NullableFlowTestQualityGate{value: val, isSet: true}
}

func (v NullableFlowTestQualityGate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlowTestQualityGate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
