/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServiceDrainRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceDrainRequest{}

// ServiceDrainRequest struct for ServiceDrainRequest
type ServiceDrainRequest struct {
	ExpectedVersion int32 `json:"expectedVersion"`
	Reason string `json:"reason"`
}

type _ServiceDrainRequest ServiceDrainRequest

// NewServiceDrainRequest instantiates a new ServiceDrainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceDrainRequest(expectedVersion int32, reason string) *ServiceDrainRequest {
	this := ServiceDrainRequest{}
	this.ExpectedVersion = expectedVersion
	this.Reason = reason
	return &this
}

// NewServiceDrainRequestWithDefaults instantiates a new ServiceDrainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceDrainRequestWithDefaults() *ServiceDrainRequest {
	this := ServiceDrainRequest{}
	return &this
}

// GetExpectedVersion returns the ExpectedVersion field value
func (o *ServiceDrainRequest) GetExpectedVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpectedVersion
}

// GetExpectedVersionOk returns a tuple with the ExpectedVersion field value
// and a boolean to check if the value has been set.
func (o *ServiceDrainRequest) GetExpectedVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedVersion, true
}

// SetExpectedVersion sets field value
func (o *ServiceDrainRequest) SetExpectedVersion(v int32) {
	o.ExpectedVersion = v
}

// GetReason returns the Reason field value
func (o *ServiceDrainRequest) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *ServiceDrainRequest) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *ServiceDrainRequest) SetReason(v string) {
	o.Reason = v
}

func (o ServiceDrainRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceDrainRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["expectedVersion"] = o.ExpectedVersion
	toSerialize["reason"] = o.Reason
	return toSerialize, nil
}

func (o *ServiceDrainRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"expectedVersion",
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceDrainRequest := _ServiceDrainRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServiceDrainRequest)

	if err != nil {
		return err
	}

	*o = ServiceDrainRequest(varServiceDrainRequest)

	return err
}

type NullableServiceDrainRequest struct {
	value *ServiceDrainRequest
	isSet bool
}

func (v NullableServiceDrainRequest) Get() *ServiceDrainRequest {
	return v.value
}

func (v *NullableServiceDrainRequest) Set(val *ServiceDrainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceDrainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceDrainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceDrainRequest(val *ServiceDrainRequest) *NullableServiceDrainRequest {
	return &NullableServiceDrainRequest{value: val, isSet: true}
}

func (v NullableServiceDrainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceDrainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
