/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"encoding/json"
	"fmt"
)

// AgentInvocationKind the model 'AgentInvocationKind'
type AgentInvocationKind string

// List of AgentInvocationKind
const (
	AGENTINVOCATIONKIND_MODEL AgentInvocationKind = "MODEL"
	AGENTINVOCATIONKIND_MCP   AgentInvocationKind = "MCP"
)

// All allowed values of AgentInvocationKind enum
var AllowedAgentInvocationKindEnumValues = []AgentInvocationKind{
	"MODEL",
	"MCP",
}

func (v *AgentInvocationKind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AgentInvocationKind(value)
	for _, existing := range AllowedAgentInvocationKindEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AgentInvocationKind", value)
}

// NewAgentInvocationKindFromValue returns a pointer to a valid AgentInvocationKind
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAgentInvocationKindFromValue(v string) (*AgentInvocationKind, error) {
	ev := AgentInvocationKind(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AgentInvocationKind: valid values are %v", v, AllowedAgentInvocationKindEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AgentInvocationKind) IsValid() bool {
	for _, existing := range AllowedAgentInvocationKindEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AgentInvocationKind value
func (v AgentInvocationKind) Ptr() *AgentInvocationKind {
	return &v
}

type NullableAgentInvocationKind struct {
	value *AgentInvocationKind
	isSet bool
}

func (v NullableAgentInvocationKind) Get() *AgentInvocationKind {
	return v.value
}

func (v *NullableAgentInvocationKind) Set(val *AgentInvocationKind) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentInvocationKind) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentInvocationKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentInvocationKind(val *AgentInvocationKind) *NullableAgentInvocationKind {
	return &NullableAgentInvocationKind{value: val, isSet: true}
}

func (v NullableAgentInvocationKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentInvocationKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
