/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"encoding/json"
	"fmt"
)

// checks if the PluginDefaultDefinition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PluginDefaultDefinition{}

// PluginDefaultDefinition struct for PluginDefaultDefinition
type PluginDefaultDefinition struct {
	Forced *bool `json:"forced,omitempty"`
	Type string `json:"type"`
	Values map[string]interface{} `json:"values,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PluginDefaultDefinition PluginDefaultDefinition

// NewPluginDefaultDefinition instantiates a new PluginDefaultDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPluginDefaultDefinition(type_ string) *PluginDefaultDefinition {
	this := PluginDefaultDefinition{}
	var forced bool = false
	this.Forced = &forced
	this.Type = type_
	return &this
}

// NewPluginDefaultDefinitionWithDefaults instantiates a new PluginDefaultDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPluginDefaultDefinitionWithDefaults() *PluginDefaultDefinition {
	this := PluginDefaultDefinition{}
	var forced bool = false
	this.Forced = &forced
	return &this
}

// GetForced returns the Forced field value if set, zero value otherwise.
func (o *PluginDefaultDefinition) GetForced() bool {
	if o == nil || IsNil(o.Forced) {
		var ret bool
		return ret
	}
	return *o.Forced
}

// GetForcedOk returns a tuple with the Forced field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PluginDefaultDefinition) GetForcedOk() (*bool, bool) {
	if o == nil || IsNil(o.Forced) {
		return nil, false
	}
	return o.Forced, true
}

// HasForced returns a boolean if a field has been set.
func (o *PluginDefaultDefinition) HasForced() bool {
	if o != nil && !IsNil(o.Forced) {
		return true
	}

	return false
}

// SetForced gets a reference to the given bool and assigns it to the Forced field.
func (o *PluginDefaultDefinition) SetForced(v bool) {
	o.Forced = &v
}

// GetType returns the Type field value
func (o *PluginDefaultDefinition) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PluginDefaultDefinition) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PluginDefaultDefinition) SetType(v string) {
	o.Type = v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *PluginDefaultDefinition) GetValues() map[string]interface{} {
	if o == nil || IsNil(o.Values) {
		var ret map[string]interface{}
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PluginDefaultDefinition) GetValuesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Values) {
		return map[string]interface{}{}, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *PluginDefaultDefinition) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given map[string]interface{} and assigns it to the Values field.
func (o *PluginDefaultDefinition) SetValues(v map[string]interface{}) {
	o.Values = v
}

func (o PluginDefaultDefinition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PluginDefaultDefinition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Forced) {
		toSerialize["forced"] = o.Forced
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PluginDefaultDefinition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPluginDefaultDefinition := _PluginDefaultDefinition{}

	err = json.Unmarshal(data, &varPluginDefaultDefinition)

	if err != nil {
		return err
	}

	*o = PluginDefaultDefinition(varPluginDefaultDefinition)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "forced")
		delete(additionalProperties, "type")
		delete(additionalProperties, "values")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePluginDefaultDefinition struct {
	value *PluginDefaultDefinition
	isSet bool
}

func (v NullablePluginDefaultDefinition) Get() *PluginDefaultDefinition {
	return v.value
}

func (v *NullablePluginDefaultDefinition) Set(val *PluginDefaultDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginDefaultDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginDefaultDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginDefaultDefinition(val *PluginDefaultDefinition) *NullablePluginDefaultDefinition {
	return &NullablePluginDefaultDefinition{value: val, isSet: true}
}

func (v NullablePluginDefaultDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginDefaultDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
