/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"encoding/json"
	"fmt"
)

// ReconciliationRunState the model 'ReconciliationRunState'
type ReconciliationRunState string

// List of ReconciliationRunState
const (
	RECONCILIATIONRUNSTATE_RUNNING ReconciliationRunState = "RUNNING"
	RECONCILIATIONRUNSTATE_COMPLETED ReconciliationRunState = "COMPLETED"
	RECONCILIATIONRUNSTATE_FAILED ReconciliationRunState = "FAILED"
)

// All allowed values of ReconciliationRunState enum
var AllowedReconciliationRunStateEnumValues = []ReconciliationRunState{
	"RUNNING",
	"COMPLETED",
	"FAILED",
}

func (v *ReconciliationRunState) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ReconciliationRunState(value)
	for _, existing := range AllowedReconciliationRunStateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ReconciliationRunState", value)
}

// NewReconciliationRunStateFromValue returns a pointer to a valid ReconciliationRunState
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewReconciliationRunStateFromValue(v string) (*ReconciliationRunState, error) {
	ev := ReconciliationRunState(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ReconciliationRunState: valid values are %v", v, AllowedReconciliationRunStateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ReconciliationRunState) IsValid() bool {
	for _, existing := range AllowedReconciliationRunStateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ReconciliationRunState value
func (v ReconciliationRunState) Ptr() *ReconciliationRunState {
	return &v
}

type NullableReconciliationRunState struct {
	value *ReconciliationRunState
	isSet bool
}

func (v NullableReconciliationRunState) Get() *ReconciliationRunState {
	return v.value
}

func (v *NullableReconciliationRunState) Set(val *ReconciliationRunState) {
	v.value = val
	v.isSet = true
}

func (v NullableReconciliationRunState) IsSet() bool {
	return v.isSet
}

func (v *NullableReconciliationRunState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReconciliationRunState(val *ReconciliationRunState) *NullableReconciliationRunState {
	return &NullableReconciliationRunState{value: val, isSet: true}
}

func (v NullableReconciliationRunState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReconciliationRunState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
