/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PluginRegistryYankRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PluginRegistryYankRequest{}

// PluginRegistryYankRequest struct for PluginRegistryYankRequest
type PluginRegistryYankRequest struct {
	Reason string `json:"reason"`
}

type _PluginRegistryYankRequest PluginRegistryYankRequest

// NewPluginRegistryYankRequest instantiates a new PluginRegistryYankRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPluginRegistryYankRequest(reason string) *PluginRegistryYankRequest {
	this := PluginRegistryYankRequest{}
	this.Reason = reason
	return &this
}

// NewPluginRegistryYankRequestWithDefaults instantiates a new PluginRegistryYankRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPluginRegistryYankRequestWithDefaults() *PluginRegistryYankRequest {
	this := PluginRegistryYankRequest{}
	return &this
}

// GetReason returns the Reason field value
func (o *PluginRegistryYankRequest) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *PluginRegistryYankRequest) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *PluginRegistryYankRequest) SetReason(v string) {
	o.Reason = v
}

func (o PluginRegistryYankRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PluginRegistryYankRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["reason"] = o.Reason
	return toSerialize, nil
}

func (o *PluginRegistryYankRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPluginRegistryYankRequest := _PluginRegistryYankRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPluginRegistryYankRequest)

	if err != nil {
		return err
	}

	*o = PluginRegistryYankRequest(varPluginRegistryYankRequest)

	return err
}

type NullablePluginRegistryYankRequest struct {
	value *PluginRegistryYankRequest
	isSet bool
}

func (v NullablePluginRegistryYankRequest) Get() *PluginRegistryYankRequest {
	return v.value
}

func (v *NullablePluginRegistryYankRequest) Set(val *PluginRegistryYankRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginRegistryYankRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginRegistryYankRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginRegistryYankRequest(val *PluginRegistryYankRequest) *NullablePluginRegistryYankRequest {
	return &NullablePluginRegistryYankRequest{value: val, isSet: true}
}

func (v NullablePluginRegistryYankRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginRegistryYankRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
