/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the PolicyRevision type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyRevision{}

// PolicyRevision struct for PolicyRevision
type PolicyRevision struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	CreatedBy string `json:"createdBy"`
	Digest string `json:"digest" validate:"regexp=^sha256:[0-9a-f]{64}$"`
	Document PolicyDocument `json:"document"`
	PolicyId *string `json:"policyId,omitempty"`
	Revision int32 `json:"revision"`
	TenantId NullableString `json:"tenantId,omitempty"`
}

type _PolicyRevision PolicyRevision

// NewPolicyRevision instantiates a new PolicyRevision object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyRevision(createdBy string, digest string, document PolicyDocument, revision int32) *PolicyRevision {
	this := PolicyRevision{}
	this.CreatedBy = createdBy
	this.Digest = digest
	this.Document = document
	this.Revision = revision
	return &this
}

// NewPolicyRevisionWithDefaults instantiates a new PolicyRevision object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyRevisionWithDefaults() *PolicyRevision {
	this := PolicyRevision{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *PolicyRevision) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyRevision) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *PolicyRevision) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *PolicyRevision) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetCreatedBy returns the CreatedBy field value
func (o *PolicyRevision) GetCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *PolicyRevision) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *PolicyRevision) SetCreatedBy(v string) {
	o.CreatedBy = v
}

// GetDigest returns the Digest field value
func (o *PolicyRevision) GetDigest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Digest
}

// GetDigestOk returns a tuple with the Digest field value
// and a boolean to check if the value has been set.
func (o *PolicyRevision) GetDigestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Digest, true
}

// SetDigest sets field value
func (o *PolicyRevision) SetDigest(v string) {
	o.Digest = v
}

// GetDocument returns the Document field value
func (o *PolicyRevision) GetDocument() PolicyDocument {
	if o == nil {
		var ret PolicyDocument
		return ret
	}

	return o.Document
}

// GetDocumentOk returns a tuple with the Document field value
// and a boolean to check if the value has been set.
func (o *PolicyRevision) GetDocumentOk() (*PolicyDocument, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Document, true
}

// SetDocument sets field value
func (o *PolicyRevision) SetDocument(v PolicyDocument) {
	o.Document = v
}

// GetPolicyId returns the PolicyId field value if set, zero value otherwise.
func (o *PolicyRevision) GetPolicyId() string {
	if o == nil || IsNil(o.PolicyId) {
		var ret string
		return ret
	}
	return *o.PolicyId
}

// GetPolicyIdOk returns a tuple with the PolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyRevision) GetPolicyIdOk() (*string, bool) {
	if o == nil || IsNil(o.PolicyId) {
		return nil, false
	}
	return o.PolicyId, true
}

// HasPolicyId returns a boolean if a field has been set.
func (o *PolicyRevision) HasPolicyId() bool {
	if o != nil && !IsNil(o.PolicyId) {
		return true
	}

	return false
}

// SetPolicyId gets a reference to the given string and assigns it to the PolicyId field.
func (o *PolicyRevision) SetPolicyId(v string) {
	o.PolicyId = &v
}

// GetRevision returns the Revision field value
func (o *PolicyRevision) GetRevision() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value
// and a boolean to check if the value has been set.
func (o *PolicyRevision) GetRevisionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Revision, true
}

// SetRevision sets field value
func (o *PolicyRevision) SetRevision(v int32) {
	o.Revision = v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PolicyRevision) GetTenantId() string {
	if o == nil || IsNil(o.TenantId.Get()) {
		var ret string
		return ret
	}
	return *o.TenantId.Get()
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PolicyRevision) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantId.Get(), o.TenantId.IsSet()
}

// HasTenantId returns a boolean if a field has been set.
func (o *PolicyRevision) HasTenantId() bool {
	if o != nil && o.TenantId.IsSet() {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given NullableString and assigns it to the TenantId field.
func (o *PolicyRevision) SetTenantId(v string) {
	o.TenantId.Set(&v)
}
// SetTenantIdNil sets the value for TenantId to be an explicit nil
func (o *PolicyRevision) SetTenantIdNil() {
	o.TenantId.Set(nil)
}

// UnsetTenantId ensures that no value is present for TenantId, not even an explicit nil
func (o *PolicyRevision) UnsetTenantId() {
	o.TenantId.Unset()
}

func (o PolicyRevision) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyRevision) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	toSerialize["createdBy"] = o.CreatedBy
	toSerialize["digest"] = o.Digest
	toSerialize["document"] = o.Document
	if !IsNil(o.PolicyId) {
		toSerialize["policyId"] = o.PolicyId
	}
	toSerialize["revision"] = o.Revision
	if o.TenantId.IsSet() {
		toSerialize["tenantId"] = o.TenantId.Get()
	}
	return toSerialize, nil
}

func (o *PolicyRevision) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"createdBy",
		"digest",
		"document",
		"revision",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPolicyRevision := _PolicyRevision{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPolicyRevision)

	if err != nil {
		return err
	}

	*o = PolicyRevision(varPolicyRevision)

	return err
}

type NullablePolicyRevision struct {
	value *PolicyRevision
	isSet bool
}

func (v NullablePolicyRevision) Get() *PolicyRevision {
	return v.value
}

func (v *NullablePolicyRevision) Set(val *PolicyRevision) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyRevision) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyRevision) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyRevision(val *PolicyRevision) *NullablePolicyRevision {
	return &NullablePolicyRevision{value: val, isSet: true}
}

func (v NullablePolicyRevision) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyRevision) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
