/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AgentResolutionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentResolutionRequest{}

// AgentResolutionRequest struct for AgentResolutionRequest
type AgentResolutionRequest struct {
	AgentRevision int32  `json:"agentRevision"`
	SubjectRef    string `json:"subjectRef"`
}

type _AgentResolutionRequest AgentResolutionRequest

// NewAgentResolutionRequest instantiates a new AgentResolutionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentResolutionRequest(agentRevision int32, subjectRef string) *AgentResolutionRequest {
	this := AgentResolutionRequest{}
	this.AgentRevision = agentRevision
	this.SubjectRef = subjectRef
	return &this
}

// NewAgentResolutionRequestWithDefaults instantiates a new AgentResolutionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentResolutionRequestWithDefaults() *AgentResolutionRequest {
	this := AgentResolutionRequest{}
	return &this
}

// GetAgentRevision returns the AgentRevision field value
func (o *AgentResolutionRequest) GetAgentRevision() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AgentRevision
}

// GetAgentRevisionOk returns a tuple with the AgentRevision field value
// and a boolean to check if the value has been set.
func (o *AgentResolutionRequest) GetAgentRevisionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentRevision, true
}

// SetAgentRevision sets field value
func (o *AgentResolutionRequest) SetAgentRevision(v int32) {
	o.AgentRevision = v
}

// GetSubjectRef returns the SubjectRef field value
func (o *AgentResolutionRequest) GetSubjectRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubjectRef
}

// GetSubjectRefOk returns a tuple with the SubjectRef field value
// and a boolean to check if the value has been set.
func (o *AgentResolutionRequest) GetSubjectRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubjectRef, true
}

// SetSubjectRef sets field value
func (o *AgentResolutionRequest) SetSubjectRef(v string) {
	o.SubjectRef = v
}

func (o AgentResolutionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentResolutionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agentRevision"] = o.AgentRevision
	toSerialize["subjectRef"] = o.SubjectRef
	return toSerialize, nil
}

func (o *AgentResolutionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"agentRevision",
		"subjectRef",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentResolutionRequest := _AgentResolutionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentResolutionRequest)

	if err != nil {
		return err
	}

	*o = AgentResolutionRequest(varAgentResolutionRequest)

	return err
}

type NullableAgentResolutionRequest struct {
	value *AgentResolutionRequest
	isSet bool
}

func (v NullableAgentResolutionRequest) Get() *AgentResolutionRequest {
	return v.value
}

func (v *NullableAgentResolutionRequest) Set(val *AgentResolutionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentResolutionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentResolutionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentResolutionRequest(val *AgentResolutionRequest) *NullableAgentResolutionRequest {
	return &NullableAgentResolutionRequest{value: val, isSet: true}
}

func (v NullableAgentResolutionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentResolutionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
