/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AgentMemoryMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentMemoryMetadata{}

// AgentMemoryMetadata struct for AgentMemoryMetadata
type AgentMemoryMetadata struct {
	AgentKey string `json:"agentKey"`
	AgentRevision int32 `json:"agentRevision"`
	ByteSize int32 `json:"byteSize"`
	ContentDigest string `json:"contentDigest" validate:"regexp=^sha256:[0-9a-f]{64}$"`
	CreatedAt time.Time `json:"createdAt"`
	EntryId string `json:"entryId"`
	ExecutionId NullableString `json:"executionId"`
	ExpiresAt time.Time `json:"expiresAt"`
	Key string `json:"key"`
	Namespace string `json:"namespace"`
	Provenance map[string]interface{} `json:"provenance"`
	Redacted bool `json:"redacted"`
	Scope AgentMemoryScope `json:"scope"`
	SharedScope NullableString `json:"sharedScope"`
	TenantId string `json:"tenantId"`
	UpdatedAt time.Time `json:"updatedAt"`
	Version int32 `json:"version"`
}

type _AgentMemoryMetadata AgentMemoryMetadata

// NewAgentMemoryMetadata instantiates a new AgentMemoryMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentMemoryMetadata(agentKey string, agentRevision int32, byteSize int32, contentDigest string, createdAt time.Time, entryId string, executionId NullableString, expiresAt time.Time, key string, namespace string, provenance map[string]interface{}, redacted bool, scope AgentMemoryScope, sharedScope NullableString, tenantId string, updatedAt time.Time, version int32) *AgentMemoryMetadata {
	this := AgentMemoryMetadata{}
	this.AgentKey = agentKey
	this.AgentRevision = agentRevision
	this.ByteSize = byteSize
	this.ContentDigest = contentDigest
	this.CreatedAt = createdAt
	this.EntryId = entryId
	this.ExecutionId = executionId
	this.ExpiresAt = expiresAt
	this.Key = key
	this.Namespace = namespace
	this.Provenance = provenance
	this.Redacted = redacted
	this.Scope = scope
	this.SharedScope = sharedScope
	this.TenantId = tenantId
	this.UpdatedAt = updatedAt
	this.Version = version
	return &this
}

// NewAgentMemoryMetadataWithDefaults instantiates a new AgentMemoryMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentMemoryMetadataWithDefaults() *AgentMemoryMetadata {
	this := AgentMemoryMetadata{}
	return &this
}

// GetAgentKey returns the AgentKey field value
func (o *AgentMemoryMetadata) GetAgentKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentKey
}

// GetAgentKeyOk returns a tuple with the AgentKey field value
// and a boolean to check if the value has been set.
func (o *AgentMemoryMetadata) GetAgentKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentKey, true
}

// SetAgentKey sets field value
func (o *AgentMemoryMetadata) SetAgentKey(v string) {
	o.AgentKey = v
}

// GetAgentRevision returns the AgentRevision field value
func (o *AgentMemoryMetadata) GetAgentRevision() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AgentRevision
}

// GetAgentRevisionOk returns a tuple with the AgentRevision field value
// and a boolean to check if the value has been set.
func (o *AgentMemoryMetadata) GetAgentRevisionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentRevision, true
}

// SetAgentRevision sets field value
func (o *AgentMemoryMetadata) SetAgentRevision(v int32) {
	o.AgentRevision = v
}

// GetByteSize returns the ByteSize field value
func (o *AgentMemoryMetadata) GetByteSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ByteSize
}

// GetByteSizeOk returns a tuple with the ByteSize field value
// and a boolean to check if the value has been set.
func (o *AgentMemoryMetadata) GetByteSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ByteSize, true
}

// SetByteSize sets field value
func (o *AgentMemoryMetadata) SetByteSize(v int32) {
	o.ByteSize = v
}

// GetContentDigest returns the ContentDigest field value
func (o *AgentMemoryMetadata) GetContentDigest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentDigest
}

// GetContentDigestOk returns a tuple with the ContentDigest field value
// and a boolean to check if the value has been set.
func (o *AgentMemoryMetadata) GetContentDigestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentDigest, true
}

// SetContentDigest sets field value
func (o *AgentMemoryMetadata) SetContentDigest(v string) {
	o.ContentDigest = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AgentMemoryMetadata) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AgentMemoryMetadata) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AgentMemoryMetadata) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetEntryId returns the EntryId field value
func (o *AgentMemoryMetadata) GetEntryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntryId
}

// GetEntryIdOk returns a tuple with the EntryId field value
// and a boolean to check if the value has been set.
func (o *AgentMemoryMetadata) GetEntryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntryId, true
}

// SetEntryId sets field value
func (o *AgentMemoryMetadata) SetEntryId(v string) {
	o.EntryId = v
}

// GetExecutionId returns the ExecutionId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AgentMemoryMetadata) GetExecutionId() string {
	if o == nil || o.ExecutionId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ExecutionId.Get()
}

// GetExecutionIdOk returns a tuple with the ExecutionId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentMemoryMetadata) GetExecutionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExecutionId.Get(), o.ExecutionId.IsSet()
}

// SetExecutionId sets field value
func (o *AgentMemoryMetadata) SetExecutionId(v string) {
	o.ExecutionId.Set(&v)
}

// GetExpiresAt returns the ExpiresAt field value
func (o *AgentMemoryMetadata) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *AgentMemoryMetadata) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *AgentMemoryMetadata) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetKey returns the Key field value
func (o *AgentMemoryMetadata) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *AgentMemoryMetadata) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *AgentMemoryMetadata) SetKey(v string) {
	o.Key = v
}

// GetNamespace returns the Namespace field value
func (o *AgentMemoryMetadata) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *AgentMemoryMetadata) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *AgentMemoryMetadata) SetNamespace(v string) {
	o.Namespace = v
}

// GetProvenance returns the Provenance field value
func (o *AgentMemoryMetadata) GetProvenance() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Provenance
}

// GetProvenanceOk returns a tuple with the Provenance field value
// and a boolean to check if the value has been set.
func (o *AgentMemoryMetadata) GetProvenanceOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Provenance, true
}

// SetProvenance sets field value
func (o *AgentMemoryMetadata) SetProvenance(v map[string]interface{}) {
	o.Provenance = v
}

// GetRedacted returns the Redacted field value
func (o *AgentMemoryMetadata) GetRedacted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Redacted
}

// GetRedactedOk returns a tuple with the Redacted field value
// and a boolean to check if the value has been set.
func (o *AgentMemoryMetadata) GetRedactedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Redacted, true
}

// SetRedacted sets field value
func (o *AgentMemoryMetadata) SetRedacted(v bool) {
	o.Redacted = v
}

// GetScope returns the Scope field value
func (o *AgentMemoryMetadata) GetScope() AgentMemoryScope {
	if o == nil {
		var ret AgentMemoryScope
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *AgentMemoryMetadata) GetScopeOk() (*AgentMemoryScope, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *AgentMemoryMetadata) SetScope(v AgentMemoryScope) {
	o.Scope = v
}

// GetSharedScope returns the SharedScope field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AgentMemoryMetadata) GetSharedScope() string {
	if o == nil || o.SharedScope.Get() == nil {
		var ret string
		return ret
	}

	return *o.SharedScope.Get()
}

// GetSharedScopeOk returns a tuple with the SharedScope field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentMemoryMetadata) GetSharedScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SharedScope.Get(), o.SharedScope.IsSet()
}

// SetSharedScope sets field value
func (o *AgentMemoryMetadata) SetSharedScope(v string) {
	o.SharedScope.Set(&v)
}

// GetTenantId returns the TenantId field value
func (o *AgentMemoryMetadata) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *AgentMemoryMetadata) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *AgentMemoryMetadata) SetTenantId(v string) {
	o.TenantId = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *AgentMemoryMetadata) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *AgentMemoryMetadata) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *AgentMemoryMetadata) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetVersion returns the Version field value
func (o *AgentMemoryMetadata) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *AgentMemoryMetadata) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *AgentMemoryMetadata) SetVersion(v int32) {
	o.Version = v
}

func (o AgentMemoryMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentMemoryMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agentKey"] = o.AgentKey
	toSerialize["agentRevision"] = o.AgentRevision
	toSerialize["byteSize"] = o.ByteSize
	toSerialize["contentDigest"] = o.ContentDigest
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["entryId"] = o.EntryId
	toSerialize["executionId"] = o.ExecutionId.Get()
	toSerialize["expiresAt"] = o.ExpiresAt
	toSerialize["key"] = o.Key
	toSerialize["namespace"] = o.Namespace
	toSerialize["provenance"] = o.Provenance
	toSerialize["redacted"] = o.Redacted
	toSerialize["scope"] = o.Scope
	toSerialize["sharedScope"] = o.SharedScope.Get()
	toSerialize["tenantId"] = o.TenantId
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *AgentMemoryMetadata) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"agentKey",
		"agentRevision",
		"byteSize",
		"contentDigest",
		"createdAt",
		"entryId",
		"executionId",
		"expiresAt",
		"key",
		"namespace",
		"provenance",
		"redacted",
		"scope",
		"sharedScope",
		"tenantId",
		"updatedAt",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentMemoryMetadata := _AgentMemoryMetadata{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentMemoryMetadata)

	if err != nil {
		return err
	}

	*o = AgentMemoryMetadata(varAgentMemoryMetadata)

	return err
}

type NullableAgentMemoryMetadata struct {
	value *AgentMemoryMetadata
	isSet bool
}

func (v NullableAgentMemoryMetadata) Get() *AgentMemoryMetadata {
	return v.value
}

func (v *NullableAgentMemoryMetadata) Set(val *AgentMemoryMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentMemoryMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentMemoryMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentMemoryMetadata(val *AgentMemoryMetadata) *NullableAgentMemoryMetadata {
	return &NullableAgentMemoryMetadata{value: val, isSet: true}
}

func (v NullableAgentMemoryMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentMemoryMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
