/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AgentProgressPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentProgressPage{}

// AgentProgressPage Cursor-bound page from the canonical cross-attempt session timeline.
type AgentProgressPage struct {
	Events     []AgentProgressEvent `json:"events"`
	NextCursor string               `json:"nextCursor"`
	SessionId  string               `json:"sessionId"`
}

type _AgentProgressPage AgentProgressPage

// NewAgentProgressPage instantiates a new AgentProgressPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentProgressPage(events []AgentProgressEvent, nextCursor string, sessionId string) *AgentProgressPage {
	this := AgentProgressPage{}
	this.Events = events
	this.NextCursor = nextCursor
	this.SessionId = sessionId
	return &this
}

// NewAgentProgressPageWithDefaults instantiates a new AgentProgressPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentProgressPageWithDefaults() *AgentProgressPage {
	this := AgentProgressPage{}
	return &this
}

// GetEvents returns the Events field value
func (o *AgentProgressPage) GetEvents() []AgentProgressEvent {
	if o == nil {
		var ret []AgentProgressEvent
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *AgentProgressPage) GetEventsOk() ([]AgentProgressEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *AgentProgressPage) SetEvents(v []AgentProgressEvent) {
	o.Events = v
}

// GetNextCursor returns the NextCursor field value
func (o *AgentProgressPage) GetNextCursor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value
// and a boolean to check if the value has been set.
func (o *AgentProgressPage) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextCursor, true
}

// SetNextCursor sets field value
func (o *AgentProgressPage) SetNextCursor(v string) {
	o.NextCursor = v
}

// GetSessionId returns the SessionId field value
func (o *AgentProgressPage) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *AgentProgressPage) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *AgentProgressPage) SetSessionId(v string) {
	o.SessionId = v
}

func (o AgentProgressPage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentProgressPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	toSerialize["nextCursor"] = o.NextCursor
	toSerialize["sessionId"] = o.SessionId
	return toSerialize, nil
}

func (o *AgentProgressPage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
		"nextCursor",
		"sessionId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentProgressPage := _AgentProgressPage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentProgressPage)

	if err != nil {
		return err
	}

	*o = AgentProgressPage(varAgentProgressPage)

	return err
}

type NullableAgentProgressPage struct {
	value *AgentProgressPage
	isSet bool
}

func (v NullableAgentProgressPage) Get() *AgentProgressPage {
	return v.value
}

func (v *NullableAgentProgressPage) Set(val *AgentProgressPage) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentProgressPage) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentProgressPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentProgressPage(val *AgentProgressPage) *NullableAgentProgressPage {
	return &NullableAgentProgressPage{value: val, isSet: true}
}

func (v NullableAgentProgressPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentProgressPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
