/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the NamespaceCheckPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NamespaceCheckPolicy{}

// NamespaceCheckPolicy struct for NamespaceCheckPolicy
type NamespaceCheckPolicy struct {
	CreatedAt time.Time `json:"created_at"`
	Definition CheckDefinition `json:"definition"`
	Enabled bool `json:"enabled"`
	Namespace string `json:"namespace"`
	PolicyId string `json:"policy_id"`
	PolicyKey string `json:"policy_key"`
	Source CheckPolicySource `json:"source"`
	TaskType NullableString `json:"task_type,omitempty"`
	TenantId string `json:"tenant_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

type _NamespaceCheckPolicy NamespaceCheckPolicy

// NewNamespaceCheckPolicy instantiates a new NamespaceCheckPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNamespaceCheckPolicy(createdAt time.Time, definition CheckDefinition, enabled bool, namespace string, policyId string, policyKey string, source CheckPolicySource, tenantId string, updatedAt time.Time) *NamespaceCheckPolicy {
	this := NamespaceCheckPolicy{}
	this.CreatedAt = createdAt
	this.Definition = definition
	this.Enabled = enabled
	this.Namespace = namespace
	this.PolicyId = policyId
	this.PolicyKey = policyKey
	this.Source = source
	this.TenantId = tenantId
	this.UpdatedAt = updatedAt
	return &this
}

// NewNamespaceCheckPolicyWithDefaults instantiates a new NamespaceCheckPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNamespaceCheckPolicyWithDefaults() *NamespaceCheckPolicy {
	this := NamespaceCheckPolicy{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *NamespaceCheckPolicy) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *NamespaceCheckPolicy) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *NamespaceCheckPolicy) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetDefinition returns the Definition field value
func (o *NamespaceCheckPolicy) GetDefinition() CheckDefinition {
	if o == nil {
		var ret CheckDefinition
		return ret
	}

	return o.Definition
}

// GetDefinitionOk returns a tuple with the Definition field value
// and a boolean to check if the value has been set.
func (o *NamespaceCheckPolicy) GetDefinitionOk() (*CheckDefinition, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Definition, true
}

// SetDefinition sets field value
func (o *NamespaceCheckPolicy) SetDefinition(v CheckDefinition) {
	o.Definition = v
}

// GetEnabled returns the Enabled field value
func (o *NamespaceCheckPolicy) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *NamespaceCheckPolicy) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *NamespaceCheckPolicy) SetEnabled(v bool) {
	o.Enabled = v
}

// GetNamespace returns the Namespace field value
func (o *NamespaceCheckPolicy) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *NamespaceCheckPolicy) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *NamespaceCheckPolicy) SetNamespace(v string) {
	o.Namespace = v
}

// GetPolicyId returns the PolicyId field value
func (o *NamespaceCheckPolicy) GetPolicyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PolicyId
}

// GetPolicyIdOk returns a tuple with the PolicyId field value
// and a boolean to check if the value has been set.
func (o *NamespaceCheckPolicy) GetPolicyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PolicyId, true
}

// SetPolicyId sets field value
func (o *NamespaceCheckPolicy) SetPolicyId(v string) {
	o.PolicyId = v
}

// GetPolicyKey returns the PolicyKey field value
func (o *NamespaceCheckPolicy) GetPolicyKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PolicyKey
}

// GetPolicyKeyOk returns a tuple with the PolicyKey field value
// and a boolean to check if the value has been set.
func (o *NamespaceCheckPolicy) GetPolicyKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PolicyKey, true
}

// SetPolicyKey sets field value
func (o *NamespaceCheckPolicy) SetPolicyKey(v string) {
	o.PolicyKey = v
}

// GetSource returns the Source field value
func (o *NamespaceCheckPolicy) GetSource() CheckPolicySource {
	if o == nil {
		var ret CheckPolicySource
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *NamespaceCheckPolicy) GetSourceOk() (*CheckPolicySource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *NamespaceCheckPolicy) SetSource(v CheckPolicySource) {
	o.Source = v
}

// GetTaskType returns the TaskType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NamespaceCheckPolicy) GetTaskType() string {
	if o == nil || IsNil(o.TaskType.Get()) {
		var ret string
		return ret
	}
	return *o.TaskType.Get()
}

// GetTaskTypeOk returns a tuple with the TaskType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NamespaceCheckPolicy) GetTaskTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TaskType.Get(), o.TaskType.IsSet()
}

// HasTaskType returns a boolean if a field has been set.
func (o *NamespaceCheckPolicy) HasTaskType() bool {
	if o != nil && o.TaskType.IsSet() {
		return true
	}

	return false
}

// SetTaskType gets a reference to the given NullableString and assigns it to the TaskType field.
func (o *NamespaceCheckPolicy) SetTaskType(v string) {
	o.TaskType.Set(&v)
}
// SetTaskTypeNil sets the value for TaskType to be an explicit nil
func (o *NamespaceCheckPolicy) SetTaskTypeNil() {
	o.TaskType.Set(nil)
}

// UnsetTaskType ensures that no value is present for TaskType, not even an explicit nil
func (o *NamespaceCheckPolicy) UnsetTaskType() {
	o.TaskType.Unset()
}

// GetTenantId returns the TenantId field value
func (o *NamespaceCheckPolicy) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *NamespaceCheckPolicy) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *NamespaceCheckPolicy) SetTenantId(v string) {
	o.TenantId = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *NamespaceCheckPolicy) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *NamespaceCheckPolicy) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *NamespaceCheckPolicy) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o NamespaceCheckPolicy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NamespaceCheckPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["definition"] = o.Definition
	toSerialize["enabled"] = o.Enabled
	toSerialize["namespace"] = o.Namespace
	toSerialize["policy_id"] = o.PolicyId
	toSerialize["policy_key"] = o.PolicyKey
	toSerialize["source"] = o.Source
	if o.TaskType.IsSet() {
		toSerialize["task_type"] = o.TaskType.Get()
	}
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *NamespaceCheckPolicy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"definition",
		"enabled",
		"namespace",
		"policy_id",
		"policy_key",
		"source",
		"tenant_id",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNamespaceCheckPolicy := _NamespaceCheckPolicy{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNamespaceCheckPolicy)

	if err != nil {
		return err
	}

	*o = NamespaceCheckPolicy(varNamespaceCheckPolicy)

	return err
}

type NullableNamespaceCheckPolicy struct {
	value *NamespaceCheckPolicy
	isSet bool
}

func (v NullableNamespaceCheckPolicy) Get() *NamespaceCheckPolicy {
	return v.value
}

func (v *NullableNamespaceCheckPolicy) Set(val *NamespaceCheckPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableNamespaceCheckPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableNamespaceCheckPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNamespaceCheckPolicy(val *NamespaceCheckPolicy) *NullableNamespaceCheckPolicy {
	return &NullableNamespaceCheckPolicy{value: val, isSet: true}
}

func (v NullableNamespaceCheckPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNamespaceCheckPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
