/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EvidenceBundlePageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EvidenceBundlePageResponse{}

// EvidenceBundlePageResponse Bounded canonical bundle projection returned by REST and SDK clients.
type EvidenceBundlePageResponse struct {
	BundleDigest  string           `json:"bundleDigest"`
	ExecutionId   string           `json:"executionId"`
	Items         []EvidenceRecord `json:"items"`
	Limit         int32            `json:"limit"`
	NextCursor    NullableString   `json:"nextCursor,omitempty"`
	SchemaVersion string           `json:"schemaVersion"`
	Section       string           `json:"section"`
	Total         int32            `json:"total"`
}

type _EvidenceBundlePageResponse EvidenceBundlePageResponse

// NewEvidenceBundlePageResponse instantiates a new EvidenceBundlePageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEvidenceBundlePageResponse(bundleDigest string, executionId string, items []EvidenceRecord, limit int32, schemaVersion string, section string, total int32) *EvidenceBundlePageResponse {
	this := EvidenceBundlePageResponse{}
	this.BundleDigest = bundleDigest
	this.ExecutionId = executionId
	this.Items = items
	this.Limit = limit
	this.SchemaVersion = schemaVersion
	this.Section = section
	this.Total = total
	return &this
}

// NewEvidenceBundlePageResponseWithDefaults instantiates a new EvidenceBundlePageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEvidenceBundlePageResponseWithDefaults() *EvidenceBundlePageResponse {
	this := EvidenceBundlePageResponse{}
	return &this
}

// GetBundleDigest returns the BundleDigest field value
func (o *EvidenceBundlePageResponse) GetBundleDigest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BundleDigest
}

// GetBundleDigestOk returns a tuple with the BundleDigest field value
// and a boolean to check if the value has been set.
func (o *EvidenceBundlePageResponse) GetBundleDigestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BundleDigest, true
}

// SetBundleDigest sets field value
func (o *EvidenceBundlePageResponse) SetBundleDigest(v string) {
	o.BundleDigest = v
}

// GetExecutionId returns the ExecutionId field value
func (o *EvidenceBundlePageResponse) GetExecutionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExecutionId
}

// GetExecutionIdOk returns a tuple with the ExecutionId field value
// and a boolean to check if the value has been set.
func (o *EvidenceBundlePageResponse) GetExecutionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExecutionId, true
}

// SetExecutionId sets field value
func (o *EvidenceBundlePageResponse) SetExecutionId(v string) {
	o.ExecutionId = v
}

// GetItems returns the Items field value
func (o *EvidenceBundlePageResponse) GetItems() []EvidenceRecord {
	if o == nil {
		var ret []EvidenceRecord
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *EvidenceBundlePageResponse) GetItemsOk() ([]EvidenceRecord, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *EvidenceBundlePageResponse) SetItems(v []EvidenceRecord) {
	o.Items = v
}

// GetLimit returns the Limit field value
func (o *EvidenceBundlePageResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *EvidenceBundlePageResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *EvidenceBundlePageResponse) SetLimit(v int32) {
	o.Limit = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EvidenceBundlePageResponse) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor.Get()) {
		var ret string
		return ret
	}
	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EvidenceBundlePageResponse) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// HasNextCursor returns a boolean if a field has been set.
func (o *EvidenceBundlePageResponse) HasNextCursor() bool {
	if o != nil && o.NextCursor.IsSet() {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given NullableString and assigns it to the NextCursor field.
func (o *EvidenceBundlePageResponse) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}

// SetNextCursorNil sets the value for NextCursor to be an explicit nil
func (o *EvidenceBundlePageResponse) SetNextCursorNil() {
	o.NextCursor.Set(nil)
}

// UnsetNextCursor ensures that no value is present for NextCursor, not even an explicit nil
func (o *EvidenceBundlePageResponse) UnsetNextCursor() {
	o.NextCursor.Unset()
}

// GetSchemaVersion returns the SchemaVersion field value
func (o *EvidenceBundlePageResponse) GetSchemaVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value
// and a boolean to check if the value has been set.
func (o *EvidenceBundlePageResponse) GetSchemaVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SchemaVersion, true
}

// SetSchemaVersion sets field value
func (o *EvidenceBundlePageResponse) SetSchemaVersion(v string) {
	o.SchemaVersion = v
}

// GetSection returns the Section field value
func (o *EvidenceBundlePageResponse) GetSection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Section
}

// GetSectionOk returns a tuple with the Section field value
// and a boolean to check if the value has been set.
func (o *EvidenceBundlePageResponse) GetSectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Section, true
}

// SetSection sets field value
func (o *EvidenceBundlePageResponse) SetSection(v string) {
	o.Section = v
}

// GetTotal returns the Total field value
func (o *EvidenceBundlePageResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *EvidenceBundlePageResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *EvidenceBundlePageResponse) SetTotal(v int32) {
	o.Total = v
}

func (o EvidenceBundlePageResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EvidenceBundlePageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bundleDigest"] = o.BundleDigest
	toSerialize["executionId"] = o.ExecutionId
	toSerialize["items"] = o.Items
	toSerialize["limit"] = o.Limit
	if o.NextCursor.IsSet() {
		toSerialize["nextCursor"] = o.NextCursor.Get()
	}
	toSerialize["schemaVersion"] = o.SchemaVersion
	toSerialize["section"] = o.Section
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *EvidenceBundlePageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bundleDigest",
		"executionId",
		"items",
		"limit",
		"schemaVersion",
		"section",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEvidenceBundlePageResponse := _EvidenceBundlePageResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEvidenceBundlePageResponse)

	if err != nil {
		return err
	}

	*o = EvidenceBundlePageResponse(varEvidenceBundlePageResponse)

	return err
}

type NullableEvidenceBundlePageResponse struct {
	value *EvidenceBundlePageResponse
	isSet bool
}

func (v NullableEvidenceBundlePageResponse) Get() *EvidenceBundlePageResponse {
	return v.value
}

func (v *NullableEvidenceBundlePageResponse) Set(val *EvidenceBundlePageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEvidenceBundlePageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEvidenceBundlePageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEvidenceBundlePageResponse(val *EvidenceBundlePageResponse) *NullableEvidenceBundlePageResponse {
	return &NullableEvidenceBundlePageResponse{value: val, isSet: true}
}

func (v NullableEvidenceBundlePageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEvidenceBundlePageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
