/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the AgentSessionRecordOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentSessionRecordOutput{}

// AgentSessionRecordOutput struct for AgentSessionRecordOutput
type AgentSessionRecordOutput struct {
	Attempt         int32                       `json:"attempt"`
	CapabilityPinId string                      `json:"capabilityPinId"`
	Checkpoint      *AgentSessionCheckpoint     `json:"checkpoint,omitempty"`
	CompletedAt     NullableTime                `json:"completedAt,omitempty"`
	Counters        *AgentSessionCountersOutput `json:"counters,omitempty"`
	CreatedAt       *time.Time                  `json:"createdAt,omitempty"`
	EnvelopeDigest  string                      `json:"envelopeDigest" validate:"regexp=^sha256:[0-9a-f]{64}$"`
	Error           NullableString              `json:"error,omitempty"`
	ExecutionId     string                      `json:"executionId"`
	FinalResult     map[string]interface{}      `json:"finalResult,omitempty"`
	Harness         NullableAgentHarnessPin     `json:"harness,omitempty"`
	Namespace       string                      `json:"namespace"`
	Phase           *AgentSessionPhase          `json:"phase,omitempty"`
	SessionId       *string                     `json:"sessionId,omitempty"`
	State           *AgentSessionState          `json:"state,omitempty"`
	TaskRunId       string                      `json:"taskRunId"`
	TenantId        string                      `json:"tenantId"`
	UpdatedAt       *time.Time                  `json:"updatedAt,omitempty"`
	Version         *int32                      `json:"version,omitempty"`
}

type _AgentSessionRecordOutput AgentSessionRecordOutput

// NewAgentSessionRecordOutput instantiates a new AgentSessionRecordOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentSessionRecordOutput(attempt int32, capabilityPinId string, envelopeDigest string, executionId string, namespace string, taskRunId string, tenantId string) *AgentSessionRecordOutput {
	this := AgentSessionRecordOutput{}
	this.Attempt = attempt
	this.CapabilityPinId = capabilityPinId
	this.EnvelopeDigest = envelopeDigest
	this.ExecutionId = executionId
	this.Namespace = namespace
	var phase AgentSessionPhase = AGENTSESSIONPHASE_READY
	this.Phase = &phase
	var state AgentSessionState = AGENTSESSIONSTATE_RUNNING
	this.State = &state
	this.TaskRunId = taskRunId
	this.TenantId = tenantId
	var version int32 = 0
	this.Version = &version
	return &this
}

// NewAgentSessionRecordOutputWithDefaults instantiates a new AgentSessionRecordOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentSessionRecordOutputWithDefaults() *AgentSessionRecordOutput {
	this := AgentSessionRecordOutput{}
	var phase AgentSessionPhase = AGENTSESSIONPHASE_READY
	this.Phase = &phase
	var state AgentSessionState = AGENTSESSIONSTATE_RUNNING
	this.State = &state
	var version int32 = 0
	this.Version = &version
	return &this
}

// GetAttempt returns the Attempt field value
func (o *AgentSessionRecordOutput) GetAttempt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Attempt
}

// GetAttemptOk returns a tuple with the Attempt field value
// and a boolean to check if the value has been set.
func (o *AgentSessionRecordOutput) GetAttemptOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attempt, true
}

// SetAttempt sets field value
func (o *AgentSessionRecordOutput) SetAttempt(v int32) {
	o.Attempt = v
}

// GetCapabilityPinId returns the CapabilityPinId field value
func (o *AgentSessionRecordOutput) GetCapabilityPinId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CapabilityPinId
}

// GetCapabilityPinIdOk returns a tuple with the CapabilityPinId field value
// and a boolean to check if the value has been set.
func (o *AgentSessionRecordOutput) GetCapabilityPinIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CapabilityPinId, true
}

// SetCapabilityPinId sets field value
func (o *AgentSessionRecordOutput) SetCapabilityPinId(v string) {
	o.CapabilityPinId = v
}

// GetCheckpoint returns the Checkpoint field value if set, zero value otherwise.
func (o *AgentSessionRecordOutput) GetCheckpoint() AgentSessionCheckpoint {
	if o == nil || IsNil(o.Checkpoint) {
		var ret AgentSessionCheckpoint
		return ret
	}
	return *o.Checkpoint
}

// GetCheckpointOk returns a tuple with the Checkpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentSessionRecordOutput) GetCheckpointOk() (*AgentSessionCheckpoint, bool) {
	if o == nil || IsNil(o.Checkpoint) {
		return nil, false
	}
	return o.Checkpoint, true
}

// HasCheckpoint returns a boolean if a field has been set.
func (o *AgentSessionRecordOutput) HasCheckpoint() bool {
	if o != nil && !IsNil(o.Checkpoint) {
		return true
	}

	return false
}

// SetCheckpoint gets a reference to the given AgentSessionCheckpoint and assigns it to the Checkpoint field.
func (o *AgentSessionRecordOutput) SetCheckpoint(v AgentSessionCheckpoint) {
	o.Checkpoint = &v
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentSessionRecordOutput) GetCompletedAt() time.Time {
	if o == nil || IsNil(o.CompletedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentSessionRecordOutput) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *AgentSessionRecordOutput) HasCompletedAt() bool {
	if o != nil && o.CompletedAt.IsSet() {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given NullableTime and assigns it to the CompletedAt field.
func (o *AgentSessionRecordOutput) SetCompletedAt(v time.Time) {
	o.CompletedAt.Set(&v)
}

// SetCompletedAtNil sets the value for CompletedAt to be an explicit nil
func (o *AgentSessionRecordOutput) SetCompletedAtNil() {
	o.CompletedAt.Set(nil)
}

// UnsetCompletedAt ensures that no value is present for CompletedAt, not even an explicit nil
func (o *AgentSessionRecordOutput) UnsetCompletedAt() {
	o.CompletedAt.Unset()
}

// GetCounters returns the Counters field value if set, zero value otherwise.
func (o *AgentSessionRecordOutput) GetCounters() AgentSessionCountersOutput {
	if o == nil || IsNil(o.Counters) {
		var ret AgentSessionCountersOutput
		return ret
	}
	return *o.Counters
}

// GetCountersOk returns a tuple with the Counters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentSessionRecordOutput) GetCountersOk() (*AgentSessionCountersOutput, bool) {
	if o == nil || IsNil(o.Counters) {
		return nil, false
	}
	return o.Counters, true
}

// HasCounters returns a boolean if a field has been set.
func (o *AgentSessionRecordOutput) HasCounters() bool {
	if o != nil && !IsNil(o.Counters) {
		return true
	}

	return false
}

// SetCounters gets a reference to the given AgentSessionCountersOutput and assigns it to the Counters field.
func (o *AgentSessionRecordOutput) SetCounters(v AgentSessionCountersOutput) {
	o.Counters = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *AgentSessionRecordOutput) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentSessionRecordOutput) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AgentSessionRecordOutput) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *AgentSessionRecordOutput) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetEnvelopeDigest returns the EnvelopeDigest field value
func (o *AgentSessionRecordOutput) GetEnvelopeDigest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvelopeDigest
}

// GetEnvelopeDigestOk returns a tuple with the EnvelopeDigest field value
// and a boolean to check if the value has been set.
func (o *AgentSessionRecordOutput) GetEnvelopeDigestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvelopeDigest, true
}

// SetEnvelopeDigest sets field value
func (o *AgentSessionRecordOutput) SetEnvelopeDigest(v string) {
	o.EnvelopeDigest = v
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentSessionRecordOutput) GetError() string {
	if o == nil || IsNil(o.Error.Get()) {
		var ret string
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentSessionRecordOutput) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *AgentSessionRecordOutput) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableString and assigns it to the Error field.
func (o *AgentSessionRecordOutput) SetError(v string) {
	o.Error.Set(&v)
}

// SetErrorNil sets the value for Error to be an explicit nil
func (o *AgentSessionRecordOutput) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *AgentSessionRecordOutput) UnsetError() {
	o.Error.Unset()
}

// GetExecutionId returns the ExecutionId field value
func (o *AgentSessionRecordOutput) GetExecutionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExecutionId
}

// GetExecutionIdOk returns a tuple with the ExecutionId field value
// and a boolean to check if the value has been set.
func (o *AgentSessionRecordOutput) GetExecutionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExecutionId, true
}

// SetExecutionId sets field value
func (o *AgentSessionRecordOutput) SetExecutionId(v string) {
	o.ExecutionId = v
}

// GetFinalResult returns the FinalResult field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentSessionRecordOutput) GetFinalResult() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.FinalResult
}

// GetFinalResultOk returns a tuple with the FinalResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentSessionRecordOutput) GetFinalResultOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.FinalResult) {
		return map[string]interface{}{}, false
	}
	return o.FinalResult, true
}

// HasFinalResult returns a boolean if a field has been set.
func (o *AgentSessionRecordOutput) HasFinalResult() bool {
	if o != nil && !IsNil(o.FinalResult) {
		return true
	}

	return false
}

// SetFinalResult gets a reference to the given map[string]interface{} and assigns it to the FinalResult field.
func (o *AgentSessionRecordOutput) SetFinalResult(v map[string]interface{}) {
	o.FinalResult = v
}

// GetHarness returns the Harness field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentSessionRecordOutput) GetHarness() AgentHarnessPin {
	if o == nil || IsNil(o.Harness.Get()) {
		var ret AgentHarnessPin
		return ret
	}
	return *o.Harness.Get()
}

// GetHarnessOk returns a tuple with the Harness field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentSessionRecordOutput) GetHarnessOk() (*AgentHarnessPin, bool) {
	if o == nil {
		return nil, false
	}
	return o.Harness.Get(), o.Harness.IsSet()
}

// HasHarness returns a boolean if a field has been set.
func (o *AgentSessionRecordOutput) HasHarness() bool {
	if o != nil && o.Harness.IsSet() {
		return true
	}

	return false
}

// SetHarness gets a reference to the given NullableAgentHarnessPin and assigns it to the Harness field.
func (o *AgentSessionRecordOutput) SetHarness(v AgentHarnessPin) {
	o.Harness.Set(&v)
}

// SetHarnessNil sets the value for Harness to be an explicit nil
func (o *AgentSessionRecordOutput) SetHarnessNil() {
	o.Harness.Set(nil)
}

// UnsetHarness ensures that no value is present for Harness, not even an explicit nil
func (o *AgentSessionRecordOutput) UnsetHarness() {
	o.Harness.Unset()
}

// GetNamespace returns the Namespace field value
func (o *AgentSessionRecordOutput) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *AgentSessionRecordOutput) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *AgentSessionRecordOutput) SetNamespace(v string) {
	o.Namespace = v
}

// GetPhase returns the Phase field value if set, zero value otherwise.
func (o *AgentSessionRecordOutput) GetPhase() AgentSessionPhase {
	if o == nil || IsNil(o.Phase) {
		var ret AgentSessionPhase
		return ret
	}
	return *o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentSessionRecordOutput) GetPhaseOk() (*AgentSessionPhase, bool) {
	if o == nil || IsNil(o.Phase) {
		return nil, false
	}
	return o.Phase, true
}

// HasPhase returns a boolean if a field has been set.
func (o *AgentSessionRecordOutput) HasPhase() bool {
	if o != nil && !IsNil(o.Phase) {
		return true
	}

	return false
}

// SetPhase gets a reference to the given AgentSessionPhase and assigns it to the Phase field.
func (o *AgentSessionRecordOutput) SetPhase(v AgentSessionPhase) {
	o.Phase = &v
}

// GetSessionId returns the SessionId field value if set, zero value otherwise.
func (o *AgentSessionRecordOutput) GetSessionId() string {
	if o == nil || IsNil(o.SessionId) {
		var ret string
		return ret
	}
	return *o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentSessionRecordOutput) GetSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SessionId) {
		return nil, false
	}
	return o.SessionId, true
}

// HasSessionId returns a boolean if a field has been set.
func (o *AgentSessionRecordOutput) HasSessionId() bool {
	if o != nil && !IsNil(o.SessionId) {
		return true
	}

	return false
}

// SetSessionId gets a reference to the given string and assigns it to the SessionId field.
func (o *AgentSessionRecordOutput) SetSessionId(v string) {
	o.SessionId = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *AgentSessionRecordOutput) GetState() AgentSessionState {
	if o == nil || IsNil(o.State) {
		var ret AgentSessionState
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentSessionRecordOutput) GetStateOk() (*AgentSessionState, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *AgentSessionRecordOutput) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given AgentSessionState and assigns it to the State field.
func (o *AgentSessionRecordOutput) SetState(v AgentSessionState) {
	o.State = &v
}

// GetTaskRunId returns the TaskRunId field value
func (o *AgentSessionRecordOutput) GetTaskRunId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskRunId
}

// GetTaskRunIdOk returns a tuple with the TaskRunId field value
// and a boolean to check if the value has been set.
func (o *AgentSessionRecordOutput) GetTaskRunIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskRunId, true
}

// SetTaskRunId sets field value
func (o *AgentSessionRecordOutput) SetTaskRunId(v string) {
	o.TaskRunId = v
}

// GetTenantId returns the TenantId field value
func (o *AgentSessionRecordOutput) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *AgentSessionRecordOutput) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *AgentSessionRecordOutput) SetTenantId(v string) {
	o.TenantId = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *AgentSessionRecordOutput) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentSessionRecordOutput) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *AgentSessionRecordOutput) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *AgentSessionRecordOutput) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *AgentSessionRecordOutput) GetVersion() int32 {
	if o == nil || IsNil(o.Version) {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentSessionRecordOutput) GetVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *AgentSessionRecordOutput) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *AgentSessionRecordOutput) SetVersion(v int32) {
	o.Version = &v
}

func (o AgentSessionRecordOutput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentSessionRecordOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attempt"] = o.Attempt
	toSerialize["capabilityPinId"] = o.CapabilityPinId
	if !IsNil(o.Checkpoint) {
		toSerialize["checkpoint"] = o.Checkpoint
	}
	if o.CompletedAt.IsSet() {
		toSerialize["completedAt"] = o.CompletedAt.Get()
	}
	if !IsNil(o.Counters) {
		toSerialize["counters"] = o.Counters
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	toSerialize["envelopeDigest"] = o.EnvelopeDigest
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	toSerialize["executionId"] = o.ExecutionId
	if o.FinalResult != nil {
		toSerialize["finalResult"] = o.FinalResult
	}
	if o.Harness.IsSet() {
		toSerialize["harness"] = o.Harness.Get()
	}
	toSerialize["namespace"] = o.Namespace
	if !IsNil(o.Phase) {
		toSerialize["phase"] = o.Phase
	}
	if !IsNil(o.SessionId) {
		toSerialize["sessionId"] = o.SessionId
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	toSerialize["taskRunId"] = o.TaskRunId
	toSerialize["tenantId"] = o.TenantId
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

func (o *AgentSessionRecordOutput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attempt",
		"capabilityPinId",
		"envelopeDigest",
		"executionId",
		"namespace",
		"taskRunId",
		"tenantId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentSessionRecordOutput := _AgentSessionRecordOutput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentSessionRecordOutput)

	if err != nil {
		return err
	}

	*o = AgentSessionRecordOutput(varAgentSessionRecordOutput)

	return err
}

type NullableAgentSessionRecordOutput struct {
	value *AgentSessionRecordOutput
	isSet bool
}

func (v NullableAgentSessionRecordOutput) Get() *AgentSessionRecordOutput {
	return v.value
}

func (v *NullableAgentSessionRecordOutput) Set(val *AgentSessionRecordOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentSessionRecordOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentSessionRecordOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentSessionRecordOutput(val *AgentSessionRecordOutput) *NullableAgentSessionRecordOutput {
	return &NullableAgentSessionRecordOutput{value: val, isSet: true}
}

func (v NullableAgentSessionRecordOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentSessionRecordOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
