/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ModelEngineLogoutResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelEngineLogoutResponse{}

// ModelEngineLogoutResponse Safe acknowledgement for a local account logout command.
type ModelEngineLogoutResponse struct {
	ActionRequired *bool   `json:"actionRequired,omitempty"`
	Adapter        string  `json:"adapter"`
	EngineRef      string  `json:"engineRef"`
	Status         *string `json:"status,omitempty"`
}

type _ModelEngineLogoutResponse ModelEngineLogoutResponse

// NewModelEngineLogoutResponse instantiates a new ModelEngineLogoutResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelEngineLogoutResponse(adapter string, engineRef string) *ModelEngineLogoutResponse {
	this := ModelEngineLogoutResponse{}
	var actionRequired bool = false
	this.ActionRequired = &actionRequired
	this.Adapter = adapter
	this.EngineRef = engineRef
	var status string = "logged_out"
	this.Status = &status
	return &this
}

// NewModelEngineLogoutResponseWithDefaults instantiates a new ModelEngineLogoutResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelEngineLogoutResponseWithDefaults() *ModelEngineLogoutResponse {
	this := ModelEngineLogoutResponse{}
	var actionRequired bool = false
	this.ActionRequired = &actionRequired
	var status string = "logged_out"
	this.Status = &status
	return &this
}

// GetActionRequired returns the ActionRequired field value if set, zero value otherwise.
func (o *ModelEngineLogoutResponse) GetActionRequired() bool {
	if o == nil || IsNil(o.ActionRequired) {
		var ret bool
		return ret
	}
	return *o.ActionRequired
}

// GetActionRequiredOk returns a tuple with the ActionRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelEngineLogoutResponse) GetActionRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.ActionRequired) {
		return nil, false
	}
	return o.ActionRequired, true
}

// HasActionRequired returns a boolean if a field has been set.
func (o *ModelEngineLogoutResponse) HasActionRequired() bool {
	if o != nil && !IsNil(o.ActionRequired) {
		return true
	}

	return false
}

// SetActionRequired gets a reference to the given bool and assigns it to the ActionRequired field.
func (o *ModelEngineLogoutResponse) SetActionRequired(v bool) {
	o.ActionRequired = &v
}

// GetAdapter returns the Adapter field value
func (o *ModelEngineLogoutResponse) GetAdapter() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Adapter
}

// GetAdapterOk returns a tuple with the Adapter field value
// and a boolean to check if the value has been set.
func (o *ModelEngineLogoutResponse) GetAdapterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Adapter, true
}

// SetAdapter sets field value
func (o *ModelEngineLogoutResponse) SetAdapter(v string) {
	o.Adapter = v
}

// GetEngineRef returns the EngineRef field value
func (o *ModelEngineLogoutResponse) GetEngineRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EngineRef
}

// GetEngineRefOk returns a tuple with the EngineRef field value
// and a boolean to check if the value has been set.
func (o *ModelEngineLogoutResponse) GetEngineRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EngineRef, true
}

// SetEngineRef sets field value
func (o *ModelEngineLogoutResponse) SetEngineRef(v string) {
	o.EngineRef = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ModelEngineLogoutResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelEngineLogoutResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ModelEngineLogoutResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ModelEngineLogoutResponse) SetStatus(v string) {
	o.Status = &v
}

func (o ModelEngineLogoutResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelEngineLogoutResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ActionRequired) {
		toSerialize["actionRequired"] = o.ActionRequired
	}
	toSerialize["adapter"] = o.Adapter
	toSerialize["engineRef"] = o.EngineRef
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

func (o *ModelEngineLogoutResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"adapter",
		"engineRef",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelEngineLogoutResponse := _ModelEngineLogoutResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelEngineLogoutResponse)

	if err != nil {
		return err
	}

	*o = ModelEngineLogoutResponse(varModelEngineLogoutResponse)

	return err
}

type NullableModelEngineLogoutResponse struct {
	value *ModelEngineLogoutResponse
	isSet bool
}

func (v NullableModelEngineLogoutResponse) Get() *ModelEngineLogoutResponse {
	return v.value
}

func (v *NullableModelEngineLogoutResponse) Set(val *ModelEngineLogoutResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelEngineLogoutResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelEngineLogoutResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelEngineLogoutResponse(val *ModelEngineLogoutResponse) *NullableModelEngineLogoutResponse {
	return &NullableModelEngineLogoutResponse{value: val, isSet: true}
}

func (v NullableModelEngineLogoutResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelEngineLogoutResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
