/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpgradeRelease type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpgradeRelease{}

// UpgradeRelease struct for UpgradeRelease
type UpgradeRelease struct {
	Lts bool `json:"lts"`
	MinimumComponents map[string]string `json:"minimumComponents"`
	SchemaMigration string `json:"schemaMigration" validate:"regexp=^[0-9]{4}_.+\\.sql$"`
	SupportEndsOn string `json:"supportEndsOn"`
	SupportStartsOn string `json:"supportStartsOn"`
	Version string `json:"version" validate:"regexp=^[0-9]+\\.[0-9]+\\.[0-9]+$"`
}

type _UpgradeRelease UpgradeRelease

// NewUpgradeRelease instantiates a new UpgradeRelease object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpgradeRelease(lts bool, minimumComponents map[string]string, schemaMigration string, supportEndsOn string, supportStartsOn string, version string) *UpgradeRelease {
	this := UpgradeRelease{}
	this.Lts = lts
	this.MinimumComponents = minimumComponents
	this.SchemaMigration = schemaMigration
	this.SupportEndsOn = supportEndsOn
	this.SupportStartsOn = supportStartsOn
	this.Version = version
	return &this
}

// NewUpgradeReleaseWithDefaults instantiates a new UpgradeRelease object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpgradeReleaseWithDefaults() *UpgradeRelease {
	this := UpgradeRelease{}
	return &this
}

// GetLts returns the Lts field value
func (o *UpgradeRelease) GetLts() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Lts
}

// GetLtsOk returns a tuple with the Lts field value
// and a boolean to check if the value has been set.
func (o *UpgradeRelease) GetLtsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lts, true
}

// SetLts sets field value
func (o *UpgradeRelease) SetLts(v bool) {
	o.Lts = v
}

// GetMinimumComponents returns the MinimumComponents field value
func (o *UpgradeRelease) GetMinimumComponents() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.MinimumComponents
}

// GetMinimumComponentsOk returns a tuple with the MinimumComponents field value
// and a boolean to check if the value has been set.
func (o *UpgradeRelease) GetMinimumComponentsOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.MinimumComponents, true
}

// SetMinimumComponents sets field value
func (o *UpgradeRelease) SetMinimumComponents(v map[string]string) {
	o.MinimumComponents = v
}

// GetSchemaMigration returns the SchemaMigration field value
func (o *UpgradeRelease) GetSchemaMigration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SchemaMigration
}

// GetSchemaMigrationOk returns a tuple with the SchemaMigration field value
// and a boolean to check if the value has been set.
func (o *UpgradeRelease) GetSchemaMigrationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SchemaMigration, true
}

// SetSchemaMigration sets field value
func (o *UpgradeRelease) SetSchemaMigration(v string) {
	o.SchemaMigration = v
}

// GetSupportEndsOn returns the SupportEndsOn field value
func (o *UpgradeRelease) GetSupportEndsOn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SupportEndsOn
}

// GetSupportEndsOnOk returns a tuple with the SupportEndsOn field value
// and a boolean to check if the value has been set.
func (o *UpgradeRelease) GetSupportEndsOnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SupportEndsOn, true
}

// SetSupportEndsOn sets field value
func (o *UpgradeRelease) SetSupportEndsOn(v string) {
	o.SupportEndsOn = v
}

// GetSupportStartsOn returns the SupportStartsOn field value
func (o *UpgradeRelease) GetSupportStartsOn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SupportStartsOn
}

// GetSupportStartsOnOk returns a tuple with the SupportStartsOn field value
// and a boolean to check if the value has been set.
func (o *UpgradeRelease) GetSupportStartsOnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SupportStartsOn, true
}

// SetSupportStartsOn sets field value
func (o *UpgradeRelease) SetSupportStartsOn(v string) {
	o.SupportStartsOn = v
}

// GetVersion returns the Version field value
func (o *UpgradeRelease) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *UpgradeRelease) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *UpgradeRelease) SetVersion(v string) {
	o.Version = v
}

func (o UpgradeRelease) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpgradeRelease) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["lts"] = o.Lts
	toSerialize["minimumComponents"] = o.MinimumComponents
	toSerialize["schemaMigration"] = o.SchemaMigration
	toSerialize["supportEndsOn"] = o.SupportEndsOn
	toSerialize["supportStartsOn"] = o.SupportStartsOn
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *UpgradeRelease) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"lts",
		"minimumComponents",
		"schemaMigration",
		"supportEndsOn",
		"supportStartsOn",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpgradeRelease := _UpgradeRelease{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpgradeRelease)

	if err != nil {
		return err
	}

	*o = UpgradeRelease(varUpgradeRelease)

	return err
}

type NullableUpgradeRelease struct {
	value *UpgradeRelease
	isSet bool
}

func (v NullableUpgradeRelease) Get() *UpgradeRelease {
	return v.value
}

func (v *NullableUpgradeRelease) Set(val *UpgradeRelease) {
	v.value = val
	v.isSet = true
}

func (v NullableUpgradeRelease) IsSet() bool {
	return v.isSet
}

func (v *NullableUpgradeRelease) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpgradeRelease(val *UpgradeRelease) *NullableUpgradeRelease {
	return &NullableUpgradeRelease{value: val, isSet: true}
}

func (v NullableUpgradeRelease) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpgradeRelease) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
