/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"encoding/json"
	"fmt"
)

// PluginQuarantineState the model 'PluginQuarantineState'
type PluginQuarantineState string

// List of PluginQuarantineState
const (
	PLUGINQUARANTINESTATE_ACTIVE   PluginQuarantineState = "ACTIVE"
	PLUGINQUARANTINESTATE_RELEASED PluginQuarantineState = "RELEASED"
)

// All allowed values of PluginQuarantineState enum
var AllowedPluginQuarantineStateEnumValues = []PluginQuarantineState{
	"ACTIVE",
	"RELEASED",
}

func (v *PluginQuarantineState) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PluginQuarantineState(value)
	for _, existing := range AllowedPluginQuarantineStateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PluginQuarantineState", value)
}

// NewPluginQuarantineStateFromValue returns a pointer to a valid PluginQuarantineState
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPluginQuarantineStateFromValue(v string) (*PluginQuarantineState, error) {
	ev := PluginQuarantineState(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PluginQuarantineState: valid values are %v", v, AllowedPluginQuarantineStateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PluginQuarantineState) IsValid() bool {
	for _, existing := range AllowedPluginQuarantineStateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PluginQuarantineState value
func (v PluginQuarantineState) Ptr() *PluginQuarantineState {
	return &v
}

type NullablePluginQuarantineState struct {
	value *PluginQuarantineState
	isSet bool
}

func (v NullablePluginQuarantineState) Get() *PluginQuarantineState {
	return v.value
}

func (v *NullablePluginQuarantineState) Set(val *PluginQuarantineState) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginQuarantineState) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginQuarantineState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginQuarantineState(val *PluginQuarantineState) *NullablePluginQuarantineState {
	return &NullablePluginQuarantineState{value: val, isSet: true}
}

func (v NullablePluginQuarantineState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginQuarantineState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
