/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"encoding/json"
	"fmt"
)

// ServiceCompatibility the model 'ServiceCompatibility'
type ServiceCompatibility string

// List of ServiceCompatibility
const (
	SERVICECOMPATIBILITY_CURRENT            ServiceCompatibility = "CURRENT"
	SERVICECOMPATIBILITY_ROLLING_COMPATIBLE ServiceCompatibility = "ROLLING_COMPATIBLE"
	SERVICECOMPATIBILITY_UNSAFE             ServiceCompatibility = "UNSAFE"
)

// All allowed values of ServiceCompatibility enum
var AllowedServiceCompatibilityEnumValues = []ServiceCompatibility{
	"CURRENT",
	"ROLLING_COMPATIBLE",
	"UNSAFE",
}

func (v *ServiceCompatibility) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ServiceCompatibility(value)
	for _, existing := range AllowedServiceCompatibilityEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ServiceCompatibility", value)
}

// NewServiceCompatibilityFromValue returns a pointer to a valid ServiceCompatibility
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewServiceCompatibilityFromValue(v string) (*ServiceCompatibility, error) {
	ev := ServiceCompatibility(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ServiceCompatibility: valid values are %v", v, AllowedServiceCompatibilityEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ServiceCompatibility) IsValid() bool {
	for _, existing := range AllowedServiceCompatibilityEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ServiceCompatibility value
func (v ServiceCompatibility) Ptr() *ServiceCompatibility {
	return &v
}

type NullableServiceCompatibility struct {
	value *ServiceCompatibility
	isSet bool
}

func (v NullableServiceCompatibility) Get() *ServiceCompatibility {
	return v.value
}

func (v *NullableServiceCompatibility) Set(val *ServiceCompatibility) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceCompatibility) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceCompatibility) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceCompatibility(val *ServiceCompatibility) *NullableServiceCompatibility {
	return &NullableServiceCompatibility{value: val, isSet: true}
}

func (v NullableServiceCompatibility) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceCompatibility) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
