/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ImageDisplayMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageDisplayMetadata{}

// ImageDisplayMetadata Safe display and decoded-image facts; never storage access material.
type ImageDisplayMetadata struct {
	AltText      NullableString `json:"altText,omitempty"`
	Filename     NullableString `json:"filename,omitempty"`
	HeightPixels int32          `json:"heightPixels"`
	WidthPixels  int32          `json:"widthPixels"`
}

type _ImageDisplayMetadata ImageDisplayMetadata

// NewImageDisplayMetadata instantiates a new ImageDisplayMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageDisplayMetadata(heightPixels int32, widthPixels int32) *ImageDisplayMetadata {
	this := ImageDisplayMetadata{}
	this.HeightPixels = heightPixels
	this.WidthPixels = widthPixels
	return &this
}

// NewImageDisplayMetadataWithDefaults instantiates a new ImageDisplayMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageDisplayMetadataWithDefaults() *ImageDisplayMetadata {
	this := ImageDisplayMetadata{}
	return &this
}

// GetAltText returns the AltText field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ImageDisplayMetadata) GetAltText() string {
	if o == nil || IsNil(o.AltText.Get()) {
		var ret string
		return ret
	}
	return *o.AltText.Get()
}

// GetAltTextOk returns a tuple with the AltText field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ImageDisplayMetadata) GetAltTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AltText.Get(), o.AltText.IsSet()
}

// HasAltText returns a boolean if a field has been set.
func (o *ImageDisplayMetadata) HasAltText() bool {
	if o != nil && o.AltText.IsSet() {
		return true
	}

	return false
}

// SetAltText gets a reference to the given NullableString and assigns it to the AltText field.
func (o *ImageDisplayMetadata) SetAltText(v string) {
	o.AltText.Set(&v)
}

// SetAltTextNil sets the value for AltText to be an explicit nil
func (o *ImageDisplayMetadata) SetAltTextNil() {
	o.AltText.Set(nil)
}

// UnsetAltText ensures that no value is present for AltText, not even an explicit nil
func (o *ImageDisplayMetadata) UnsetAltText() {
	o.AltText.Unset()
}

// GetFilename returns the Filename field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ImageDisplayMetadata) GetFilename() string {
	if o == nil || IsNil(o.Filename.Get()) {
		var ret string
		return ret
	}
	return *o.Filename.Get()
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ImageDisplayMetadata) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Filename.Get(), o.Filename.IsSet()
}

// HasFilename returns a boolean if a field has been set.
func (o *ImageDisplayMetadata) HasFilename() bool {
	if o != nil && o.Filename.IsSet() {
		return true
	}

	return false
}

// SetFilename gets a reference to the given NullableString and assigns it to the Filename field.
func (o *ImageDisplayMetadata) SetFilename(v string) {
	o.Filename.Set(&v)
}

// SetFilenameNil sets the value for Filename to be an explicit nil
func (o *ImageDisplayMetadata) SetFilenameNil() {
	o.Filename.Set(nil)
}

// UnsetFilename ensures that no value is present for Filename, not even an explicit nil
func (o *ImageDisplayMetadata) UnsetFilename() {
	o.Filename.Unset()
}

// GetHeightPixels returns the HeightPixels field value
func (o *ImageDisplayMetadata) GetHeightPixels() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.HeightPixels
}

// GetHeightPixelsOk returns a tuple with the HeightPixels field value
// and a boolean to check if the value has been set.
func (o *ImageDisplayMetadata) GetHeightPixelsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HeightPixels, true
}

// SetHeightPixels sets field value
func (o *ImageDisplayMetadata) SetHeightPixels(v int32) {
	o.HeightPixels = v
}

// GetWidthPixels returns the WidthPixels field value
func (o *ImageDisplayMetadata) GetWidthPixels() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WidthPixels
}

// GetWidthPixelsOk returns a tuple with the WidthPixels field value
// and a boolean to check if the value has been set.
func (o *ImageDisplayMetadata) GetWidthPixelsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WidthPixels, true
}

// SetWidthPixels sets field value
func (o *ImageDisplayMetadata) SetWidthPixels(v int32) {
	o.WidthPixels = v
}

func (o ImageDisplayMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageDisplayMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AltText.IsSet() {
		toSerialize["altText"] = o.AltText.Get()
	}
	if o.Filename.IsSet() {
		toSerialize["filename"] = o.Filename.Get()
	}
	toSerialize["heightPixels"] = o.HeightPixels
	toSerialize["widthPixels"] = o.WidthPixels
	return toSerialize, nil
}

func (o *ImageDisplayMetadata) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"heightPixels",
		"widthPixels",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImageDisplayMetadata := _ImageDisplayMetadata{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImageDisplayMetadata)

	if err != nil {
		return err
	}

	*o = ImageDisplayMetadata(varImageDisplayMetadata)

	return err
}

type NullableImageDisplayMetadata struct {
	value *ImageDisplayMetadata
	isSet bool
}

func (v NullableImageDisplayMetadata) Get() *ImageDisplayMetadata {
	return v.value
}

func (v *NullableImageDisplayMetadata) Set(val *ImageDisplayMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableImageDisplayMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableImageDisplayMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageDisplayMetadata(val *ImageDisplayMetadata) *NullableImageDisplayMetadata {
	return &NullableImageDisplayMetadata{value: val, isSet: true}
}

func (v NullableImageDisplayMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageDisplayMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
