/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"encoding/json"
	"fmt"
)

// PolicyScope the model 'PolicyScope'
type PolicyScope string

// List of PolicyScope
const (
	POLICYSCOPE_INSTANCE  PolicyScope = "INSTANCE"
	POLICYSCOPE_TENANT    PolicyScope = "TENANT"
	POLICYSCOPE_NAMESPACE PolicyScope = "NAMESPACE"
)

// All allowed values of PolicyScope enum
var AllowedPolicyScopeEnumValues = []PolicyScope{
	"INSTANCE",
	"TENANT",
	"NAMESPACE",
}

func (v *PolicyScope) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PolicyScope(value)
	for _, existing := range AllowedPolicyScopeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PolicyScope", value)
}

// NewPolicyScopeFromValue returns a pointer to a valid PolicyScope
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPolicyScopeFromValue(v string) (*PolicyScope, error) {
	ev := PolicyScope(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PolicyScope: valid values are %v", v, AllowedPolicyScopeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PolicyScope) IsValid() bool {
	for _, existing := range AllowedPolicyScopeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PolicyScope value
func (v PolicyScope) Ptr() *PolicyScope {
	return &v
}

type NullablePolicyScope struct {
	value *PolicyScope
	isSet bool
}

func (v NullablePolicyScope) Get() *PolicyScope {
	return v.value
}

func (v *NullablePolicyScope) Set(val *PolicyScope) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyScope) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyScope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyScope(val *PolicyScope) *NullablePolicyScope {
	return &NullablePolicyScope{value: val, isSet: true}
}

func (v NullablePolicyScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyScope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
