/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the CapabilityCatalog type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CapabilityCatalog{}

// CapabilityCatalog struct for CapabilityCatalog
type CapabilityCatalog struct {
	CatalogDigest string                   `json:"catalogDigest" validate:"regexp=^sha256:[0-9a-f]{64}$"`
	GeneratedAt   time.Time                `json:"generatedAt"`
	Items         []CapabilityCatalogItem  `json:"items,omitempty"`
	Namespace     NullableString           `json:"namespace,omitempty"`
	Returned      int32                    `json:"returned"`
	SchemaVersion *string                  `json:"schemaVersion,omitempty"`
	SourceAccess  []CapabilitySourceAccess `json:"sourceAccess,omitempty"`
	Total         int32                    `json:"total"`
	Truncated     *bool                    `json:"truncated,omitempty"`
}

type _CapabilityCatalog CapabilityCatalog

// NewCapabilityCatalog instantiates a new CapabilityCatalog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCapabilityCatalog(catalogDigest string, generatedAt time.Time, returned int32, total int32) *CapabilityCatalog {
	this := CapabilityCatalog{}
	this.CatalogDigest = catalogDigest
	this.GeneratedAt = generatedAt
	this.Returned = returned
	var schemaVersion string = "amesh.capability-catalog/v1"
	this.SchemaVersion = &schemaVersion
	this.Total = total
	var truncated bool = false
	this.Truncated = &truncated
	return &this
}

// NewCapabilityCatalogWithDefaults instantiates a new CapabilityCatalog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCapabilityCatalogWithDefaults() *CapabilityCatalog {
	this := CapabilityCatalog{}
	var schemaVersion string = "amesh.capability-catalog/v1"
	this.SchemaVersion = &schemaVersion
	var truncated bool = false
	this.Truncated = &truncated
	return &this
}

// GetCatalogDigest returns the CatalogDigest field value
func (o *CapabilityCatalog) GetCatalogDigest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CatalogDigest
}

// GetCatalogDigestOk returns a tuple with the CatalogDigest field value
// and a boolean to check if the value has been set.
func (o *CapabilityCatalog) GetCatalogDigestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CatalogDigest, true
}

// SetCatalogDigest sets field value
func (o *CapabilityCatalog) SetCatalogDigest(v string) {
	o.CatalogDigest = v
}

// GetGeneratedAt returns the GeneratedAt field value
func (o *CapabilityCatalog) GetGeneratedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.GeneratedAt
}

// GetGeneratedAtOk returns a tuple with the GeneratedAt field value
// and a boolean to check if the value has been set.
func (o *CapabilityCatalog) GetGeneratedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GeneratedAt, true
}

// SetGeneratedAt sets field value
func (o *CapabilityCatalog) SetGeneratedAt(v time.Time) {
	o.GeneratedAt = v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *CapabilityCatalog) GetItems() []CapabilityCatalogItem {
	if o == nil || IsNil(o.Items) {
		var ret []CapabilityCatalogItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityCatalog) GetItemsOk() ([]CapabilityCatalogItem, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *CapabilityCatalog) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []CapabilityCatalogItem and assigns it to the Items field.
func (o *CapabilityCatalog) SetItems(v []CapabilityCatalogItem) {
	o.Items = v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CapabilityCatalog) GetNamespace() string {
	if o == nil || IsNil(o.Namespace.Get()) {
		var ret string
		return ret
	}
	return *o.Namespace.Get()
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CapabilityCatalog) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Namespace.Get(), o.Namespace.IsSet()
}

// HasNamespace returns a boolean if a field has been set.
func (o *CapabilityCatalog) HasNamespace() bool {
	if o != nil && o.Namespace.IsSet() {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given NullableString and assigns it to the Namespace field.
func (o *CapabilityCatalog) SetNamespace(v string) {
	o.Namespace.Set(&v)
}

// SetNamespaceNil sets the value for Namespace to be an explicit nil
func (o *CapabilityCatalog) SetNamespaceNil() {
	o.Namespace.Set(nil)
}

// UnsetNamespace ensures that no value is present for Namespace, not even an explicit nil
func (o *CapabilityCatalog) UnsetNamespace() {
	o.Namespace.Unset()
}

// GetReturned returns the Returned field value
func (o *CapabilityCatalog) GetReturned() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Returned
}

// GetReturnedOk returns a tuple with the Returned field value
// and a boolean to check if the value has been set.
func (o *CapabilityCatalog) GetReturnedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Returned, true
}

// SetReturned sets field value
func (o *CapabilityCatalog) SetReturned(v int32) {
	o.Returned = v
}

// GetSchemaVersion returns the SchemaVersion field value if set, zero value otherwise.
func (o *CapabilityCatalog) GetSchemaVersion() string {
	if o == nil || IsNil(o.SchemaVersion) {
		var ret string
		return ret
	}
	return *o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityCatalog) GetSchemaVersionOk() (*string, bool) {
	if o == nil || IsNil(o.SchemaVersion) {
		return nil, false
	}
	return o.SchemaVersion, true
}

// HasSchemaVersion returns a boolean if a field has been set.
func (o *CapabilityCatalog) HasSchemaVersion() bool {
	if o != nil && !IsNil(o.SchemaVersion) {
		return true
	}

	return false
}

// SetSchemaVersion gets a reference to the given string and assigns it to the SchemaVersion field.
func (o *CapabilityCatalog) SetSchemaVersion(v string) {
	o.SchemaVersion = &v
}

// GetSourceAccess returns the SourceAccess field value if set, zero value otherwise.
func (o *CapabilityCatalog) GetSourceAccess() []CapabilitySourceAccess {
	if o == nil || IsNil(o.SourceAccess) {
		var ret []CapabilitySourceAccess
		return ret
	}
	return o.SourceAccess
}

// GetSourceAccessOk returns a tuple with the SourceAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityCatalog) GetSourceAccessOk() ([]CapabilitySourceAccess, bool) {
	if o == nil || IsNil(o.SourceAccess) {
		return nil, false
	}
	return o.SourceAccess, true
}

// HasSourceAccess returns a boolean if a field has been set.
func (o *CapabilityCatalog) HasSourceAccess() bool {
	if o != nil && !IsNil(o.SourceAccess) {
		return true
	}

	return false
}

// SetSourceAccess gets a reference to the given []CapabilitySourceAccess and assigns it to the SourceAccess field.
func (o *CapabilityCatalog) SetSourceAccess(v []CapabilitySourceAccess) {
	o.SourceAccess = v
}

// GetTotal returns the Total field value
func (o *CapabilityCatalog) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *CapabilityCatalog) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *CapabilityCatalog) SetTotal(v int32) {
	o.Total = v
}

// GetTruncated returns the Truncated field value if set, zero value otherwise.
func (o *CapabilityCatalog) GetTruncated() bool {
	if o == nil || IsNil(o.Truncated) {
		var ret bool
		return ret
	}
	return *o.Truncated
}

// GetTruncatedOk returns a tuple with the Truncated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityCatalog) GetTruncatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Truncated) {
		return nil, false
	}
	return o.Truncated, true
}

// HasTruncated returns a boolean if a field has been set.
func (o *CapabilityCatalog) HasTruncated() bool {
	if o != nil && !IsNil(o.Truncated) {
		return true
	}

	return false
}

// SetTruncated gets a reference to the given bool and assigns it to the Truncated field.
func (o *CapabilityCatalog) SetTruncated(v bool) {
	o.Truncated = &v
}

func (o CapabilityCatalog) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CapabilityCatalog) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["catalogDigest"] = o.CatalogDigest
	toSerialize["generatedAt"] = o.GeneratedAt
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if o.Namespace.IsSet() {
		toSerialize["namespace"] = o.Namespace.Get()
	}
	toSerialize["returned"] = o.Returned
	if !IsNil(o.SchemaVersion) {
		toSerialize["schemaVersion"] = o.SchemaVersion
	}
	if !IsNil(o.SourceAccess) {
		toSerialize["sourceAccess"] = o.SourceAccess
	}
	toSerialize["total"] = o.Total
	if !IsNil(o.Truncated) {
		toSerialize["truncated"] = o.Truncated
	}
	return toSerialize, nil
}

func (o *CapabilityCatalog) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"catalogDigest",
		"generatedAt",
		"returned",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCapabilityCatalog := _CapabilityCatalog{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCapabilityCatalog)

	if err != nil {
		return err
	}

	*o = CapabilityCatalog(varCapabilityCatalog)

	return err
}

type NullableCapabilityCatalog struct {
	value *CapabilityCatalog
	isSet bool
}

func (v NullableCapabilityCatalog) Get() *CapabilityCatalog {
	return v.value
}

func (v *NullableCapabilityCatalog) Set(val *CapabilityCatalog) {
	v.value = val
	v.isSet = true
}

func (v NullableCapabilityCatalog) IsSet() bool {
	return v.isSet
}

func (v *NullableCapabilityCatalog) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCapabilityCatalog(val *CapabilityCatalog) *NullableCapabilityCatalog {
	return &NullableCapabilityCatalog{value: val, isSet: true}
}

func (v NullableCapabilityCatalog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCapabilityCatalog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
