/*
AMESH

Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ameshclient

import (
	"encoding/json"
	"fmt"
)

// AgentCeilingMode the model 'AgentCeilingMode'
type AgentCeilingMode string

// List of AgentCeilingMode
const (
	AGENTCEILINGMODE_BOUNDED          AgentCeilingMode = "BOUNDED"
	AGENTCEILINGMODE_PROVIDER_BOUNDED AgentCeilingMode = "PROVIDER_BOUNDED"
)

// All allowed values of AgentCeilingMode enum
var AllowedAgentCeilingModeEnumValues = []AgentCeilingMode{
	"BOUNDED",
	"PROVIDER_BOUNDED",
}

func (v *AgentCeilingMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AgentCeilingMode(value)
	for _, existing := range AllowedAgentCeilingModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AgentCeilingMode", value)
}

// NewAgentCeilingModeFromValue returns a pointer to a valid AgentCeilingMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAgentCeilingModeFromValue(v string) (*AgentCeilingMode, error) {
	ev := AgentCeilingMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AgentCeilingMode: valid values are %v", v, AllowedAgentCeilingModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AgentCeilingMode) IsValid() bool {
	for _, existing := range AllowedAgentCeilingModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AgentCeilingMode value
func (v AgentCeilingMode) Ptr() *AgentCeilingMode {
	return &v
}

type NullableAgentCeilingMode struct {
	value *AgentCeilingMode
	isSet bool
}

func (v NullableAgentCeilingMode) Get() *AgentCeilingMode {
	return v.value
}

func (v *NullableAgentCeilingMode) Set(val *AgentCeilingMode) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentCeilingMode) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentCeilingMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentCeilingMode(val *AgentCeilingMode) *NullableAgentCeilingMode {
	return &NullableAgentCeilingMode{value: val, isSet: true}
}

func (v NullableAgentCeilingMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentCeilingMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
