{{- if .Values.network.policy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "amesh.fullname" . }}-components
  labels:
    {{- include "amesh.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "amesh.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            {{- toYaml .Values.network.policy.ingressNamespaceSelector | nindent 12 }}
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- range .Values.network.policy.egressCidrs }}
    - to:
        - ipBlock:
            cidr: {{ . | quote }}
    {{- end }}
{{- end }}
