apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "amesh.fullname" . }}-task-runner
  labels:
    {{- include "amesh.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "amesh.fullname" . }}-task-runner
  labels:
    {{- include "amesh.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "amesh.fullname" . }}-task-runner
subjects:
  - kind: ServiceAccount
    name: {{ include "amesh.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
