apiVersion: v1
kind: Service
metadata:
  name: {{ include "amesh.fullname" . }}
  labels:
    {{- include "amesh.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "amesh.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
