"""Original-order feature-router composition manifest."""

ROUTE_SEQUENCE: tuple[tuple[str, str, str], ...] = (
    ("feature", "system", "router_1"),
    ("factory", "promotion", ""),
    ("factory", "model_engines", ""),
    ("factory", "differential", ""),
    ("feature", "agents", "router_1"),
    ("feature", "system", "router_2"),
    ("feature", "catalog", "router_1"),
    ("feature", "platform", "router_1"),
    ("feature", "session_administration", "router_1"),
    ("feature", "platform", "router_2"),
    ("feature", "operations", "router_1"),
    ("feature", "platform", "router_3"),
    ("feature", "operations", "router_2"),
    ("feature", "identity", "router_1"),
    ("feature", "system", "router_3"),
    ("feature", "workflows", "router_1"),
    ("feature", "namespace_resources", "router_1"),
    ("feature", "workflows", "router_2"),
    ("feature", "flow_quality", "router_1"),
    ("feature", "workflows", "router_3"),
    ("feature", "triggers", "router_1"),
    ("feature", "executions", "router_1"),
    ("feature", "triggers", "router_2"),
    ("feature", "executions", "router_2"),
    ("feature", "operations", "router_3"),
    ("feature", "executions", "router_3"),
    ("feature", "agent_sessions", "router_1"),
    ("feature", "session_administration", "router_2"),
    ("feature", "agent_sessions", "router_2"),
    ("feature", "session_administration", "router_3"),
    ("feature", "executions", "router_4"),
    ("feature", "realtime", "router_1"),
    ("feature", "executions", "router_5"),
    ("feature", "triggers", "router_3"),
    ("feature", "governance", "router_1"),
    ("feature", "executions", "router_6"),
    ("feature", "governance", "router_2"),
    ("feature", "workflows", "router_4"),
)
