# coding: utf-8

"""
    AMESH

    Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from amesh_client.models.agent_context_receipt import AgentContextReceipt
from amesh_client.models.agent_harness_pin import AgentHarnessPin
from amesh_client.models.agent_session_counters import AgentSessionCounters
from amesh_client.models.agent_session_phase import AgentSessionPhase
from amesh_client.models.agent_session_state import AgentSessionState
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentSessionSummary(BaseModel):
    """
    Redacted session state safe for execution-scoped inspection.
    """ # noqa: E501
    agent_ref: Optional[StrictStr] = Field(default=None, alias="agentRef")
    attempt: Annotated[int, Field(strict=True, ge=1)]
    capability_pin_id: UUID = Field(alias="capabilityPinId")
    completed_at: Optional[datetime] = Field(default=None, alias="completedAt")
    context_receipt: Optional[AgentContextReceipt] = Field(default=None, alias="contextReceipt")
    counters: AgentSessionCounters
    created_at: datetime = Field(alias="createdAt")
    envelope_digest: StrictStr = Field(alias="envelopeDigest")
    error: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = None
    execution_id: UUID = Field(alias="executionId")
    final_result: Optional[Dict[str, Any]] = Field(default=None, alias="finalResult")
    harness: Optional[AgentHarnessPin] = None
    model_profile: Optional[StrictStr] = Field(default=None, alias="modelProfile")
    namespace: Annotated[str, Field(min_length=1, strict=True, max_length=255)]
    phase: AgentSessionPhase
    session_id: UUID = Field(alias="sessionId")
    state: AgentSessionState
    task_run_id: UUID = Field(alias="taskRunId")
    tenant_id: StrictStr = Field(alias="tenantId")
    updated_at: datetime = Field(alias="updatedAt")
    version: Annotated[int, Field(strict=True, ge=0)]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["agentRef", "attempt", "capabilityPinId", "completedAt", "contextReceipt", "counters", "createdAt", "envelopeDigest", "error", "executionId", "finalResult", "harness", "modelProfile", "namespace", "phase", "sessionId", "state", "taskRunId", "tenantId", "updatedAt", "version"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentSessionSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of context_receipt
        if self.context_receipt:
            _dict['contextReceipt'] = self.context_receipt.to_dict()
        # override the default output from pydantic by calling `to_dict()` of counters
        if self.counters:
            _dict['counters'] = self.counters.to_dict()
        # override the default output from pydantic by calling `to_dict()` of harness
        if self.harness:
            _dict['harness'] = self.harness.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if agent_ref (nullable) is None
        # and model_fields_set contains the field
        if self.agent_ref is None and "agent_ref" in self.model_fields_set:
            _dict['agentRef'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completedAt'] = None

        # set to None if context_receipt (nullable) is None
        # and model_fields_set contains the field
        if self.context_receipt is None and "context_receipt" in self.model_fields_set:
            _dict['contextReceipt'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if final_result (nullable) is None
        # and model_fields_set contains the field
        if self.final_result is None and "final_result" in self.model_fields_set:
            _dict['finalResult'] = None

        # set to None if harness (nullable) is None
        # and model_fields_set contains the field
        if self.harness is None and "harness" in self.model_fields_set:
            _dict['harness'] = None

        # set to None if model_profile (nullable) is None
        # and model_fields_set contains the field
        if self.model_profile is None and "model_profile" in self.model_fields_set:
            _dict['modelProfile'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentSessionSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agentRef": obj.get("agentRef"),
            "attempt": obj.get("attempt"),
            "capabilityPinId": obj.get("capabilityPinId"),
            "completedAt": obj.get("completedAt"),
            "contextReceipt": AgentContextReceipt.from_dict(obj["contextReceipt"]) if obj.get("contextReceipt") is not None else None,
            "counters": AgentSessionCounters.from_dict(obj["counters"]) if obj.get("counters") is not None else None,
            "createdAt": obj.get("createdAt"),
            "envelopeDigest": obj.get("envelopeDigest"),
            "error": obj.get("error"),
            "executionId": obj.get("executionId"),
            "finalResult": obj.get("finalResult"),
            "harness": AgentHarnessPin.from_dict(obj["harness"]) if obj.get("harness") is not None else None,
            "modelProfile": obj.get("modelProfile"),
            "namespace": obj.get("namespace"),
            "phase": obj.get("phase"),
            "sessionId": obj.get("sessionId"),
            "state": obj.get("state"),
            "taskRunId": obj.get("taskRunId"),
            "tenantId": obj.get("tenantId"),
            "updatedAt": obj.get("updatedAt"),
            "version": obj.get("version")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
