# coding: utf-8

"""
    AMESH

    Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from amesh_client.models.plugin_policy_effect import PluginPolicyEffect
from amesh_client.models.plugin_policy_rule import PluginPolicyRule
from amesh_client.models.plugin_quarantine import PluginQuarantine
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EffectivePluginPolicy(BaseModel):
    """
    EffectivePluginPolicy
    """ # noqa: E501
    default_effect: PluginPolicyEffect = Field(alias="defaultEffect")
    namespace: Optional[StrictStr] = None
    quarantines: List[PluginQuarantine]
    rules: List[PluginPolicyRule]
    tenant_id: StrictStr = Field(alias="tenantId")
    __properties: ClassVar[List[str]] = ["defaultEffect", "namespace", "quarantines", "rules", "tenantId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EffectivePluginPolicy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in quarantines (list)
        _items = []
        if self.quarantines:
            for _item_quarantines in self.quarantines:
                if _item_quarantines:
                    _items.append(_item_quarantines.to_dict())
            _dict['quarantines'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in rules (list)
        _items = []
        if self.rules:
            for _item_rules in self.rules:
                if _item_rules:
                    _items.append(_item_rules.to_dict())
            _dict['rules'] = _items
        # set to None if namespace (nullable) is None
        # and model_fields_set contains the field
        if self.namespace is None and "namespace" in self.model_fields_set:
            _dict['namespace'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EffectivePluginPolicy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "defaultEffect": obj.get("defaultEffect"),
            "namespace": obj.get("namespace"),
            "quarantines": [PluginQuarantine.from_dict(_item) for _item in obj["quarantines"]] if obj.get("quarantines") is not None else None,
            "rules": [PluginPolicyRule.from_dict(_item) for _item in obj["rules"]] if obj.get("rules") is not None else None,
            "tenantId": obj.get("tenantId")
        })
        return _obj
