# coding: utf-8

"""
    AMESH

    Clean-room durable workflow MVP with validated flow management, execution control, webhook triggers and execution logs.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from amesh_client.models.plugin_policy_scope import PluginPolicyScope
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PluginQuarantineCreate(BaseModel):
    """
    PluginQuarantineCreate
    """ # noqa: E501
    namespace: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=255)]] = None
    package: Annotated[str, Field(min_length=1, strict=True, max_length=255)]
    reason: Annotated[str, Field(min_length=1, strict=True, max_length=2048)]
    scope: Optional[PluginPolicyScope] = None
    version: Annotated[str, Field(min_length=1, strict=True, max_length=128)]
    __properties: ClassVar[List[str]] = ["namespace", "package", "reason", "scope", "version"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PluginQuarantineCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if namespace (nullable) is None
        # and model_fields_set contains the field
        if self.namespace is None and "namespace" in self.model_fields_set:
            _dict['namespace'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PluginQuarantineCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "namespace": obj.get("namespace"),
            "package": obj.get("package"),
            "reason": obj.get("reason"),
            "scope": obj.get("scope"),
            "version": obj.get("version")
        })
        return _obj
